### ISSUE TITLE
ng2- RC6 : sdk/index.ts @angular/htttp has no exported mng 'HTTP_PROVIDERS'

### ISSUE THREAD

**Issue by sprypradeep** [mean-expert-official/loopback-sdk-builder#104]
sdk/index.ts Module @angular/htttp/index has no exported mng 'HTTP_PROVIDERS', with rc.6 

I removed it as import and exports from index.ts to resolve.

**Comment by jonathan-casarrubias** [comment]
Closing this in favor of https://github.com/mean-expert-official/loopback-sdk-builder/issues/100
