### ISSUE TITLE
Add Bidirectional IO Messaging for custom messaging

### ISSUE THREAD

**Issue by jonathan-casarrubias** [mean-expert-official/loopback-sdk-builder#112]
Currently the builder allows to subscribe to events sent by the server but would be great to allow custom events to be sent.

**Comment by dmastag** [comment]
Does this include sending the AccessToken when subscribing to the events?

**Comment by jonathan-casarrubias** [comment]
Hello @dmastag, currently the PubSub functionality already have an authentication mechanism that when is enabled the SDK Builder sends the AccessToken to be authenticated in the server side and this last one automatically authenticates when recive a token.

If I develop this feature, this will be for you to send any custom event message to be received by other clients that are not tied to any endpoint, using the server only for singling purposes. This would not be part of the PubSub functionality. But, it will definitely share the authentication mechanism.

Just to be clear, this will be a different pattern to achieve real-time applications, but in the low level will share the same authentication mechanism.

Hope this clarifies the scope of this issue.

Cheers!!!
Jon

**Comment by jonathan-casarrubias** [comment]
https://github.com/mean-expert-official/loopback-component-realtime/issues/7
