### ISSUE TITLE
change-stream endpoint msg missing type

### ISSUE THREAD

**Issue by duffn** [mean-expert-official/loopback-sdk-builder#114]
In the `change-stream` endpoint of a custom service, the msg variable on line 42 is missing a type. If enabled, tslint throws an error on this.

`error TS7006: Parameter 'msg' implicitly has an 'any' type.`

https://github.com/mean-expert-official/loopback-sdk-builder/blob/master/lib/angular2/shared/services/custom/service.ejs#L42

**Comment by jonathan-casarrubias** [comment]
Hi @duffn thanks for reporting, the ng lint command did not show that error when I published, do you know which rule is that so I can enable it and make sure it does not happen for you again?.

I will add this fix for the next release.

Cheers!
Jon

**Comment by duffn** [comment]
@jonathan-casarrubias It appears to be `"noImplicitAny"`

**Comment by jonathan-casarrubias** [comment]
@duffn I added that rule to tsconfig for the test application, now I get a bunch of errors lol..

Is unfortunate that angular-cli in the latest version does not set by default that rule.

Anyway, once I fix all the implicit any issues I will add this to the next release.

Cheers!
Jon
