### ISSUE TITLE
Supporting angular1 lb-ng

### ISSUE THREAD

**Issue by dooddy** [mean-expert-official/loopback-sdk-builder#115]
Hi. I found some problem. I don't know after which of releases, but in lb-ng file you console warning message that i should use lb-sdk. But in my app in different parts I use different angulars. It sounds strange but it's fact. Can we do something with this?

**Comment by jonathan-casarrubias** [comment]
Hi @dooddy before stable versions I left the lb-ng command with the message saying is deprecated, but after stable releases the lb-ng is not longer provided.

If you clean your node_modules at least the part related to loopback-sdk-builder and install again you won't have the lb-ng command from the builder, then you will be able to also install the loopback-sdk-angular and create your sdks for NG1.

The builder won't support Angular 1 by any terms, but the issue of lb-ng commands collisions is not present in the latests versions.

Again, my recommendation now is to have both packages and use lb-ng for ng1 y lb-sdk for ng2

Cheers
