### ISSUE TITLE
Cannot find module 'socket.io-client'

### ISSUE THREAD

**Issue by k3n3l** [mean-expert-official/loopback-sdk-builder#119]
Hi:

When I run the service this send the error 
`ERROR in [default] {{ base_path }}/src/app/shared/sdk/sockets/socket.driver.ts:2:20 
Cannot find module 'socket.io-client'`

I am working with:
 * Angular 2.0.0 (created with angular-cli)
 * socket.io-client has been installed (v1.4.8).

Could you help me, please ???
Best Regards.

**Comment by hmtai6** [comment]
May be you haven't install socket.io-client typings 

try to use
npm install typings --global
typings install socket.io-client --global --save

**Comment by jonathan-casarrubias** [comment]
Hi @k3n3l Sure!!! Thanks for reaching me out.

It seems that there is 1 step missing in the documentation:

````sh
$ cd /to/ng-project/
$ npm install --save-dev @types/socket.io-client
````

Then within the src directory there is a `tsconfig.json` file. Open it and then add the following

````json
{
  "compilerOptions": {
  ...
    "types": [
        "socket.io-client"
    ]
  }
}
````

Cheers
Jon

**Comment by jonathan-casarrubias** [comment]
Hi @hmtai6 thanks for contributing with your answer, I just want to clarify that the typings approach will be deprecated in favour of https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/

Currently Typescript provides an official way to install types that you can search and find in [HERE!!!!](http://microsoft.github.io/TypeSearch/)

Cheers!!!
Jon

**Comment by jonathan-casarrubias** [comment]
I have just added this information within the [wiki documentation](https://github.com/mean-expert-official/loopback-sdk-builder/wiki/2.-Setup-SDK#install-socket-io-type)

**Comment by k3n3l** [comment]
Thanks @jonathan-casarrubias

**Comment by barocsi** [comment]
How to disable real time communication when generating the sdk hence not requiring the installation of this?

**Comment by jonathan-casarrubias** [comment]
use the flag -i disabled when generating the sdk
