### ISSUE TITLE
(2.1 Beta) SDK tries to export real.time module when generating with real time disabled

### ISSUE THREAD

**Issue by bostondv** [mean-expert-official/loopback-sdk-builder#140]
Run `./node_modules/.bin/lb-sdk server/server path/to/client/src/app/shared/sdk -l angular2 -d ng4web -i disabled`

Generated SDK includes an export for `app/shared/sdk/services/core/real.time.ts` within `app/shared/sdk/services/core/index.ts` but `real.time.ts` doesn't exist.

With real time module disabled, this export shouldn't exist I think :)

**Comment by jonathan-casarrubias** [comment]
@bostondv yup that is right, looks like there is a missing validation... That is why the realtime does not exist, but the reference shouldn't neither..

I will fix this issue ASAP.

BTW: If you don't need the realtime functionality, then you may want to try the latest stable version which is the 2.0.10. That version does not include anything related to the RealTime service and FireLoop.

Cheers
Jon

**Comment by bostondv** [comment]
Awesome, I don't need it right now so I'll try 2.0.10 :)

**Comment by jonathan-casarrubias** [comment]
Fixed
