### ISSUE TITLE
Various AccessToken model errors

### ISSUE THREAD

**Issue by bostondv** [mean-expert-official/loopback-sdk-builder#141]
I'm getting various errors related to the AccessToken in the generated SDK's.

This is the output of running `ng serve` with a CLI generated project.

```
ERROR in ./src/app/shared/sdk/models/BaseModels.ts
Module not found: Error: Can't resolve 'AccessToken' in '/path/to/client/src/app/shared/sdk/models'
 @ ./src/app/shared/sdk/models/BaseModels.ts 7:0-21
 @ ./src/app/shared/sdk/models/index.ts
 @ ./src/app/shared/sdk/index.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in [default] /path/to/client/src/app/shared/sdk/models/BaseModels.ts:3:21
';' expected.

ERROR in [default] /path/to/client/src/app/shared/sdk/models/BaseModels.ts:3:21
Cannot find name 'from'.

ERROR in [default] /path/to/client/src/app/shared/sdk/models/BaseModels.ts:3:26
';' expected.

ERROR in [default] /path/to/client/src/app/shared/sdk/models/BaseModels.ts:16:30
Cannot find name 'AccessToken'.

ERROR in [default] /path/to/client/src/app/shared/sdk/models/BaseModels.ts:23:27
Cannot find name 'AccessToken'.

ERROR in [default] /path/to/client/src/app/shared/sdk/services/core/auth.service.ts:7:9
Module '"/path/to/client/src/app/shared/sdk/models/BaseModels"' has no exported member 'AccessToken'.

ERROR in [default] /path/to/client/src/app/shared/sdk/services/custom/Person.ts:14:9
Duplicate identifier 'AccessToken'.

ERROR in [default] /path/to/client/src/app/shared/sdk/services/custom/Person.ts:15:9
Duplicate identifier 'AccessToken'.
```

For `sdk/models/BaseModels.ts` I believe there are two issues:

1. Change `import 'AccessToken' from './AccessToken';` to `import { AccessToken } from './AccessToken';` which fixes all except last 3 errors.

2. Change `userId: string = null;` in SDKToken class to `userId: number = null;`

The other couple errors I think are simple import mistakes in the generated code?

**Comment by jonathan-casarrubias** [comment]
@bostondv quick question... Did you published the AccessToken? by default is not public within the cd/to/loopback/server/model-config.json.

Most of the cases this model should not be exposed.

A long time ago I verified it should work when people enables the AccessToken model, but it may got broken in some version.

So I will verify the tests and publish the AccessToken model to see if I can replicate your issue.

Cheers
Jon

**Comment by bostondv** [comment]
Yeah I did have it published (for testing). Once I unpublished it and went
back to stable 2.0.10 SDK generated without errors.

**Comment by jonathan-casarrubias** [comment]
@bostondv thanks for looking at it.. I will set the bug label then, since it should work in both cases regardless the percentage of people using it in public.

Cheers
jon

**Comment by jonathan-casarrubias** [comment]
Fixed
