### ISSUE TITLE
Rollup Compile Err in sdk/service/core/error.service.ts

### ISSUE THREAD

**Issue by kattsushi** [mean-expert-official/loopback-sdk-builder#153]
When compiling with rollup, returns this error

Return type of public method from exported class has or is using name 'ErrorObservable' from external module "/home/andres/Gatey-movil/node_modules/rxjs/observable/ErrorObservable" but cannot be named.

in sdk/service/core/error.service.ts

**Comment by kattsushi** [comment]
to resolve this bug, when generating the sdk, you must import Error Observable from 'rxjs/observable/ErrorObservable'; like that

`/* tslint:disable */
import { Injectable } from '@angular/core';
import { Response } from '@angular/http';
import { Observable } from 'rxjs/Observable';
import { ErrorObservable } from 'rxjs/observable/ErrorObservable'; <<--
import 'rxjs/add/observable/throw';
/**
 * Default error handler
 */
@Injectable()
export class ErrorHandler {
  public handleError(error: Response) {
    return Observable.throw(error.json().error || 'Server error');
  }
}
`

I also found another similar bug but this time in the /sdk/services/core/base.service.ts file when the Observable be imported for the method requests like that work

`/* tslint:disable */
import { Injectable, Inject, Optional } from '@angular/core';
import { Http, Headers, Request } from '@angular/http';
import { NgModule, ModuleWithProviders } from '@angular/core';
import { JSONSearchParams } from './search.params';
import { ErrorHandler } from './error.service';
import { LoopBackAuth } from './auth.service';
import { LoopBackConfig } from '../../lb.config';
import { AccessToken } from '../../models';
import { Observable } from 'rxjs/Observable'; // <<<<<<<<
import { ErrorObservable } from 'rxjs/observable/ErrorObservable';
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/map';
/**
* @module BaseLoopBackApi
* @author Nikolay Matiushenkov <https://github.com/mnvx>
* @contributor Jonathan Casarrubias <@johncasarrubias> <github:jonathan-casarrubias>
* @license MTI
* @description
* Abstract class that will be implemented in every custom service automatically built
* by the sdk builder.
* It provides the core functionallity for every API call, either by HTTP Calls or by
* WebSockets.
**/
@Injectable()
export abstract class BaseLoopBackApi {

  protected path: string;

  constructor(
    @Inject(Http) protected http: Http, 
    @Inject(LoopBackAuth) protected auth: LoopBackAuth, 
    @Inject(JSONSearchParams) protected searchParams: JSONSearchParams, 
    @Optional() @Inject(ErrorHandler) protected errorHandler: ErrorHandler
  ) {}

  /**
   * Process request
   * @param string  method      Request method (GET, POST, PUT)
   * @param string  url         Request url (my-host/my-url/:id)
   * @param any     routeParams Values of url parameters
   * @param any     urlParams   Parameters for building url (filter and other)
   * @param any     postBody    Request postBody
   * @param boolean isio        Request socket connection (When IO is enabled)
   */
  public request( // <<<<
    method      : string,
    url         : string,
    routeParams : any = {},
    urlParams   : any = {},
    postBody    : any = null  
  ) {`

**Comment by jonathan-casarrubias** [comment]
Hey @kattsushi  thanks for reaching out,

Just a question, what version of the builder are you using?

**Comment by kattsushi** [comment]
@jonathan-casarrubias i'm just testing since 2.1.0-beta.9 to 2.1.0-beta.10

**Comment by jonathan-casarrubias** [comment]
Hey @kattsushi thanks for the response, I though this was already fixed but you are right, these are kind of mixed I just verified the code.

I added the 2 dependencies, I will be publishing this fix ASAP.

Cheers
Jon

**Comment by jonathan-casarrubias** [comment]
Fixed
