### ISSUE TITLE
Custom properties generated by operation hook

### ISSUE THREAD

**Issue by bostondv** [mean-expert-official/loopback-sdk-builder#156]
Hi there,

I have a Document model that has related ratings. In the Document model I have a an operation hook which tally's the average and total ratings into `averageRating` and `totalRatings` values in the API response to the client.

Because these are not properties defined in the model json, the SDK builder has no way of knowing about these values and thus typescript linting throws warnings because they aren't defined the client side class.

To workaround this, I extended the Document class to include those properties. Is this the recommend way to do this or is there a better way?

**Loopback Operation Hook**

```js
module.exports = function(Document) {
  // Calculate and include average and total ratings
  Document.observe('loaded', (ctx, next) => {
    if (ctx.instance) {
      let sum = 0;

      Document.app.models.Rating.find({
        where: {
          documentId: ctx.instance.id,
        },
        fields: {
          rating: true,
        },
      }, (err, ratings) => {
        if (err) return next(err);

        if (ratings.length) {
          ratings.forEach((item) => {
            sum += item.rating;
          });

          ctx.instance.averageRating = sum / ratings.length;
        } else {
          ctx.instance.averageRating = 0;
        }

        ctx.instance.totalRatings = ratings.length;

        return next();
      });
    } else {
      return next();
    }
  });
};
```

**Extended Document Class**

```js
import { Document } from '../../sdk';

export class DocumentExtended extends Document {

  public averageRating: number;
  public totalRatings: number;

  constructor(json?: Document) { super(json); }
}
```

Thanks!

**Comment by jonathan-casarrubias** [comment]
Hi @bostondv, thanks for reaching out.

Hey so, yes that is the right approach because these properties are dynamic and does not really belongs to the original Document model.

Extending the models is completely fine and it is the reason of why I provided a way to extend Models, because of this type of use cases that needs to be addressed.

Cheers
Jon

**Comment by bostondv** [comment]
Awesome, thanks for the clarification!
