### ISSUE TITLE
How to handle relations

### ISSUE THREAD

**Issue by tfiwm** [mean-expert-official/loopback-sdk-builder#170]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [x] Question

#### What version of this module are you using?
- [x] 2.0.10 (Stable)
- [ ] 2.1.0-beta.14
- [ ] Other

Write other if any:

#### Please add a description for your issue:
Hello,

how can i use relations in the typescript code? Can you give me an example e.g. with "Belongs To"?

Best regard

**Comment by dmastag** [comment]
Hi @tfiwm 
You should be able to use the normal loopback relationship filter using include.
Just put it inside the function call.

Julian

**Comment by tfiwm** [comment]
Hi @dmastag 

thx for the quick anwser :)
can you give me a link with an example. This would be great!
Thank you very much!

**Comment by itamar-Cohen** [comment]
Hi,

you can go to the  wiki page
https://github.com/mean-expert-official/loopback-sdk-builder/wiki/5.-Usage-Examples

and check the getRoom in the real time app

`
getRoom(id: any): void {
      this.roomApi.findById(id, {
        **include**: [
          {
            relation: 'messages',
            scope: { order: 'id DESC' }
          }
        ]
      }).subscribe((room: Room) => {
        this.room = room;
        this.roomApi.onCreateMessages(this.room.id)
                    .subscribe((message: Message) => this.room.messages.push(message))
      });
  }
 `

**Comment by tfiwm** [comment]
thx a lot!

**Comment by jonathan-casarrubias** [comment]
Hey Guys, Thanks for reaching and jumping in to the question.

I'm glad this is starting to feel like wider community.

Cheers!!!
Jon
