### ISSUE TITLE
Login - logout - login - 403 status code

### ISSUE THREAD

**Issue by AlexanderVolk** [mean-expert-official/loopback-sdk-builder#179]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [x] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [x] 2.1.0-beta.14
- [ ] Other

Write other if any:

#### Please add a description for your issue:

Using user api login method I can successfully login into app and without any worries can use other api methods in which atomatically will be added secret token to request. As I can see user token data stores into AuthService as variable. 
And if user made logout and again login - this variable becomes invalid and all requests via return back with 403 status code. As I understtand, logout method clear token data, and login invokes "setUser(token)" only for one AuthService, not to all services that was created in components (in constructors of ApiService).

Is there any special mechanism to avoid this?

**Comment by jonathan-casarrubias** [comment]
Hey @AlexanderVolk, thanks for reaching out..

When you login, the authService is the one that stores in memory the credentials, this service is shared throughout all of the other services, this is using singleton pattern..

So, basically just need to be define once and works for all.

In this starter I implemented authentication example

https://github.com/mean-expert-official/sdk-builder-starter

Please take a look at it and see if helps you with the implementation. There are a good amount of applications currently working with the Builder so I feel kind of confident it works. -but I can always be wrong-

So, just make sure you are redirecting users within the subscribe methods for either login or logount and should works

I hope this helps you with your issue.

Cheers
jon

**Comment by jonathan-casarrubias** [comment]
@AlexanderVolk were you able to progress on this?

**Comment by AlexanderVolk** [comment]
Hi!

sorry for too late reply.

Yeah, your example is good and gave me some idea to find the reason. Actually my application divided into several modules. And in some modules I forgot remove SDK from import. And these modules loaded AuthService into it's own  context and that's why AuthService had different AccessToken on different pages.

Thanks!
