### ISSUE TITLE
Custom LB Remote Method generates Invalid Method.

### ISSUE THREAD

**Issue by Destreyf** [mean-expert-official/loopback-sdk-builder#185]
#### What type of issue are you creating?
- [X] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [X] 2.1.0-beta.15
- [ ] Other

#### Please add a description for your issue:
1. When defining a custom remote method it creates the method as an Array of whatever model rather than a single instance.
2. The custom parameter in my function isn't getting set (this one i'm not surprised by)

```js
  Course.remoteMethod(
    'findBySlugDetailed',
    {
      accessType: 'READ',
      description: "Query a course by its url slug, with all of its data (course, sections and lessons).",
      http: {path: "/slug/:slug/detailed", verb: "get"},
      accepts: [
        {arg: 'slug', type: 'string', required: true},
        {arg: 'filter', type: 'any', required: false}
      ],
      returns: {arg: 'data', type: 'Course', root: true}
    }
  );
```

And this generates a method in the CourseApi file that looks like this

```typescript
  public findBySlugDetailed(slug: any, filter: any = undefined): Observable<Array<Course>> {
    let method: string = "GET";
    let url: string = LoopBackConfig.getPath() + "/" + LoopBackConfig.getApiVersion() +
    "/courses/slug/:slug/detailed";
    let routeParams: any = {};
    let postBody: any = {};
    let urlParams: any = {};
    if (slug) urlParams.slug = slug;
    if (filter) urlParams.filter = filter;
    let result = this.request(method, url, routeParams, urlParams, postBody);
    return result.map((instances: Array<Course>) =>
        instances.map((instance: Course) => new Course(instance))
    );
  }
```
1. It returns an `Observable<Array<Course>>` when it should be `Observable<Course>`
2. The url has a :slug in it with a custom /detailed after for some manual methods i'm doing to grab additional data in a specific format.

----

Aside from these two issues, I've been loving the loopback-sdk-builder, and i would love to contribute once i have additional free time.

**Comment by jonathan-casarrubias** [comment]
Hi @Destreyf thanks for reaching out.

Hey so, in regards of the type of result; this is the function that decides the type:

````js
  /**
   * @method buildObservableType
   * @description
   * Define observable type
   */
  function buildObservableType(modelName, methodName) {
    let type = 'any';
    if (methodName.match(/(^createMany$|^find)/g)) type = `Array<${modelName}>`;
    if (methodName.match(/(^create$|upsert|^findById$|^findOne$)/g)) type = modelName;
    return type;
  }
````

The pattern in LoopBack is that any find method would return an array unless is a findOne or findById. I believe we may check also for the configurations return type, though I usually see standard loopback types: https://docs.strongloop.com/display/public/LB/LoopBack+types It can be a helper on deciding what type set in typescript.

I will take a look asap.

Cheers
Jon

**Comment by Destreyf** [comment]
Just to give a more complete reproducible snippet.

```js
  Course.findBySlugDetailed = function (slug, filter, cb) {
    filter = filter || {where: {}};
    filter.where.slug = slug;
    filter.include = detailedFilter.include;

    Course.findOne(filter, function (err, course) {
      if (err) {
        cb(err);
      } else {
        if (course !== null && typeof(course) !== 'undefined' && (typeof(course.length) !== 'undefined' && course.length !== 0)) {
          Course.process_full_course(course, cb);
        } else {
          var error = new Error();
          error.status = 404;
          error.message = 'Course not found.';
          error.code = 'NOT_FOUND';
          cb(error);
        }
      }
    });
  };
```

I use findOne in my code, but the actual name of the method is findBySlugDetailed (i have have findBySlug and findByIdDetailed that are affected) i see your regex looks based on method name.

Maybe we could have a key in the model.json to force the type and then we don't have to worry about figuring out the type when dealing with custom methods?

I'll see if i can figure something out and if i can i'll submit a PR.
