### ISSUE TITLE
sdk in the fireloop enviroment

### ISSUE THREAD

**Issue by kattsushi** [mean-expert-official/loopback-sdk-builder#187]
#### What type of issue are you creating?
- [ x] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ x] 2.0.10 (Stable)
- [ x] 2.1.0-beta.14
- [ ] Other

Write other if any:

#### Please add a description for your issue:
i try to generate the SDK with a  fireloop enviroment and typescript in the backend side and the remotes custom methods are not been generate in the final SDK

**Comment by jonathan-casarrubias** [comment]
Hi @kattsushi thanks for reaching out..

Hey so, would you mind to describe the steps to reproduce this issue?

**Comment by kattsushi** [comment]
Sure @jonathan-casarrubias I'm don't see nothing rare 
`'use strict';
var loopback = require('loopback');
var boot = require('loopback-boot');
var app = module.exports = loopback();
  var bodyParser = require('body-parser');
  var path = require('path');

  // configure view handler
  app.set('view engine', 'ejs');
  app.set('views', path.join(__dirname, 'views'));

  // configure body parser
  app.use(bodyParser.urlencoded({extended: true}));

  //app.use(loopback.token());
  app.use(loopback.token({ model: app.models.accessToken }));

app.start = function() {
  // start the web server
  var server = app.listen(function() {
    app.emit('started', server);
    var baseUrl = app.get('url').replace(/\/$/, '');
    console.log('Web server listening at: %s', baseUrl);
    if (app.get('loopback-component-explorer')) {
      var explorerPath = app.get('loopback-component-explorer').mountPath;
      console.log('Browse your REST API at %s%s', baseUrl, explorerPath);
    }
  });
  return server;
};

// Bootstrap the application, configure models, datasources and middleware.
// Sub-apps like REST API are mounted via boot scripts.
boot(app, __dirname, function(err) {
  if (err) {throw err;}
  if (require.main === module){
    //app.start();
    //Socketio
    app.io = require('socket.io')(app.start());
    require('socketio-auth')(app.io, {
      authenticate: function (socket, value, callback) {
        console.log(value);
      var AccessToken = app.models.AccessToken;
      //get credentials sent by the client
      var token = AccessToken.find({
        where:{
                and: [{ userId: value.userId }, { id: value.id }]
        }
      },
      function(err, tokenDetail){
        if (err) {throw err;}
        console.log(tokenDetail);
        //socket.emit('objectToken',tokenDetail);
        if(tokenDetail.length){
          callback(null, true);
        }else {
          callback(null, false);
        }
      }); //find function..
      } //authenticate function..
    })
    app.io.on('connection', function(socket){
      console.log('a user connected');
      socket.on('ouputQRCode',function(userJson){
        console.log('ouputQRCode');
        var Qrcode = app.models.PGQ_QRCode;
        Qrcode.reqQrCode(userJson.userId,function(err,result){
          console.log('Id User: '+userJson.userId);
          if (err){
            socket.emit('QR',err);
          }else{
            console.log(result)
            socket.emit('QR',result);
          }
        });
      });
    });
  }
});`

**Comment by jonathan-casarrubias** [comment]
Yes that is what I assumed, since the FireLoop cli is in alpha, many changes are being made. If you want to manage a project in this stage you may need to create a new project on each version and migrate until is RC.

Look, this is how the server now looks, I believe you are only missing 1 line: https://github.com/mean-expert-official/fireloop-todo-example/blob/master/server/server.js#L2

Also, are you using the @mean-expert/loopback-component-realtime?

**Comment by kattsushi** [comment]
No,  no use cli I'm testing doing with you advice thanks,  cheers

**Comment by kattsushi** [comment]
I have conflicts on one of the models when I place require('ts-node/register');
And I'm using require for no like that
```
import {
     model
} From '@ mean-expert / model';
Import * as path from 'path';

Const app = require ( '../../ server / server');
// const path = require ( 'path');
Const config = require ( '../../ server / config.json');
```
I guess with the register already this will not be so true? As it would be in an example

@jonathan-casarrubias  cheers!

**Comment by jonathan-casarrubias** [comment]
@kattsushi I recommend you not to require app or config, you can have access from the model.

Within the constructor you are receiving the app instance and then any config you want from the config.json file, you can get it from the app itself

````js
import { Model } From '@mean-expert/model';

class MyModel {
   constructor(app: any) {
      console.log(app.get('port')); // port or any property within the config.json
   }
}

````

**Comment by kattsushi** [comment]
@jonathan-casarrubias  But if there are other dependencies such as mongodb, or crypto for example I use them a lot, as the compatibility with ts-node/register? Or do I have to have anyway diffninicion of types typings for each?

**Comment by jonathan-casarrubias** [comment]
@kattsushi now consuming dependencies will be the same way as in angular 2, basically as any typescript app

Here is the docs for that: https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html#consuming-dependencies

Though I use `let library = require('library')` and I know this is valid also, but you may get type issues, so please check the typescript docs to know how to manage types from external libraries.

I know this can be confusing at the beginning -still is for me- but at the end you will have a consistent development across Back and Front End, so once you get it... It will work for both

Cheers
Jon

**Comment by kattsushi** [comment]
@jonathan-casarrubias urra , thanks very much following

**Comment by jonathan-casarrubias** [comment]
Awesome, I'll close this issue then. 

btw. by the moment I release the complete documentation,  you will be a fireloop expert 🎉 

Cheers!
Jon
