### ISSUE TITLE
Reservated words Warning

### ISSUE THREAD

**Issue by davidpestana** [mean-expert-official/loopback-sdk-builder#189]
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [x] 2.1.0-beta.14
- [ ] Other

Write other if any:

#### Please add a description for your issue:

**Comment by davidpestana** [comment]
If you have a remote method variable named "method" for example when sdk was generated you can find this problem:

***Duplicate Identifier 'method'.***

> public paymentStart(id: any, method: any = {}): Observable<any> {
    let method: string = "POST";
    let url: string = LoopBackConfig.getPath() + "/" + LoopBackConfig.getApiVersion() +
    "/YourModel/:id/paymentStart";
    let routeParams: any = {
      id: id
    };
    let postBody: any = {};
    let urlParams: any = {};
    if (method) urlParams.method = method;
    let result = this.request(method, url, routeParams, urlParams, postBody);
    return result;
  }

**Comment by jonathan-casarrubias** [comment]
Hi @davidpestana thanks for reaching me out..

Hey so, I see the issue and I think it is legit... I will add an underscore prefix for the methods so they don't collision like this.

I will try to send the fix ASAP.

Thanks for reporting.

Cheers
Jon

**Comment by jonathan-casarrubias** [comment]
Fixed.

Enjoy!
Jon
