### ISSUE TITLE
Builder does not ignore argument with a source property in a custom remote method

### ISSUE THREAD

**Issue by bostondv** [mean-expert-official/loopback-sdk-builder#190]
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [x] 2.0.10 (Stable)
- [x] 2.1.0-beta.16
- [ ] Other

Write other if any:

#### Please add a description for your issue:

I have a custom remote method on my Document model which accepts two arguments, `context` and `filter`. The `context` argument is populated automatically by an http source of the request and thus is not an argument that should be passed to the Loopback API. For example, Loopback Explorer ignores the `context` argument and only displays the `filter` argument.

![screen shot 2016-11-08 at 10 51 55 am](https://cloud.githubusercontent.com/assets/133814/20105899/6766cd3a-a5a1-11e6-933c-665eb8115dbe.png)

The SDK builder however, includes the `context` argument in the generated SDK code:

```
public search(context: any = {}, filter: LoopBackFilter = {}): Observable<any> {
    let method: string = "GET";
    let url: string = LoopBackConfig.getPath() + "/" + LoopBackConfig.getApiVersion() +
    "/documents/search";
    let routeParams: any = {};
    let postBody: any = {};
    let urlParams: any = {};
    if (context) urlParams.context = context;
    if (filter) urlParams.filter = filter;
    let result = this.request(method, url, routeParams, urlParams, postBody);
    return result;
  }
```

Loopback Document.json:

```
"methods": {
    "search": {
      "isStatic": true,
      "accepts": [
        {
          "arg": "context",
          "type": "object",
          "http": {
            "source": "context"
          }
        },
        {
          "arg": "filter",
          "type": "object",
          "description": "Filter defining query, fields, where, include, order, offset, and limit"
        }
      ],
      "returns": {
        "type": ["Document"],
        "root": true
      },
      "description": "Performs a full text search.",
      "http": {
        "path": "/search",
        "verb": "get"
      }
    }
  }
```

Because the `context` arg has an http source, I believe the SDK should ignore `context` and generate the SDK method with just the `filter` argument:

```
public search(filter: LoopBackFilter = {}): Observable<any>
```

As a workaround right now I can call the method like `Document.search(null, filter);` but I don't think it's ideal.

There are specific source values remote methods can accept which should probably be filtered out: http://loopback.io/doc/en/lb2/Remote-methods.html#http-mapping-of-input-arguments 

Thanks!

**Comment by jonathan-casarrubias** [comment]
Hi @bostondv thanks for reaching out.

So, you are right actually we will need to avoid req, res and context since in the builder we are only managing, body, path and query.

I will try to add a fix ASAP for this issue.

Thanks for reporting

**Comment by jonathan-casarrubias** [comment]
Fixed.

Enjoy!
Jon

**Comment by bostondv** [comment]
Works great, thanks!
