### ISSUE TITLE
Not supported if hasmany through relation to same table

### ISSUE THREAD

**Issue by dmastag** [mean-expert-official/loopback-sdk-builder#195]
#### What type of issue are you creating?
- [X] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [X] 2.1.0-beta.16
- [ ] Other

Write other if any:
Loopback 2.36.0
#### Please add a description for your issue:

I have a hasmany through relationship from table Employee to Employee with the Intention to store the Team members and Supervisors.

Getting the following error:

```
ERROR in [default] ...\sdk\models\Employee.ts:4:2
Individual declarations in merged declaration 'Employee' must be all exported or all local.

ERROR in [default] ...\sdk\models\Employee.ts:4:2
Import declaration conflicts with local declaration of 'Employee'

ERROR in [default] ...\sdk\models\Employee.ts:35:13
Individual declarations in merged declaration 'Employee' must be all exported or all local.
```

Turns out that there a declarations to models/Employee.ts  is trying to import Employee from the index
And in custom/Employee.ts has the Employee Model imported twice.

**Comment by jonathan-casarrubias** [comment]
@dmastag I will take a look on it, I believe this was fixed a long time ago, but there has been some pull requests that have created minor dis-adjustments, this may be one of it.

I will add this issue to the current milestone, so I hope this will be published during the next couple of days.

Thanks for reporting!!

Cheers
Jon

**Comment by dmastag** [comment]
I think this was my fault by creating a wrong relation, it wasn't even working in loopback itself.
Marking to closed

**Comment by jonathan-casarrubias** [comment]
cool... Im glad you make it work.

Cheers!
