### ISSUE TITLE
using mixins count is not supported

### ISSUE THREAD

**Issue by dmastag** [mean-expert-official/loopback-sdk-builder#197]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [X] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [X] 2.1.0-beta.16
- [ ] Other

Write other if any:
"loopback": "^2.36.0",
"loopback-counts-mixin": "^1.0.1",

#### Please add a description for your issue:
I am trying out the [loopback-counts-mixin](https://github.com/exromany/loopback-counts-mixin) to get the total of my Items but count is not part of the LoopBackFilter so I can't use it.

```
constructor(
    private companyApi: CompanyApi,
    private communicationService: CommunicationService
  ) { 
    this.companies = this.companyApi.find({
      counts:"employees"
    }) 
}
```

Error:
`Argument of type '{ counts: string; }' is not assignable to parameter of type 'LoopBackFilter'.
  Object literal may only specify known properties, and 'counts' does not exist in type 'LoopBackFilter'.`

Temprary Workaround:
Update LoopBackFilter in models/BaseModels.ts to

```
export interface LoopBackFilter {
  fields?: any;
  include?: any;
  limit?: any;
  order?: any;
  skip?: any;
  offset?: any;
  where?: any;
  count?: any;
}
```

**Comment by jonathan-casarrubias** [comment]
Hi @dmastag thanks for reaching out.

Hey so, since the count is not part of the LoopBack Filter is obvious is generating this issue, I'm trying to think in a solution, but I just don't want to add the count property to the interface, since all the people not having that mixing may get confused by having available the count option.


Lets think in a solution that can be automatically mapped when the mixing is available

**Comment by jonathan-casarrubias** [comment]
I believe I have come up with an idea of implementing this.

I'll try to implement it when I get the chance.

Cheers
Jon

**Comment by dmastag** [comment]
Awesome, was thinking about other mixins also like your [stats-mixin](https://github.com/mean-expert-official/loopback-stats-mixin) haven't tried it out with this though.

**Comment by Cyperwu** [comment]
is there any progress on this issue?
I found out that such mixins does not support header params, which is the default way for our sdk. Is it possible to change it manually in cli?

**Comment by jonathan-casarrubias** [comment]
@Cyperwu there is no way to manually changing that, you would need to commend a couple of lines within the base api file.

of course that would be removed on each re-generation, we might add an option to either use headers or query string, but is not part of this version plans

**Comment by Cyperwu** [comment]
@jonathan-casarrubias great! looking forward to this feature.

**Comment by jonathan-casarrubias** [comment]
Need to clean the repo to open space for LB4 related issues.
