### ISSUE TITLE
Community Questions

### ISSUE THREAD

**Issue by jonathan-casarrubias** [mean-expert-official/loopback-sdk-builder#198]
Use this thread for community questions.

**Comment by AurelieV** [comment]
Hey. I want to use cookie for authentication. What is currently the best approach to do it? What I have done now is to not use User methods for handle authentication, but mannually send the requests (login and logout). Everything seems to work fine, but I am not sure this is the correct approach.

**Comment by jonathan-casarrubias** [comment]
Hey @AurelieV, I have not implemented any cookie authentication so I would not be able to say what is the right approach.

I actually will explore that because of the angular universal integration, but It still is on the back log.

I believe if that works for you now is fine, and lets see how the cookie integration evolves.

Cheers
Jon

**Comment by jonathan-casarrubias** [comment]
Ok I'm implementing DI Swapping for a cookie service that needs to work in angular universal.

I believe I will be adding the cookie implementation within the SDK, but it still is work in progress it will be delivered aside the angular universal integration

**Comment by sprypradeep** [comment]
The localStorage option has been swapped by cookie storage for the auth.api , shouldnt there be a choice to use either of them (I loved locaStorage, because we prepopulated data on first call for dropdown options).

**Comment by jonathan-casarrubias** [comment]
Hi @sprypradeep I'm glad to see you back.

Hey so, I'm not understanding the problem, you still can populate data on first call when using cookies, of course you need to add the rememberMe as second parameter into the login method.

Anyway, the cookies are needed for angular universal to work....

If you find a good reason and elaborate of why cookies does not provide you the same functionality, I may decide to change the SDKBrowserModule to localStorage ONLY when there Angular Universal was not selected.

If Angular Universal is a requirement, then there is nothing I can do to add localStorage instead of Cookies.

**Comment by sprypradeep** [comment]
@jonathan-casarrubias thank you for such a prompt response. It (cookies) worked just fine, until I found that some of my pre-loading data was going above 4kb size limit, thats when I missed localStorage.

**Comment by sprypradeep** [comment]
Plus some of the data may never be required to be sent back to server.

**Comment by jonathan-casarrubias** [comment]
@sprypradeep I see your point, I think then cookies is right for the purpose of storing credentials, which is the original idea.

But, I see your point and I think it needs to be addressed in a different way, maybe a way to allow you persist in localStorage whatever you want. Though I still think cookies will remain for the original purpose.

Does it works for you to provide you with an API to manage localStorage? so you can persist whatever you want, as you are saying `some of the data may never be required to be sent back to server`.

That sounds like great idea specially, will help for offline mode in mobile applications.

Is that something that would help you with your use case?

**Comment by sprypradeep** [comment]
Yes, that's what would fulfill both the cases of auth data and other
extended data.

**Comment by jonathan-casarrubias** [comment]
Since, this is getting a common requested feature, I will be adding a new issue to address persisting custom data within local storage

**Comment by jonathan-casarrubias** [comment]
Ok guys..

You should be able to start using a storage service provided by RC6

````
import { SDKStorage } from '../shared/sdk/storage/storage.swaps';

@Component(...)
export class MyComponent {
  constructor(
    private storage: SDKStorage
  ) {
    this.storage.set('something', this.something);
    console.log(this.storage.get('something'));
  }
}
````

You should be able to start storing in local storage by using the example above. The same code will work regardless the environment (Web, Native) since it is also using DI Swapping but now for public local storage.

I hope this help you with your projects.

`PS. CookieBrowsers must remain for Angular Universal to work`

Cheers
Jon

**Comment by JonnyBGod** [comment]
@jonathan-casarrubias I think there should be an easy way to select what storage you want to use with Auth service.

Probably when importing the module you should have the option to pass the storage provider and default to Cookies.

**Comment by JonnyBGod** [comment]
I will PR it in coming days

**Comment by jonathan-casarrubias** [comment]
@JonnyBGod that sounds good, a PR will be appreciated... Just consider that if angular universal is selected, you must use Cookies. So if a user selects that driver you should not allow to change that configuration, for the rest of applications you can actually enable the feature you are proposing and should work.

Cheers!
Jon

**Comment by JonnyBGod** [comment]
@jonathan-casarrubias PR here https://github.com/mean-expert-official/loopback-sdk-builder/pull/327

I am just enabling the feature for ng2web and it defaults to current behaviour (using CookieStorage.

**Comment by JonnyBGod** [comment]
I will start a new branch soon for ngrx experimental implementation if you still agree in including this functionality.

Probably will start small by providing an alternative to ```AuthService``` with ngrx implementation.

**Comment by kattsushi** [comment]
Hello @JonnyBGod ! , Just these days I had a use case where what you propose makes a lot of sense! For example when I have several subscribers from various parts of the application I need to share the request in them, ngrx this library case to solve it with the Shared () method; They are strung in the style of the request

```js
return this.http.request(request)
      .shared()
      .map((res: any) => (res.text() != "" ? res.json() : {}))
      .catch((e) => this.errorHandler.handleError(e));
```
what do you think ? 
Ideas like this that we can contribute and the a sdk more intelligent, what is the best way to establish this? I think it is already being very extensive options flags of the sdk cli, but if I think that an optional file should be given where we can configure certain functionalities of ngrx.

Cheers!

**Comment by JonnyBGod** [comment]
@kattsushi Not sure if I got your point. But I was planning to keep all models and related services as is and generate templates for actions, reducers and effects.

In ```effects``` I would make use of current model services such as ```UserApi.login()```.

I think this keeps it simple but open to ideas.

I will soon create a new branch and open an issue for ngrx specific discussion. I expect this to take some time to be fully functional and included in main distribution, meaning that we can tryout a bit with different ideas for implementation.

**Comment by beeman** [comment]
@JonnyBGod I'll be happy to test anything you have related to this 👍

**Comment by kattsushi** [comment]
@JonnyBGod  @beeman  me too (y)

**Comment by JonnyBGod** [comment]
@jonathan-casarrubias I would like to know your thought about implementing an option to generate sdk from swagger specs.

My general idea would be to make use of [generator-loopback](https://github.com/strongloop/generator-loopback/blob/master/swagger/index.js) to parse swagger and feed the models to SDK-builder.

I see two option here:
1. integrate it into this project
2. make some changes to sdk-builder to be able to use parts of it in other project. This would mean create a new project that would use sdk-builder generator passing it the models and not the app.

This features would be great because in the end we could end up with same sdk logic for loopback aps and any other swagger api.

**Comment by JonnyBGod** [comment]
I would be happy to create ```swagger-idk-builder``` within ```mean-expert-official```

**Comment by JonnyBGod** [comment]
@kattsushi @beeman I am experimenting with some different approaches. Hoping to have you testing it next week.

**Comment by jonathan-casarrubias** [comment]
@JonnyBGod I like the idea of building the SDK from swagger specs, this approach may lead to actually generate SDKS from other backends and not only from loopback.

I thin that for that it should be plain services, like what this project originally was and I'm actually intending to have a fireloop-sdk-builder so we have separated the concerns.

Let me arrive into my house and I will add you as member

Cheers
Jon

**Comment by jonathan-casarrubias** [comment]
Hey @JonnyBGod I added you to the community as contributor and I also created a repo for the swagger sdk builder.

It would be super cool if this builder can work with any swagger client so this new SKD Builder can work with different backends.

git@github.com:mean-expert-official/swagger-sdk-builder.git

**Comment by kps-dev** [comment]
@JonnyBGod If you're still engaged on the swagger-sdk-builder and need some help or need someone to test please let me know, I have an immediate use-case for it. 

FNG-disclaimer: I'm a network security consultant, not a professional dev by any means, that has been digging into ng2 for a project and fireloop is pure ninja for what I'm trying to do. Very familiar w/ swagger, intermediate w/ fireloop at current, perhaps there's something I can do which fits within my capabilities?

**Comment by JonnyBGod** [comment]
@kps-dev I will defiantly follow through with this has I also have the need for it. I am very busy atm though and had to postpone for a few weeks.

If your up for it I can explain my general plan to tackle it and you can start.

**Comment by kps-dev** [comment]
@JonnyBGod - Thanks for the quick response. I'm up for it, if you can explain your general plan I'll get started on what I can.

**Comment by juliancuni** [comment]
@jonathan-casarrubias is there any bug with logout on Angular2 sdk? logout() function clear the localstorage on client side but dont delete token on API side. I am using MogoDb

**Comment by thiagovito** [comment]
Hi @jonathan-casarrubias,
I have a question, I hope you or someone could give me some thoughts about it. 

Is there any way to check the authenticity of a Token? for example. I am using userApi.isAuthenticated on my Guards to verify if user is authenticated. However, in some cases the Token has expired. I was wondering if there is a way to verify if token is valid to proceed the request.

**Comment by jonathan-casarrubias** [comment]
@thiagovito you might want to use the userApi.getCurrent() that will call the API to return the current logged user, if the user is not authenticated it will return a no authorized error, you could catch that and redirect user to login.

I hope this helps you clarify your question

**Comment by thiagovito** [comment]
@jonathan-casarrubias ,
I think I have tried it before. maybe i am doing something wrong. Because when I try using getCurrent() I get the following error on my Api: 
GET /api/users/26?filter=undefined: Error: Value is not an object.

I think it complains that filter is undefined.

**Comment by jonathan-casarrubias** [comment]
@thiagovito that is a known issue that will be fixed in the next SDK version, I have already fixed that in my local I need to verify a couple of other issues and then I will publish a fix for that.

For now you might want to add an empty object as filter while the new SDK is released

**Comment by thiagovito** [comment]
Awesome! I managed to fix by adding the following lines on my extended Model. 
![image](https://user-images.githubusercontent.com/904073/27090265-1eb5ed40-5033-11e7-99d9-ff9f3784c771.png)

**Comment by offwork** [comment]
I've been struggling all day, but I can not even create a project. I follow the steps on the wiki page, but it did not help much.

I gave up before it started, just a SDK that a little community understands and is almost without documentation.

I do not write this for a bad purpose. But what should I do to make progress? Shall I wait? I'm sorry but that's what i think.

**Comment by jonathan-casarrubias** [comment]
@offwork first of all I apologize for the hard time you had trying to setup the SDK.

Second, the SDK is really near to stable, but at this point it grew so much that for new devs like you it might be a little confusing, plus today I found there were some markdown issues on the Wiki that can misled you as well.

Anyway, I would first need to understand what you are trying to achieve, because you need to understand that the SDK works in several scenarios and that is the reason there are now so many configurations.

The SDK won't create or setup a project for you, but it will integrate LoopBack with Angular 2 by using different approaches like REST, PubSub and FireLoop API and working for Web, Mobile even IoT... Therefore I can help you if you help me understand what is your goal.

Regards
Jon

**Comment by thiagovito** [comment]
Hi @jonathan-casarrubias 
How are you doing? Quick question. in the latest release I noticed that my Remote methods were not passing the params correctly. So I noticed that there were couple of changes when Generating the classes using the SDK build. 
![image](https://user-images.githubusercontent.com/904073/27335803-1f8d98be-55a4-11e7-92e1-0eb596c0b417.png)

As you can see in the example above. The builder generated the method using _routeParams (which wasn't working). However I changed it by passing my param via _urlParams, that approach works fine. 

Could you please explain the difference here? 
Once again I appreciate your help in advance.

Regards, 
Thiago Vito

**Comment by jonathan-casarrubias** [comment]
@thiagovito  I'm doing great, thanks for asking..

Hey so, that is a configuration issue, for me it seems you are not defining what is the http source for that param, if you don't define one the SDK will just pass it over routeParams.

For you to configure your custom remote method, you can check the following remote method register example:


````js
    Model.remoteMethod('myCustomMethod', {
        accepts: [{
            arg: 'someParam',
            type: 'any',
            required: true,
            http: {
                source: 'body' // or query or route
            }
        }],
        http: {
            path: '/import',
            verb: 'post'
        },
        returns: {
            arg: 'result',
            root: true,
            type: 'any'
        }
    });
````

When you define the http source, the SDK will take that information and correctly setup the parameter.

Reference link: https://loopback.io/doc/en/lb3/Remote-methods.html#http-mapping-of-input-arguments

I hope this helps to clarify your question.

**Comment by thiagovito** [comment]
@jonathan-casarrubias, 
I think I found my mistake. I was using "id" as param. it seems that "id" defaults it to _routeParam. 
Either way thanks for your prompt response as usual

**Comment by thiagovito** [comment]
@jonathan-casarrubias 
Quick question. I am trying to set new password using setPassword method Via Reset email Link which gives me an Access Token.

How can I set access token to send a request to setPassword? 

Sorry this must be a really stupid question. :(

**Comment by Destreyf** [comment]
@thiagovito there's a `changePassword` method that you can use, that requires the old password and the new one.  Or you can call `patchAttributes` and pass a password in to set the password.

**Comment by thiagovito** [comment]
Thanks @Destreyf . Maybe I wasn't clear on my Question. 
Here is the scenario: 
User lost his pass. So I used the `POST /user/reset (Reset password for a user with email)` to send a new token via email. 
![image](https://user-images.githubusercontent.com/904073/27455537-029a1fa8-5774-11e7-8a9d-16d379a07903.png)

When user clicks on the link it directs to the app. so this Token can be used to set new password by using the following endpoint: `POST /user/reset-password`
![image](https://user-images.githubusercontent.com/904073/27455574-205f2736-5774-11e7-9fcf-9e3ecd30b1af.png)

So When I try to use the SDK, because I am not authenticated, I have no Token. My question is how can I use password-reset token to make this request.
![image](https://user-images.githubusercontent.com/904073/27455642-64ff5258-5774-11e7-984d-220de77980cd.png)

**Comment by Destreyf** [comment]
This gets a little tricky, i actually make my own calls for things like this.  Here's the snippet of code i use for our password reset logic

```typescript
export class ForgotComponent implements OnInit {
  public user;
  public loading = false;
  public sent = false;
  public changed = false;
  public token = false;
  public expired = false;
  ...
  ngOnInit() {
    this.token = _.get(this.route, 'snapshot.params.token', false);

    if (this.token) {
      this.loading = true;
      this.getUserByToken().subscribe(u => {
        this.user = u;
        this.getFullToken().subscribe(t => {
          this.auth.setToken(t);
          this.loading = false;
        });
      }, () => {
        // Token expired
        this.expired = true;
        this.loading = false;
      });
    }
  }

  changePassword() {
    const data = this.changePasswordFormGroup.value;

    if (this.changePasswordFormGroup.valid) {
      // Long Enough
      this.loading = true;

      this.userApi.patchAttributes(this.user.id, data).subscribe(r => {
        this.userService.login({email: this.user.email, password: data.password}).subscribe(l => {
          this.router.navigate(['/profile']);
        });
      });
    }
  }

  getUserByToken() {
    const url = [LoopBackConfig.getPath(), LoopBackConfig.getApiVersion(), 'users', ['me', ['access_token', this.token].join('=')].join('?')].join('/');

    return this.http.get(url).map(r => r.json());
  }

  getFullToken() {
    const url = [LoopBackConfig.getPath(), LoopBackConfig.getApiVersion(), 'users/me', ['accessTokens/' + this.token, ['access_token', this.token].join('=')].join('?')].join('/');

    return this.http.get(url).map(r => r.json());
  }
```

I use a manual request to get the full token, i also have my loopback server setup to do custom user literals by adding 

```js
  server.use(loopback.token({
    model: server.models.accessToken,
    currentUserLiteral: 'me',
  }));
```

to my `server/boot/authentication.js` file.

**Comment by Destreyf** [comment]
You could also possibly use the `customHeaders` property to set `{'Authorization': this.token}` however i haven't tested that as of yet.

**Comment by jonathan-casarrubias** [comment]
@thiagovito fast answer: You can not. 

setPassword is more related to the process of a user changing his/her own password.

Anyway, you can achieve this by 2 different  but similar approaches, both are server side.

Context: From the server you are actually able to change the password, therefore you need to some how do that from the server.

A) Not so advanced: When you send the email, you change the password and send it in the email body, later the user can change it when is logged in.

A) More Advanced: You create a UUID token that you send in your email, then you need to create a Custom Remote method, that will be called from the recover password section. Then in your custom remote method you receive the email, new password and UUID.  internally you change the password, Until this point this is a big security whole, because anyone could call that custom remote method. You need to secure it creating a Dynamic Role where you verify the UUID somehow is associated with that Account Email, then you assign an ACL rule for that custom method.

@Destreyf the problem with that is that he doesn't have a token available since the user is not able to login... 😞

**Comment by Destreyf** [comment]
@jonathan-casarrubias The token generated by the reset password function, is actually an access token that can be used to interact with the API, you can do this by either setting the `Authorization` header OR by passing the the token as `?access_token=X` I have used this method for several months now and have had no issues.

**Comment by thiagovito** [comment]
@jonathan-casarrubias I think @Destreyf is right 

> The token generated by the reset password function. 

If I use this accessToken in the lb Explorer it works fine. Im going to try using customHeaders and setting the Authorization.

**Comment by jonathan-casarrubias** [comment]
@Destreyf haven't you protected the resetPassword with an ACL rule? is open for anyone to call it?

**Comment by Destreyf** [comment]
@jonathan-casarrubias I am using the /users/reset api which takes a object containing an email field, you then have to listen to the resetPasswordRequest inside of the user model, which is where the actual creation & email happens.  Anyone can request a "password reset" but all its really doing it generating a token and sending an email to the account to then be handled in any way by your application, this way there's no security risk being exposed, and it allows a quicker entry point to handle the requests.

**Comment by jonathan-casarrubias** [comment]
@Destreyf yes that is exactly how it should be done by using the reset and not resetPassword from the Front-End, inside the reset password request event you handle the critical part of the flow, as you just stated, so we are all in the same page now.

Cheers
Jon

**Comment by thiagovito** [comment]
@jonathan-casarrubias Sorry but If /reset endpoint generates a Temp AccessToken, Why can't I use it on:

```
POST /api/usuarios/reset-password
Content-Type: application/json
Authorization: eYqsBM3gNQPfH34sK7G1eGCL0RUzTyTimCM4nQnJenEdhZpwcduXEJERiv5KKHFH0

Body
{"newPassword":"1234"}
```

Maybe I am mistaken here. But I believe it would be possible.

**Comment by thiagovito** [comment]
I followed this example:
https://github.com/strongloop/loopback-example-user-management/blob/master/common/models/user.js

**Comment by jonathan-casarrubias** [comment]
@thiagovito if you already got a token, try using the UserApi.updateAttributes or UserApi.patchAttributes with the authentication header and see if works

**Comment by mittinatten** [comment]
Hi,
Is this thread still meant to be used? (since it is closed)

I have problems with cookie storage. I use passport and have no problems logging in using the standard recipe, but when I reload the page I lose the login. No cookies are stored with the `$LoopBackSDK` prefix. If I set up the `SDKBrowserModule` with `StorageBrowser` the data is stored in local storage and preserved on reload. Not sure if this is a bug or just me missing something obvious. I use version 2.1.0 of the SDK builder and angular 4.4.3.

I tried printing `window.document.cookie` before and after line 51 in `cookie.browser.ts` (https://github.com/mean-expert-official/loopback-sdk-builder/blob/master/lib/angular2/shared/storage/cookie.browser.ts#L51) and it doesn't change after it is set (and it looks strange to me that it should be set this way, but I haven't worked directly with cookies before, so not sure what to expect).

**Comment by jonathan-casarrubias** [comment]
@mittinatten thanks for reaching out..

Hey so cookies browser does correctly work on browsers, but I heard there are some issues on progressive mobile apps, is this your case as well?...

There is another issue related to cookies but for Angular Universal.... or is this other your case?

If you are not doing mobile, nor angular universal then you might want to add a new issue for that..

Cheers
Jon

**Comment by mittinatten** [comment]
Thanks for quick reply @jonathan-casarrubias! I build using `ng2web`. I'll create an issue.

**Comment by sourvil** [comment]
> @jonathan-casarrubias Sorry but If /reset endpoint generates a Temp AccessToken, Why can't I use it on:
> 
> ```
> POST /api/usuarios/reset-password
> Content-Type: application/json
> Authorization: eYqsBM3gNQPfH34sK7G1eGCL0RUzTyTimCM4nQnJenEdhZpwcduXEJERiv5KKHFH0
> 
> Body
> {"newPassword":"1234"}
> ```
> 
> Maybe I am mistaken here. But I believe it would be possible.

Hey, did you find a solution for this?

**Comment by sourvil** [comment]
@thiagovito Did you find a solution for this?




Sorry but If /reset endpoint generates a Temp AccessToken, Why can't I use it on:

POST /api/usuarios/reset-password
Content-Type: application/json
Authorization: eYqsBM3gNQPfH34sK7G1eGCL0RUzTyTimCM4nQnJenEdhZpwcduXEJERiv5KKHFH0

Body
{"newPassword":"1234"}
Maybe I am mistaken here. But I believe it would be possible.

**Comment by thiagovito** [comment]
So, I believe the problem I had was that I couldn't understand how to use
the customHeaders properly.
At the end, instead of using the SDK I ended up making a http call passing
the Authorization header, which worked

something like this:
```
const url = `${environment.BASE_URL}/${
environment.API_VERSION
}/user/reset-password`;

const body = JSON.stringify({
newPassword
});

const headers: Headers = new Headers();
headers.append('Content-Type', 'application/json');
headers.append('Authorization', token.toString());

const request: Request = new Request(
new RequestOptions({
headers,
method: 'POST',
url,
body
})
);

this.http
.request(request)
.toPromise()
.then(result => {
resolve(result);
})
.catch(error => {
reject(error);
});
});
```
