### ISSUE TITLE
Discussion about sdk features

### ISSUE THREAD

**Issue by jonathan-casarrubias** [mean-expert-official/loopback-sdk-builder#200]

**Comment by jonathan-casarrubias** [comment]
From: https://github.com/mean-expert-official/loopback-sdk-builder/issues/36
>John0x commented 2 hours ago
> I took a look at your generated models/services generated by the sdk builder and I'd suggest to use a base class for most of the crud stuff. That would reduce the file size drastically and make it more maintainable.

Hey @John0x 

Actually my preference would be not to create any service at all and the FireLoop interface is a step for that, if you create a pure FireLoop project your sdk size will be way decreased, but I still need to add the flag to avoid the creation of services.

So for those that for any valid reason needs to stick to the REST Interface, there actually is within the core directory, a base service that is the ones that handles requests, that code is not repeated within every single service, it is abstracted already and what you see within the actual service methods are configurations for that base service to work.

Anyway since the services already extend the BaseLoopBackApi service, we are able to migrate the cruds to that class instead of having them within each of the services as you are proposing.

But I see a couple of problems:

First of all that the ServicesAPI would change;

Think about this since we would need to create generic types for those methods, I already did that with the FireLoopRef.

````js

  private todo: Todo = new Todo();

  constructor(private todoApi: TodoApi) {
    todoApi.create<Todo>(todo).subscribe((instance: Todo => console.log(instance)));
  }
````

That change would break all the applications using the SDK.

The second of the issues:

````js

  private todo: Todo = new Todo();

  constructor(private todoApi: TodoApi) {
    todoApi.create<Todo>(todo).subscribe((instance: Todo => console.log(type of instance)));
  }
// console.log: Todo
````

When we create or find something, the service should return an instance of that specific model, maybe by using the getModelName method we could dynamically create instances on the fly and then we would be able to migrate to the BaseApi.

Both issues I think can be resolved, and yes that would definitely reduce the services size at some level.

Thoughts?

**Comment by John0x** [comment]
@jonathan-casarrubias I'm not sure about the performance of the Fireloop interface, but I guess it's alot heavier on the server since it uses websockets. So there will probably be still a lot of cases where people might want to use the rest interfaces instead of the realtime one. Besides that, there will still be at least one rest service be used for the authentication, or am I wrong?

I see a lot of repeated code in for example the UserApi, which could be optimized using generics. I believe that file size should be a top priority for the sdk builder since it can stack up pretty fast once you have a really big loopback service with a lot of models.

How is the performance/load of the realtime services (which the fireloop interface uses, right?) compared to the REST interface?

Besides that there is still one big advantage of the REST interface. And that is, that you can easily cache it. Which is important in cases like angular universal since both the server and the client (once it's loaded) would ask for the same thing.

**Comment by John0x** [comment]
Btw. I'd suggest adding an optional caching mechanism for angular universal for basic GET methods.

**Comment by jonathan-casarrubias** [comment]
@John0x thanks for bringing the performance topic up to the table, actually it's a great topic for an article.

See, the performance of course is matter of a good design, right implementation and setup. Either the case, you can drastically improve performance by adding Memcache to LoopBack models.

For right design I mean that according the system requirements you may have pure realtime, pure state less or an hybrid, in which the right implementation of these can lead to perform the best.

I'm not saying I will drop services support but I do need to add the option for applications that does not require it, actually I have a customer that he strictly requires not to use any rest service for his application, so at the end is just matter of requirements.

And yes, unless we open a new socket channel only for authentication, I believe the best way to authenticate is to use single http request, not persisting connection. -I may be wrong-

About the size of the services you are right, and I already decided and added an issue for that (https://github.com/mean-expert-official/loopback-sdk-builder/issues/209) see... Not sure if you used the loopback-sdk-angular but when nikolay originally forked that repo, many vices were brought of course to this project, it originally was just a translation from plain javascript to classes, there were no typings at all and each of the service methods used to implement much more code than now, but is a progressive effort.

So, I'm totally up to progress and now that the sdk achieves the purpose, It is a good time to start polishing it, that is why I created the issue #209 to start addressing this situation.

Cheers,
Jon

**Comment by jonathan-casarrubias** [comment]
Hey @John0x I'm very excited with the progress on refactoring the crud methods, it is reducing a lot the loc's. This will be released with the next major release, really soon.

**Comment by jonathan-casarrubias** [comment]
Actually this is the entire list of refactored methods and migrated to base service

create
createMany
find
exists
findOne
findById
updateAttributes
updateAll
count
createChangeStream

**Comment by todrules** [comment]
I have just the opposite needs than most people, I guess. I was wondering if there's any way to ONLY get the custom services. I don't even need the auth, error, or logging. I've already created my own custom modules. If you're looking at taking that piece out, I may fork this project and provide a service-only version.

**Comment by jonathan-casarrubias** [comment]
@todrules I believe your use case is totally legit, but there would be so many things to be disconnected that may lead to a bunch of issues.

After all for me it sounds that what you are trying to achieve is already possible if you see the following instructions: https://github.com/strongloop/loopback-sdk-angular/issues/188#issuecomment-224365840

By following that, you will get services only and you will need to pass the token your self, I believe that is your use case.

**Comment by jmls** [comment]
I was looking at implementing some sort of caching mechanism , and came across this http://stackoverflow.com/questions/41554156/angular-2-cache-observable-http-result-data which, on the surface, seems that it could be easily built into each method ...

**Comment by jmls** [comment]
there is also this, which seems _very_ easy to implement .. 

http://www.syntaxsuccess.com/viewarticle/caching-with-rxjs-observables-in-angular-2.0
