### ISSUE TITLE
Custom remote method with filter + other arg fails

### ISSUE THREAD

**Issue by bostondv** [mean-expert-official/loopback-sdk-builder#201]
#### What type of issue are you creating?
- [x] Bug

#### What version of this module are you using?
- [x] 2.1.0-beta.14

#### Please add a description for your issue:

I have a custom remote method which accepts to arguments:

- property: string (required)
- filter: loopback filter (optional)

When calling the generated SDK method eg. `myMethod('propertyName', {include: 'model'})`, the property argument gets dropped from the request and causes the request to fail.

It seems as that if a `filter` argument exists it drops other arguments. Seems like a bug?

**Comment by jonathan-casarrubias** [comment]
Hi @bostondv thanks for reporting.

Hey so, looks like a bug... I will add a unit test for the case you just described and if fails I will set the bug label to this issue and then try to send the fix ASAP.

Cheers
Jon

**Comment by jonathan-casarrubias** [comment]
Hey @bostondv I'm verifying this issue, is one of the latest pending before I release the RC.1

I just would like to ask you to share your remoteMethod configuration, there are so many variables that can affect the result that trying them all could waste some time.

Please share only the configuration I don't care for the remote method logic

something like:

````js
  Room.remoteMethod(
    'propertyMethod',
    {
      accepts: [
        { arg: 'property', type: 'string', required: true, http: { source: 'body' }},
        { arg: 'filter', type: 'object', http: { source: 'query' }}
      ],
      returns: { arg: 'greeting', type: 'string' },
      http: { path: '/propertyMethods', verb: 'post' }
    }
  );
````

By sharing your configuration I will be able to add a new unit test for this specific case and make sure it does not break again.

**Comment by bostondv** [comment]
Hey @jonathan-casarrubias,

I've worked around the issue since reporting but here's the model definition I was using originally. Defined in Model JSON file:

```json
"getPropertyValues": {
      "isStatic": true,
      "accepts": [
        {
          "arg": "property",
          "type": "string",
          "required": true,
          "description": "Property name to lookup values for."
        },
        {
          "arg": "filter",
          "type": "object",
          "description": "Filter defining fields, where, include, order, offset, and limit"
        }
      ],
      "returns": {
        "type": [
          "String"
        ],
        "root": true
      },
      "description": "Gets list of all unique values used for a given property.",
      "http": {
        "path": "/propertyValues",
        "verb": "get"
      }
    }
```

**Comment by jonathan-casarrubias** [comment]
Hey @bostondv thanks I will try this configuration and see if I can replicate.

Cheers
Jon

**Comment by jonathan-casarrubias** [comment]
Fixed
