### ISSUE TITLE
Update Auth Service to use cookies in web environments

### ISSUE THREAD

**Issue by jonathan-casarrubias** [mean-expert-official/loopback-sdk-builder#205]
#### What type of issue are you creating?
- [X] Enhancement

#### What version of this module are you using?
- [X] 2.1.0-beta.17

Write other if any:

#### Please add a description for your issue:

Need to update auth service to use cookies and local storage according the environment.

**Comment by viki53** [comment]
Hi, 

Why use cookies in the browser, as they are sent to the server when localStorage isn't?

There that easily be a lot of data going back and forth with every request (un-necessary headers) and they can be easily intercepted by a simple man-in-the-middle attack.

Is there a way to force the use of localStorage?

**Comment by jonathan-casarrubias** [comment]
Hi @viki53 thanks for reaching out,

Hey so, cookies are required to allow the SDK to work within an Angular Universal environment.

If are not selecting the ng2universal driver then we may be able to change cookies to localStorage, but anytime ng2universal is seleceted, there is nothing we can do to remove the cookies

**Comment by viki53** [comment]
Okay, but this causes a lot of issues when I try to store bigger data than a simple ID.

How do I select an other driver?

**Comment by jonathan-casarrubias** [comment]
Yes that topic is being discussed in here: https://github.com/mean-expert-official/loopback-sdk-builder/issues/198#issuecomment-261042428

In the immediate you would need to replace the code from the CookeStorage to use localStorage API.
