### ISSUE TITLE
Migrate PersistedModel Services to Base API

### ISSUE THREAD

**Issue by jonathan-casarrubias** [mean-expert-official/loopback-sdk-builder#209]
#### What type of issue are you creating?
- [X] Enhancement

#### What version of this module are you using?
- [X] 2.1.0-beta.17

Write other if any:

#### Please add a description for your issue:

Lets reduce the size of the services by migrating the crud services to the base api

**Comment by jonathan-casarrubias** [comment]
create
createMany
exists
find
findOne
findById
updateAttributes
updateAll
count
createChangeStream

**Comment by davidpestana** [comment]
Hi

i am using now upsertWithWhere and this method was a fail because dont are using the post verb... are using the put verb and dont works fine, maybe will be fixed with this issue?

**Comment by mriyaz** [comment]
Hi Jonathan,
What do you think about exposing the replicate method through the BASE API?
