### ISSUE TITLE
Issue with config.local.js

### ISSUE THREAD

**Issue by PhilippeCorreges** [mean-expert-official/loopback-sdk-builder#219]
#### What type of issue are you creating?
- [X] Bug

#### What version of this module are you using?
- [X] 2.0.10 (Stable)

#### Please add a description for your issue:

Hello,
When you want to make api versioning you must use config.local.js as this : 

var p = require('../package.json');
var version = p.version.split('.').shift();
module.exports = {
  restApiRoot: '/api' + (version > 0 ? '/v' + version : ''),
  host: process.env.HOST || 'localhost',
  port: process.env.PORT || 3000
};

when you run generate the SDK with that file in server folder, the **lb-sdk crashes**.

**Comment by jonathan-casarrubias** [comment]
Hey @PhilippeCorreges, thanks for reporting I will verify the issue and send the fix aside the next release.

Since it is a major release it may take some days.

**Comment by PhilippeCorreges** [comment]
No probs @jonathan-casarrubias 
I encountered it fortunately :-)

**Comment by jonathan-casarrubias** [comment]
Hey @PhilippeCorreges were you able to find the issue? I'm unable to replicate this

**Comment by PhilippeCorreges** [comment]
@jonathan-casarrubias to be honnest I did not try to work around it. You may want to close this stream and will try once all my config will be ready.

Let me know.

**Comment by jonathan-casarrubias** [comment]
Just make sure you have a default config.json beside the config.local.js.

I got an error when transformed the config.json into the config.local.js, I was able to fix it by leaving the default config.json configurations and just adding the config.local.js with the code snippet you provided, after that it correctly worked.

I'm closing this unless we got the same issue with the right steps to replicate.

Cheers
Jon

**Comment by PhilippeCorreges** [comment]
Hello @jonathan-casarrubias 
I reopen this issue as I have more information : 
 My config.local.js is : 

var p = require('../package.json');
var version = p.version.split('.').shift();
module.exports = {
  restApiRoot: '/api' + (version > 0 ? '/v' + version : ''),
  host: process.env.HOST || 'localhost',
  port: process.env.PORT || 3000
};

On the root folder of my project, I have a package.json for the server with the following line : 
  "version": "2.0.0"

This gives an API url which is : **[ base url: /api/v2 , api version: 1.0.0 ]**

I generated the SDK with all those things above.

The URLs do not take /v2 into account.

I checked User.ts for instance and it is written : **let url: string = LoopBackConfig.getPath() + "/" + LoopBackConfig.getApiVersion() +
    "/Users/:id/accessTokens/:fk";**

It sounds like **LoopBackConfig.getPath()** + "/" does not resolve **http://localhost:3000/api/v2/Users**

Thanks for your help on this topic.
