### ISSUE TITLE
rememberMe missing from AccessToken class

### ISSUE THREAD

**Issue by bostondv** [mean-expert-official/loopback-sdk-builder#220]
#### What type of issue are you creating?
- [x] Bug

#### What version of this module are you using?
- [x] 2.1.0-beta.14

#### Please add a description for your issue:

Thanks again for this amazing builder!

I believe this is bug, but am not 100% sure. 

With one of my extended models I'm getting the `rememberMe` property from `auth.getToken()`, however because `rememberMe` property is not defined on the `AccessToken` class Typescript is throwing an error.

```
Property 'rememberMe' does not exist on type 'AccessToken'.
```

The `rememberMe` data is there and the app runs fine despite the error. If you were to define `rememberMe` in the class like so I think it would solve the problem? (at least it does for me)  

```
export class AccessToken implements AccessTokenInterface {
      id:string;
      ttl: number;
      created: any;
      userId: string;
      user: any;
-->   rememberMe: boolean;
      constructor(instance?: AccessToken) {
            Object.assign(this, instance);
      }
}
```

**Comment by jonathan-casarrubias** [comment]
Hey @bostondv thanks for reporting I just added the missing property, it will be published within the next release.

Cheers
Jon
