### ISSUE TITLE
Question : Classes that extends User

### ISSUE THREAD

**Issue by PhilippeCorreges** [mean-expert-official/loopback-sdk-builder#226]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [X] Question

#### What version of this module are you using?
- [X] 2.0.10 (Stable)
- [ ] 2.1.0-beta.14
- [ ] Other

Write other if any:

#### Please add a description for your issue:

Does someone know if it is possible with the sdk to implement login()/register() with other classes that extends User one ?

**Comment by jonathan-casarrubias** [comment]
Hi @PhilippeCorreges, thanks for reaching out. Hey so, yes any Model that extends from Users will inherit these methods and the SDK Builder will create these.

Cheers
Jon

**Comment by PhilippeCorreges** [comment]
Thanks @jonathan-casarrubias
