### ISSUE TITLE
Handling arguments description as array

### ISSUE THREAD

**Issue by viki53** [mean-expert-official/loopback-sdk-builder#228]
#### What type of issue are you creating?
- Bug

#### What version of this module are you using?
- 2.1.0-beta.15

#### Please add a description for your issue:

We added a description for an argument in a remote method that is an Array, so when I generate the SDK the template tries the following:
```
(arg.description || "").replace
```

Which doesn't work on an Array. So maybe a `join('\n')` could be useful…

Here's a more complete look at the error:

```bash
readline.js:953
            throw err;
            ^

TypeError: ejs:231
    229|   });
    230| }
 >> 231| -%>
    232| <% if (params.length != 0) {
    233|   params.forEach(function(arg) { -%>
    234|    *

(arg.description || "").replace is not a function
```

#### Quick fix

Here is what I used to fix those lines:

```javascript
(arg.description ? (arg.description.join ? arg.description.join('\n') : arg.description) : '').replace
```

`lib/angular2/shared/serices/custom/service.ejs:236` & `lib/angular2/shared/serices/custom/service.ejs:261` on my version

**Comment by jonathan-casarrubias** [comment]
Hey @viki53 thanks for reporting, I will add a similar validation I will just rather use Array.isArray() for the validation, but yeah... lets support array descriptions

Cheers
Jon

**Comment by viki53** [comment]
Yes, that's the clean version I thought about right after I submitted this fix. 😊 

Thanks!

**Comment by jonathan-casarrubias** [comment]
Cool, I did the fix I will be publishing within the next version which is the RC1 for 2.1

Cheers
Jon

**Comment by viki53** [comment]
Great!

Any idea when this version will be published?
