### ISSUE TITLE
webapp/src/app/shared/sdk/index has no exported member 'SDKBrowserModule'

### ISSUE THREAD

**Issue by Mik-** [mean-expert-official/loopback-sdk-builder#239]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [x] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [x] 2.1.0-rc.2 (2.1 Release Candidate 2)
- [ ] Other

#### Please add a description for your issue:

Hi there,

I created a simple loopback app following the tutorial. I added a single model and checked the api works.

Than, I installed the loopback-sdk-build, following the descriptions in the wiki. The SDK creation is done by this command:
`./node_modules/.bin/lb-sdk server/server.js webapp/src/app/shared/sdk -d ng4web`

When I try to setup my app.module by adding SDKBrowserModule (or any of the other options) i've got then compile message: `webapp/src/app/shared/sdk/index"' has no exported member 'SDKBrowserModule'.`

I tried fireloop the other day, which yielded to the same error.

Where did I forgot something?

**Comment by jonathan-casarrubias** [comment]
Hi @Mik- thanks for reaching me out.

I'm sorry for this unfortunate moment, but we are in a transition from version 2 to 2.1 and some breaking changes have been implemented, in which not all of them are up to date within the documentation.

please try the following:

````sh
./node_modules/.bin/lb-sdk server/server.js webapp/src/app/shared/sdk -d ng2web
````

and then open the file `webapp/src/app/shared/sdk/index` you should be able to see the SDKBrowserModule now available.

I will try to update the documentation ASAP, I just need to fix a couple of issues in NativeScript.

Cheers
Jon

**Comment by Mik-** [comment]
Hi Jon,
that worked perfectly fine.

Thanks for the fast response. I'm looking forward to see where this project (and fireloop) will go.

Mik

**Comment by jonathan-casarrubias** [comment]
Hey @Mik- I'm glad it worked!!!.

I estimate it will take some weeks to have all of this in a really good shape so I can launch it as stable.

No more features, nor breaking changes will be implemented from now to stable release, only bug fixing and documentation improvements.

Don't hesitate to add any issue or bug you may find.

Cheers!!
Jon
