### ISSUE TITLE
SocketConnections import being added incorrectly.

### ISSUE THREAD

**Issue by Destreyf** [mean-expert-official/loopback-sdk-builder#240]
#### What type of issue are you creating?
- [X] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [X] 2.1.0-rc.2 (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

There appears to be a bug with sockets being used even with the -i flag set to disabled (tried both -i disabled and -io disabled) the culprit is here: https://github.com/mean-expert-official/loopback-sdk-builder/blob/811bded84df724dc97e100b0cc6da8fded86b45b/lib/angular2/index.js#L399

This is causing angular 2 to fail to build while using the angular-cli, and most likely in any other use case where they're not utilizing sockets.

**Comment by Destreyf** [comment]
As a follow up buildModuleImports also lacks a conditional statement on SocketConnections import statement.

SocketBrowser also ends up in the module definitions which should also be conditionally imported.

**Comment by jonathan-casarrubias** [comment]
Hey @Destreyf  there were several breaking changes, and some cases were not completely tested, thanks for reporting.

I will try to fix this asap, also if you are able to send a pull request for this would be much appreciated.

Cheers
Jon
