### ISSUE TITLE
Question about requesting Data

### ISSUE THREAD

**Issue by PhilippeCorreges** [mean-expert-official/loopback-sdk-builder#242]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [X] Question

#### What version of this module are you using?
- [X] 2.0.10 (Stable)
- [ ] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

Hello,
Would you please excuse my poor ag2 level :(
I have generated a component with ng g component and want to use it to manage a model called Category.
In the component I wrote something like below : 

import {Component} from '@angular/core';
import { CategoryApi } from '../shared/sdk/services';
@Component({
  selector: 'category',
  templateUrl: 'category.component.html'
})
export class CategoryComponent {
  constructor(
     ) { }
getCategories()
{
   var categories=CategoryApi.find()
  };
  }

I used to have this previously : 
 **$scope.categories = [];
      function getCategories() {
        Category
            .find()
            .$promise
            .then(function(results) {
              $scope.categories = results;
            });
      }
      getCategories();**

I want to populate an array called categories to be able to show it using a ng-repeat.
Unfortunately my CategoryAPI.find() does not find anything ...

I would be very pleased for any help.

Thanks

**Comment by kattsushi** [comment]
CategoryApi is an injectable service component of angular 2
and execute the method of class in the constructor
try this.

`import {Component} from '@angular/core';
import { CategoryApi } from '../shared/sdk/services';
@Component({
selector: 'category',
templateUrl: 'category.component.html'
})
export class CategoryComponent {
public categories;
constructor(
  private category: CategoryApi
) {
 this.getCategories();
}
getCategories()
{
 this.category.find({}).subscribe((data)=>{
 this.categories = data;
}, err =>{
  console.log(err);
});
};
}
`

cheers!.

**Comment by PhilippeCorreges** [comment]
Thanks @kattsushi for the sample code I ll test tomorrow 
The link sends a 404 :)

**Comment by PhilippeCorreges** [comment]
That works fine.
Thanks @kattsushi 
I found the link too.

**Comment by PhilippeCorreges** [comment]
Hi @kattsushi 
On the same model, how would you make a create() in the database ?
I have an textarea like this : 
 **<textarea name="categoryName" class="mdl-textfield__input" type="text" id="textAddCategory"></textarea>**
and my database is waiting a **categoryName** field ...

Thanks in advance.

Philippe

**Comment by PhilippeCorreges** [comment]
Hello @kattsushi @jonathan-casarrubias 
I found a solution of getting input value in the component using 2 ways data binding.

My question is : Is there any doc somewhere on how I can use the SDK observables to do a create() ?

Thanks

**Comment by jonathan-casarrubias** [comment]
Hey @PhilippeCorreges I hope you have had a fun research and development.

Hey so, yes many of these questions are not right now within this documentation because mainly are in their respective documentations, either in the Angular 2 one or the LoopBack one, but I honestly think that since this is getting so much traction and many people is using it, I think is leading to some disservice from my part not adding a more complete documentation in here.

Look the SDK Builder replicates your LoopBack Models into Angular 2, so any exposed LoopBack Model with its methods would be within your SDK.

So, basically the following documentation from LoopBack explains how to manage data: http://loopback.io/doc/en/lb2/Creating-updating-and-deleting-data.html

The only translation would be that for Angular 2; since everything is an observable you need to execute the subscribe() to get the results, other than that the rest are the same methods definition.

To specifically answer how to create something:

````js

import { Model } from './shared/sdk/models';
import { ModelApi } from './shared/sdk/services';

@Component(...)
class MyComponent {

  // This prop  actually is binded into the angular 2 template
  private modelInstance: Model = new Model(); 
  constructor(private modelApi: ModelApi) {
    this.modelApi.create(this.modelInstance).subscribe((persistedInstance: Model) => {});
  }
}
````

**Comment by PhilippeCorreges** [comment]
Hi @jonathan-casarrubias 

Very fair answer. I ll go into it very quicky.

thanks again.

**Comment by PhilippeCorreges** [comment]
I have just succeeded to add a record in my MongoDB database having made some very few modifications to the code you provided. Tomorrow, I will clean the code up a little more and publish here my working example.

**Comment by jonathan-casarrubias** [comment]
Hey @PhilippeCorreges I'm glad to read you were able to succeed on an instance persistence.

I hope you to have fun building with NG2, LB and the generated SDK

Cheers!!
Jon

**Comment by PhilippeCorreges** [comment]
hi @jonathan-casarrubias 
I am certainly a newbie in angular and all that observable stuff but used to be a dev 20 years ago :) and should be able to make some good thinks with the sdk you provided. The main problem is a lack of documentation. Today the plan is to make a delete :) with a findById first and a following delete.
At the end, I will opt for a whole CRUD service. In a long term future.

**Comment by PhilippeCorreges** [comment]
Hi @jonathan-casarrubias 
Same issues for deleteById() ... I spent long hours trying to find out what my poor knowledge is lacking about ...
I have a table (working) with ngFor based on my Category component. I am showing a trash for each row to be able to delete a row by clicking on that trash. Here is the code : 
        `<table class="mdl-data-table mdl-shadow--2dp">
            <thead>
            <tr>
                <th>
                    {{ 'ISACTIVE' | translate }}
                </th>
                <th class="mdl-data-table__cell--non-numeric">{{ 'CATEGORYNAME' | translate }}
                </th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let category of categories">
                <td>
                    <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect mdl-data-table__select"
                           for="row[3]">
                        <input type="checkbox" id="row[3]" class="mdl-checkbox__input"/>
                    </label>
                </td>
                <td contenteditable='true' class="mdl-data-table__cell--non-numeric">{{category.categoryName}}</td>
                <td class="mdl-data-table__cell--non-numeric">{{category.id}}</td>
                **<td><i (click)="deleteCategory(category.id)" class="material-icons">delete</i></td>**
            </tr>
            </tbody>
        </table>
`
Now TS side, I have my category component defined like this : 

`import {Component} from '@angular/core';
import { CategoryApi } from '../shared/sdk/services';
import {Category} from "../shared/sdk/models/Category";

@Component({
  selector: 'category',
  templateUrl: './category.component.html',
  styleUrls: ['./category.component.css']
})
export class CategoryComponent {
  public categories;
  categoryId = '';
  private categoryInstance: Category = new Category();
  constructor(private category: CategoryApi)
  {
    this.getCategories();
   }
  getCategories(): void {
    this.category.find({}).subscribe((data)=>{
      this.categories = data;
      console.log(data);
    }, err =>{
      console.log(err);
    });
  };
  addCategory(): void {
    this.category.create(this.categoryInstance).subscribe((persistedInstance: Category) =>{});
    this.getCategories();
  };
  deleteCategory(): void{
    alert(this.categoryId);
    this.category.deleteById(this.categoryInstance.id).subscribe((persistedInstance: Category) =>{
      console.log((persistedInstance.id));

    });
    this.getCategories();
  };
}`

Of course, my deleteCategory function does not work. 
any idea ? I am pretty sure yes

Thanks in advance.

**Comment by kattsushi** [comment]
hi @PhilippeCorreges  try this pass parameter id in like you have in the template
```
<td><i (click)="deleteCategory(category.id)" class="material-icons">delete</i></td>
```


```
deleteCategory( id : string ): void{

    this.category.deleteById( id ).subscribe(() =>{
      // .. success delete
    });
   this.getCategories();
 };
```

**Comment by PhilippeCorreges** [comment]
@kattsushi 

FYI, I hard coded an ID inside the code above like 
`this.category.deleteById(58342db76101e85a058dd9d3).subscribe(() =>{ }); this.getCategories();`

and it works fine.

Getting the ID from the template is not part of the sdk.

Thanks

**Comment by jonathan-casarrubias** [comment]
Hi @PhilippeCorreges, not sure why are you adding the this.categoryId, but at the end it should work as @kattsushi's example, the problem is that you actually need to pass the id some how, but in your first example you did not pass it at all.

Second, I always recommend to follow the dependency injection, pattern in which I would always pass the entire dependency, instead of each of its properties.

````html
<td><i (click)="deleteCategory(category)" class="material-icons">delete</i></td>
````

````js
deleteCategory(category: Category): void{
  this.category.deleteById( category.id ).subscribe(() =>{ console.log('success') });
  this.getCategories();
};
````

That should definitely work.

Cheers
Jon
