### ISSUE TITLE
How to use AccessToken

### ISSUE THREAD

**Issue by mikkoh85** [mean-expert-official/loopback-sdk-builder#244]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [x] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [x] 2.1.0-rc.2 (2.1 Release Candidate 2)
- [ ] Other

Hello,

I am a bit new with LoopBack and definetly new with loopback-sdk-builder. I followed the Wiki documentation, which is good and I was able to get my backend work with angular-cli built frontend. 

However, I didn't find any documentation how to use services with AccessToken. I found how to get the token when login, but didn't found how to pass it to some api service call with ACL. My Angular2 function example:

`  private getSites() {
    this.siteApi.find().subscribe(
      sites => console.log(sites)
    );
  }`

I guess the access token should go to getSites() params?

That one prints error like this on browser console when it has ACL $everyone in "DENY":
`message
:
"Authorization Required"
name
:
"Error"
statusCode
:
401
__proto__
:
Object`

...and like this when I put ACL $everyone to "ALLOW":
`Array[1]
0
:
Site
admin
:
1
id
:
1
url
:
"www.testurl.com"`

So it works just as it should, but I just don't know where to pass the AccessToken when using something that has ACL rule for some particular role. 

I know, dumb question :) An example would be nice to have on Wiki.

**Comment by jonathan-casarrubias** [comment]
Hi @mikkoh85 thanks for reaching me out,

Hey so, you don't need to pass the access token, that is internally managed within the SDK Core, you just need to login an account, and the SDK will persist a cookie with the access token, this will be automatically loaded on any request.

**Comment by mikkoh85** [comment]
Oh alright. Neat thing. Thank you
