### ISSUE TITLE
base-service request method is calling errorHandler without this-context

### ISSUE THREAD

**Issue by hgoebl** [mean-expert-official/loopback-sdk-builder#249]
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [x] 2.0.10 (Stable)
- [ ] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

`BaseLoopBackApi.request` calls the error-handler as a pure function without its own this context.
This leads to unexpected results (usually null-pointer exceptions).

<https://github.com/mean-expert-official/loopback-sdk-builder/blob/master/lib/angular2/shared/services/core/base.ejs#L127>

instead of

      .catch(this.errorHandler.handleError);

it should read

        .catch((e) => this.errorHandler.handleError(e));

I suppose everybody can imagine what happens if someone replaces the default ErrorHandler with something depending on `this`.

Sorry for not creating a PR, but I'm in a hurry.

**Comment by jonathan-casarrubias** [comment]
Hey @hgoebl thanks for reporting and also for contributing with the approach,

I will add a fix for this ASAP.

Cheers
Jon
