### ISSUE TITLE
Issue building ng2 with rxjs-rc

### ISSUE THREAD

**Issue by redaikidoka** [mean-expert-official/loopback-sdk-builder#250]
#### What type of issue are you creating?
- [ X ] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [ X ] 2.1.0-rc.2 (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

When building my app with the generated code, and using the newer react:
`    "rxjs": "5.0.0-rc.5",`

there is a build error:
`[default] /src/app/shared/datasdk/services/core/error.service.ts:12:39`

which can be corrected by giving the ErrorObservable return value a type, cum sa:

`@Injectable()
export class ErrorHandler {
  public handleError(error: Response): ErrorObservable<string> {
    return Observable.throw(error.json().error || 'Server error');
  }
}`

**Comment by jonathan-casarrubias** [comment]
Hey @redaikidoka thanks for reporting I will add a fix for this ASAP.

Cheers
Jon
