### ISSUE TITLE
Cannot find module 'application-settings'

### ISSUE THREAD

**Issue by viki53** [mean-expert-official/loopback-sdk-builder#255]
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [x] 2.1.0-rc.2 (2.1 Release Candidate 2)
- [ ] Other

#### Please add a description for your issue:

Hi,

I just generated a new version of the SDK for Angular 2 (`-d ng4web`) and there's a line that seems odd in `storage/storage.native.ts`:

```
import * as AppSettings from 'application-settings';
```

The `application-settings` module isn't found, so TypeScript cannot compile it

Also, there are similar errors with the `sockets` modules, as we are not using sockets, so not generating this part of the SDK (`-i disabled`).

**Comment by jonathan-casarrubias** [comment]
Hi @viki53, this has been alreafy fixed ib RC4

Cheers
Jon

**Comment by hsdhillon** [comment]
Hi @jonathan-casarrubias, I ran into the same issue with with RC-8.3 when generating SDK using `-d ng2native` parameter. Here is the complete error message displayed by angular2

```
<path to sdk>/storage/storage.native.ts (2,30): Cannot find module 'application-settings'.)

ERROR in ./src/app/shared/sdk/storage/storage.native.ts
Module not found: Error: Can't resolve 'application-settings' in '<path to sdk>/shared/sdk/storage'
 @ ./src/app/shared/sdk/storage/storage.native.ts 10:0-52
 @ ./src/app/shared/sdk/index.ts
 @ ./src/app/app.component.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts
```

**Comment by jonathan-casarrubias** [comment]
hi @hsdhillon it is not the same issue, because @viki53 was receiving the issue while selecting ng2web, in which truly is wrong, 

But you are in fact selecting ng2native, which is intended for NativeScript users, in which you would have access to application-settings,

Are you really creating a nativescript application? Otherwise maybe  using ng2native is not the right flag for you.
