### ISSUE TITLE
Question: How to get logged in user information

### ISSUE THREAD

**Issue by PhilippeCorreges** [mean-expert-official/loopback-sdk-builder#256]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [X] Question

#### What version of this module are you using?
- [X] 2.0.10 (Stable)
- [ ] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

Hello,
I have the following login component: 
`import { Component, OnInit } from '@angular/core';
import { Client, AccessToken } from '../shared/sdk/models';
import { ClientApi } from '../shared/sdk/services';
import { Router } from '@angular/router';

@Component({
  selector: 'login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  private user: Client = new Client();

  constructor(
      private clientApi: ClientApi,
      private router: Router
  ) { }

  ngOnInit() { }

  login() {
    this.clientApi.login(this.user).subscribe(
        (token: AccessToken) => this.router.navigate(['/home']),
        err => alert(err.message)
    );
  }

}`

I am wondering how I can get access to the user(Client?) object in my whole app.

King regards,

**Comment by jonathan-casarrubias** [comment]
Hi @PhilippeCorreges thanks for reaching me out.

Once you get logged in, the SDK will temporally persist in memory the credentials, if you want to get the current account from any other component/section within your app, then you can do it by using the clientApi service as follows:

````js
class OtherComponent {
  constructor(private clientApi: ClientApi) {
    this.clientApi.getCurrent().subscribe(); // This will call from the backend the current user
    this.clientApi.getCachedCurrent().subscribe(); // This will call user from memory
  }
}
````

**Comment by PhilippeCorreges** [comment]
Thanks @jonathan-casarrubias

**Comment by PhilippeCorreges** [comment]
it works.
Thanks @jonathan-casarrubias

**Comment by PhilippeCorreges** [comment]
Hi @jonathan-casarrubias 
I would like to manage "menus" anfd show them only if user is authenticated.
I have seen there is a service called auth.service.ts.
Should I used it injecting it at the top level module to be able to know if a user is authenticated ?

Many thanks for you advice on that topic.
