### ISSUE TITLE
2.1.0-rc6 storage.swaps.ts causes a problem on build

### ISSUE THREAD

**Issue by dehypnosis** [mean-expert-official/loopback-sdk-builder#271]
#### What type of issue are you creating?
- [x ] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [x ] 2.1.0-rc.6 (2.1 Release Candidate n)
- [ ] Other

#### Please add a description for your issue:

this line seems to cause a problem on my environment

```js
ERROR in ~/sdk/storage/storage.swaps.ts
Module build failed: Error: ~/sdk/storage/storage.swaps.ts (24,38): Extends clause of exported class 'InternalStorage' has or is using private name 'Storage'.)
~/sdk/storage/storage.swaps.ts (35,33): Extends clause of exported class 'SDKStorage' has or is using private name 'Storage'.)
    at _checkDiagnostics (~/node_modules/@ngtools/webpack/src/loader.js:115:15)
    at ~/node_modules/@ngtools/webpack/src/loader.js:140:17
 @ .~/sdk/index.ts 15:0-70
...
```

my build tool versions:
```js
"@angular/compiler-cli": "2.2.3",
"typescript": "~2.0.3",
```

when update to export the Storage class, built successfully

```js
export class Storage {
```
from https://github.com/mean-expert-official/loopback-sdk-builder/blob/81405ee06ca1ac151ea613189a39e606223685b1/lib/angular2/shared/storage/storage.swaps.ts#L9

**Comment by jonathan-casarrubias** [comment]
Hi @dehypnosis thanks for reporting it is so strange I tested with a {N} app and within the angular2 test and did not catch that error.

I didn't want to export it since it was just for extending locally

Anyway I see the angular2 tests is getting behind in the versions, maybe is the reason it did not catch the error.

I will update the unit tests and add a patch for this asap.

Cheers
Jon

**Comment by dehypnosis** [comment]
okay, thanks for your works

**Comment by trusktr** [comment]
Regarding the all-too-common "has or is using private name" error, I've opened a request to fix issues like these in TypeScript by bringing declaration files to parity with language features. https://github.com/microsoft/TypeScript/issues/35822
