### ISSUE TITLE
Ng build fails with AOT, lazy-loading

### ISSUE THREAD

**Issue by funkizer** [mean-expert-official/loopback-sdk-builder#278]
#### What type of issue are you creating?
- [ x ] Bug
- [ ] Enhancement
- [ x ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [ x ] 2.1.0-rc.6 (2.1 Release Candidate 6)
- [ ] Other

#### Description

I'm using Lazy Loading (Router's loadChildren) with angular-cli. JIT-compiling works flawlessly but crashed when using AOT compiler:

> $ ng build --aot --prod
> ERROR in Error encountered resolving symbol values statically. Reference to a non-exported class Storage. Consider exporting the class (position 9:1 in the original .ts file), resolving symbo
> l InternalStorage in client/src/app/sdk/storage/storage.swaps.ts
> 
> ERROR in ./src/main.ts
> Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'client\src'
>  @ ./src/main.ts 4:0-74
>  @ multi main
> 
> ERROR in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
> Module not found: Error: Can't resolve 'client\src\$$_gendir' in 'client\node_modules\@angular\core\src\linker'
>  @ ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js 69:15-36 85:15-102
>  @ ./~/@angular/core/src/linker.js
>  @ ./~/@angular/core/src/core.js
>  @ ./~/@angular/core/index.js
>  @ ./src/main.ts
>  @ multi main

I'm importing SDKBrowserModule in my root module, which lazy-loads all the routes. SDK is used in lazy-loaded modules.
```

 imports: [
        BrowserModule,
     ...,
        SDKBrowserModule.forRoot()
    ],
```

My app was only ~20% finished when I found this awesome SDK builder, so it's not too late to refactor out of lazy into eager loading, but still, I'm not too eager to do it because of obvious advantages. AOT shouldn't be the problem here right, got to be about lazy loading?

> $ ng -v
> angular-cli: 1.0.0-beta.24
> node: 6.9.1
> os: win32 x64
> @angular/common: 2.4.1
> @angular/compiler: 2.4.1
> @angular/compiler-cli: 2.4.1
> @angular/core: 2.4.1
> @angular/forms: 2.4.1
> @angular/http: 2.4.1
> @angular/platform-browser: 2.4.1
> @angular/platform-browser-dynamic: 2.4.1
> @angular/router: 3.4.1
> @angular/upgrade: 2.4.1

> $ node -v
> v6.9.1

**Comment by funkizer** [comment]
Adding export to class Storage in rc.7 didn't work, different error now. But man, you're fast  =)

> 
> ERROR in Error encountered resolving symbol values statically. Reference to a non-exported class Storage. Consider exporting the class (position 9:1 in the original .ts file), resolving symbo
> l InternalStorage in client/src/app/sdk/storage/storage.swaps.ts
> 
> ERROR in ./src/main.ts
> Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'client\src'
>  @ ./src/main.ts 4:0-74
>  @ multi main
> 
> ERROR in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
> Module not found: Error: Can't resolve 'client\src\$$_gendir' in 'client\node_modules\@angular\core\src\linker'
>  @ ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js 69:15-36 85:15-102
>  @ ./~/@angular/core/src/linker.js
>  @ ./~/@angular/core/src/core.js
>  @ ./~/@angular/core/index.js
>  @ ./src/main.ts
>  @ multi main

**Comment by funkizer** [comment]
Oops, that was the old error. Now it's:

> ERROR in Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler
>  (position 7:12 in the original .ts file), resolving symbol Ng2BootstrapConfig.theme in client/node_modules/ng2-bootstrap/components/ng2-bootstrap-config.d.ts, r
> esolving symbol TypeaheadContainerComponent in client/node_modules/ng2-bootstrap/components/typeahead/typeahead-container.component.d.ts, resolving symbol Typeah
> eadContainerComponent in client/node_modules/ng2-bootstrap/components/typeahead/typeahead-container.component.d.ts
> 
> ERROR in ./src/main.ts
> Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'client\src'
>  @ ./src/main.ts 4:0-74
>  @ multi main
> 
> ERROR in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
> Module not found: Error: Can't resolve 'client\src\$$_gendir' in 'client\node_modules\@angular\core\src\linker'
>  @ ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js 69:15-36 85:15-102
>  @ ./~/@angular/core/src/linker.js
>  @ ./~/@angular/core/src/core.js
>  @ ./~/@angular/core/index.js
>  @ ./src/main.ts
>  @ multi main

**Comment by jonathan-casarrubias** [comment]
Hey @funkizer I'm glad it is working with the latest RC Version, it seems that there are no more bugs for this version, but I want to wait until the holidays to finish so I can make sure more people is using it and then I will publish the stable version.

For now I can tell, and from the stats you provide... This is ready for production already :1st_place_medal: 

Cheers!!!
Jon
