### ISSUE TITLE
Community question : How to access remote API?

### ISSUE THREAD

**Issue by PhilippeCorreges** [mean-expert-official/loopback-sdk-builder#279]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [X] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [X] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:
Hello everyone.
I hope you all had a merry Xmas chilling out.

I have a question that could look quite strange to the most of you but ...:
I am using angular-cli which serves the app on port 4200.
My Api is running on port 3000.
Each time I run something into the app, the server part of the URL is from angular-cli. This seems normal to me.
But I want to access the data through the Loopback API which gives http response in json format I just have to read.
Let me explain:
I have links with a foreign key pointing to categories. Those are categories of links.
The api is: GET http://0.0.0.0:3000/api/Categories/**categoryID**/links
If I run an angular code, I can manage to have http://0.0.0.0:4200/api/Categories**categoryID**/links but I do not get a json as an http response because the server URL is not correct. I am obliged to make filters

I imaging pointing to the API server is the way to develop proper apps ...

So my question is:
As I am using [routerLink] to have my <a> tags (pointing to localhost:4200), do someone know how I could manage this kind of url stuff.

Many Thanks.

PS: Sorry if this may appear confused. It is for myself.

**Comment by AurelieV** [comment]
I, have you try to configure a proxy inside angular-cli to redirect api request to 3000 ?
You have to define a proxy file and pass it ng-serve.
Take a look [here](https://github.com/AurelieV/pptq-calendar/blob/master/proxy.conf.json), which I use with the command `ng serve --proxy-config proxy.conf.json`

**Comment by PhilippeCorreges** [comment]
Hi @AurelieV 
Thanks for the idea!
In fact in angular, we are managing routes which are "routes to components" and not at all an url management, I think. This is mostly done to lazy load components, architecting the app...
Now, what I think is that an angular component MUST own all the API routes that are linked to its model (if it is model linked) and inside this component, all the rest APIs must be managed. 
In that case, **all must be controlled by the SDK** and there should not be any url parameter management like getting an "id" in the url ... etc etc etc. We, I, must use only SDK functions and work on json responses.

What do you think ?

**Comment by AurelieV** [comment]
I don't know if I have understand you well, but an angular component cannot "own" API routes, because they are totally independant. The API can be use without your angular app. They must not be linked.
Can you explain me what you really want? Advice for code architecture/splitting?

**Comment by PhilippeCorreges** [comment]
hi @AurelieV 
ok.
In fact I have my Loopback APIs and am developing an app.
In this development life, I manage URLs, routes and API URLs.
So, I have absolutely no clear idea on where to manage all those things. For instance, lets talk about the User model.
Do we have to have a component "managing" all the User API urls ? : 
**/User/User_deleteById**, /**User/User_upsert_put_Users** etc etc 

The SDK is enabling us to get http json responses. So, we should be able to do everything in a component per Loopback model.

Do not know if I am clear :(

Thanks

**Comment by PhilippeCorreges** [comment]
hi @AurelieV 
For instance I have a Link model and I have a category model.
Each Link has a Category.
So I have a Category component which is responsible for showing Categories and a Link component for showing Links both in HTML tables.
Which one is responsible for showing /Categories/{id}/Links to show all the links of one category ?
I should be able to just send a get to this URL and grap the http response. In my case, I map the /Categories/{id}/Links to a route pointing to the Link component. After that I am getting parameters and renders the necessary data in my template url linked to LinkComponent.. This sounds very weird to me.
Is that the way it should work ? Should we have to do all those things ?

Thanks

**Comment by AurelieV** [comment]
Your API urls and your app urls are totally not linked.
You have a server with your Loopback application, for example served at localhost:3000/api.
You also have your angular app, which have internal routing (localhhost:4200).
When you navigate to one of your angular app url, it creates components which are then displayed on the screen. This components may need data. If so, they can request your api for this data. The easiest way to do so is to use the SDK generated, which exposes different methods which call your API url, listen the server response, transform it from json to javascript object and give you an Observable of the result.

Your angular app routing and your API urls are totally not the same world.
For answer your previous question, it is up to you to decide when and where display the data on your app. It will depend on your needs. But it does not have to be link the API structures. Each component may call several API urls to obtain all the data it needs.

**Comment by PhilippeCorreges** [comment]
thanks @AurelieV 
I think I am mismatching things as obviously our code will need to grap an id somewhere to execute an http request.
