### ISSUE TITLE
subject.next with throw or subject.error?

### ISSUE THREAD

**Issue by mike-packetwerk** [mean-expert-official/loopback-sdk-builder#281]
#### What type of issue are you creating?
- [X] Bug
- [X] Question

#### What version of this module are you using?
- [X] 2.1.0-rc.7 (2.1 Release Candidate 7)

Write other if any:

#### Please add a description for your issue:
https://github.com/mean-expert-official/loopback-sdk-builder/blob/9ddbdb8edb4934f1a504a22104cacda2b275f72a/lib/angular2/shared/models/flref.ejs#L207

As currently coded, an error object enters the stream as a higher-ordered stream. ie given:
```
subscribe(successFn, failFn, completeFn)
```
the successFn will receive a new Observable stream that has a single error result. Is this expected?

I would have thought we want the failFn to receive the original error object.

**Comment by jonathan-casarrubias** [comment]
Hey @mike-packetwerk thanks for reaching out.

Also, that is a great point... I believe the following would make much more sense, can you agree on that?

````js
    this.socket.onZone(`${ this.model.getModelName() }.value.result.${ this.id }`, (res: any) => {
      if (res.error) {
        subject.next(res.error);
      } else {
        subject.error(res);
      }
    });
````

Is always great to have users bringing up this kind of issues, this is the fuel that lets the project keeps growing.

Anyway, I will be adding this patch by the next RC.

Cheers
Jon

**Comment by mike-packetwerk** [comment]
This bug is not the same as #296. These are two independent problems. #281 is in-band error handling, and #296 is out-of-band error handling.
