### ISSUE TITLE
Support "PATCH" request method for "updateAttributes" model method/hook

### ISSUE THREAD

**Issue by suryakand** [mean-expert-official/loopback-sdk-builder#282]
#### What type of issue are you creating?
- [x] Bug
- [x] Enhancement

#### What version of this module are you using?
- [x] 2.0.10 (Stable)

Write other if any:

#### Please add a description for your issue:
Seem like in loopback's latest version they have implemented "PATCH" method (not PUT) for updating attributes on a model. The generated Angular2 SDK still generated "updateAttributes" method with "PUT" as request method. Please note "PATCH" method implementation may be only specific to Loopback 3.

Thanks,
- Surya

**Comment by jonathan-casarrubias** [comment]
Hi @suryakand thanks for reporting,

We will start working on supporting LB3 soon :)

**Comment by PhilippeCorreges** [comment]
Hi @suryakand
Happy new year coding :-) 
Could you please let me know which method I must use to update a model as doing a replaceById() does not work for me.

King Regards

**Comment by suryakand** [comment]
@PhilippeCorreges have you tried updateAttributes method (if you are using version 3.x)?

**Comment by PhilippeCorreges** [comment]
@suryakand 
thanks for your input.
I have seen this yesterday late evening and just tested it. The method works perfectly.

Thanks

**Comment by suryakand** [comment]
@PhilippeCorreges glad that it worked for you!

**Comment by luisfavila** [comment]
@jonathan-casarrubias I keep needing to manually edit `base.service.ts` and change updateAttributes from `PUT` to `PATCH`

**Comment by barocsi** [comment]
@jonathan-casarrubias Same here. Please advise. Shall we need to manually override put to patch generally ?

**Comment by rheineo** [comment]
I in my component.ts agree on suscribe.. 

this.modelApi.updateAttributes(this.model.id, this.model).subscribe(
            data => {
                console.log(data);
            },
            error => {
                console.log(error);
            }
        );
