### ISSUE TITLE
Support for remoteMethods in FireLoop

### ISSUE THREAD

**Issue by jonathan-casarrubias** [mean-expert-official/loopback-sdk-builder#285]
#### What type of issue are you creating?
- [X] Enhancement

#### What version of this module are you using?
- [X] 2.1.0-rc.n (2.1 Release Candidate n)

#### Please add a description for your issue:

Currently, there is no way to interact with remote methods using fireloop, this is quite important since most systems will require to create custom remote methods.

**Comment by hieuit7** [comment]
Hi,

I have a problem with remoteMethods post. How long to publish this release?

Thanks you

**Comment by jonathan-casarrubias** [comment]
Hi @hieuit7 thanks for reaching out.

Hey so, I estimate the next release will be out between 10~15 days.

**Comment by hieuit7** [comment]
Hi @jonathan-casarrubias,

Thanks for support! 

Nice day!
