### ISSUE TITLE
Update inline documentation to use official jsdoc type definitions 

### ISSUE THREAD

**Issue by Destreyf** [mean-expert-official/loopback-sdk-builder#287]
#### What type of issue are you creating?
- [ ] Bug
- [X] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [X] 2.1.0-rc.7 (2.1 Release Candidate 7)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

Right now the SDK generates sections like this
```js
  /**
   * ...
   * @param any id User id
   * @param any fk Foreign key for credentials
   * ...
   */
```
However in my IDE that leaves indicators like this
![image](https://cloud.githubusercontent.com/assets/967304/21576370/84da948e-cee9-11e6-968d-e7908bcc724a.png)

Note the yellow lines on the side this isn't a huge issue but it'd be nice to not have thousands of jsdoc errors in my editor when doing checks 😛 

the proper syntax in jsdoc to indicate type would look like this

```js
  /**
   * ...
   * @param {any} id User id
   * @param {any} fk Foreign key for credentials
   * ...
   */
```

It should be as simple as wrapping curly braces around the type portion.

Here's MS's official documentation on it: [JSDoc support in JavaScript - Microsoft/TypeScript Wiki](https://github.com/Microsoft/TypeScript/wiki/JSDoc-support-in-JavaScript)

It appears to be pretty straight forward to implement, if i find some free time this weekend i'll likely submit a PR for this.

**Comment by Destreyf** [comment]
Another cleanup item could be to remove the 
```js
let result = ...; 
return result;
```

As its not necessary to define the variable and immediately return it.

**Comment by jonathan-casarrubias** [comment]
Hi @Destreyf, thanks for reporting this issue.

Hey so, the let result reference is created because in some scenarios there is extra code between result declaration and return, anyway... I believe it would be good idea not to create the reference when there is nothing to do with it, like mapping it or something.
