### ISSUE TITLE
Duplicate method declarations

### ISSUE THREAD

**Issue by Destreyf** [mean-expert-official/loopback-sdk-builder#288]
#### What type of issue are you creating?
- [X] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [X] 2.1.0-rc.7 (2.1 Release Candidate 7)
- [ ] Other

Write other if any:

#### Please add a description for your issue:
In this file: https://github.com/mean-expert-official/loopback-sdk-builder/blob/master/lib/angular2/index.js#L273-L274 the `buildModelImports` and `buildModelProperties` are re-defined without a `buildModelProperties: buildModelProperties` at the bottom, i am unsure if this is intentional, it doesn't seem to be causing any issues when running the commands but my IDE complained about it.

**Comment by jonathan-casarrubias** [comment]
Hi @Destreyf, that is not a bug it is actually new javascript, try updating your ide or something.

**Comment by Destreyf** [comment]
@jonathan-casarrubias i understand this and use this on a daily basis, my point is that if you look at lines 268 and 269 you've already defined them, and then you're re-defining it using the self referencing method on lines 273 and 274, creating a duplicate item, Its technically just overwriting the previously defined method.

As for my IDE, its Jetbrains Webstorm, the latest version using the ES6 setting which is completely up to date with the latest ES standards.

![image](https://cloud.githubusercontent.com/assets/967304/21579064/8346781c-cf58-11e6-9e34-d1fdf53173ee.png)

**Comment by jonathan-casarrubias** [comment]
Ok I see your point now, it may be a merge conflict issue I will reopen this then so wendont forget to remove the previously defined props
