### ISSUE TITLE
dataType decimal treated as number

### ISSUE THREAD

**Issue by BostjanPisler** [mean-expert-official/loopback-sdk-builder#289]
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [x] 2.0.10 (Stable)
- [ ] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:
In my model definition I'm using type "number" combined with mysql dataType "decimal" which creates a restraint with TS not allowing other than numbers to be set on a property. Setting the type to "any" or "" (nothing) breaks the LB migration.

**Comment by jonathan-casarrubias** [comment]
HI @BostjanPisler thanks for reaching out.

Hey so, not totally sure I understand your problem but there are some points I would like to clarify

1.- There is no decimal type in loopback, should be number https://www.typescriptlang.org/docs/handbook/basic-types.html which also include decimals
2.- When generated, the SDK implements the number type in typescript, which also allows decimals https://www.typescriptlang.org/docs/handbook/basic-types.html

Technically if your property is type of number in TypeScript, you can use any type of number including decimals.

![image](https://cloud.githubusercontent.com/assets/1533239/21577841/60b3230a-cf2f-11e6-89f3-06e31be920a5.png)

![image](https://cloud.githubusercontent.com/assets/1533239/21577844/6db864a2-cf2f-11e6-9bdc-aacfc319d1ab.png)

![image](https://cloud.githubusercontent.com/assets/1533239/21577846/7b41f638-cf2f-11e6-8711-51eaaf235f95.png)

**Comment by BostjanPisler** [comment]
Yes, you're right! Just had to convert to primitive type number which as you pointed out is also decimal. Thanks
