### ISSUE TITLE
Getting AccessToken Error

### ISSUE THREAD

**Issue by Ellipizle** [mean-expert-official/loopback-sdk-builder#290]
### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [ ] ^2.1.0-rc.7
- [ ] Other

Write other if any:

#### Please add a description for your issue:
I am using loopback ^2.22.0 and sdk ^2.1.0-rc.7.

after running sdk build and starting serve ng2, i get this error
```javascript
Class `SDKToken` incorrectly extends base class AcessToken
 property `created` is optional in type `SDKToken` but reuire in type `AccessToken`
```
i change it to require in BaseModel and serve the app again, other errors shows
```javascript
ERROR in [default] C:\loopapp\web\src\app\shared\sdk\services\core\auth.service.
ts:5:19
Module '"C:/loopapp/web/src/app/shared/sdk/models/BaseModels"' has no exported m
ember 'AccessToken'.

ERROR in [default] C:\loopapp\web\src\app\shared\sdk\services\core\base.service.
ts:9:25
Module '"C:/loopapp/web/src/app/shared/sdk/models/BaseModels"' has no exported m
ember 'AccessToken'.
```

**Comment by Ellipizle** [comment]
I compared a client app generated with sdk  2.1.0.-beta 13 and i saw that in both auth.service and base.service, `AccessToken` was imported from its model like this 
```import { AccessToken } from '../../models/AccessToken';``` 
not from the baseModel which is done like this in the latest version (rc7)
 ```import { SDKToken,AccessToken } from '../../models/BaseModels';```

**Comment by jonathan-casarrubias** [comment]
Ok I see this issue is different from what I originally thought, we will neet to update the property declaration

**Comment by yagobski** [comment]
Any progress on this task?

**Comment by jonathan-casarrubias** [comment]
Im still working on other issues, but I estimate the next release will be in around 10~15 days.


Cheers
Jon
