### ISSUE TITLE
`{HTTP: {source: body}}` service arguments are handled oddly

### ISSUE THREAD

**Issue by hoxxep** [mean-expert-official/loopback-sdk-builder#298]
#### What type of issue are you creating?
- [x] Bug
- [x] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [x] 2.1.0-rc.7 (2.1 Release Candidate 7)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

A loopback remote method argument which is `{http: {source: body}}` will be passed the *entire* body, while the Angular2 sdk seems to think you can have multiple arguments with accepting the body. 

It also changes the structure of the body from what I would like. If I have `SomeModel`, with a `customCreate` method on the `POST: /` route, I want/expect the POST body to be the model object `{prop1: ..., prop2: ...}` as per RESTful design; but because the SDK supports multiple body args (note that loopback doesn't, nor does it make sense to, the argument *is* the body) it rewrites the post body to `{argname: {prop1: ..., prop2: ...}}`.

In the [`buildPostBody`](https://github.com/mean-expert-official/loopback-sdk-builder/blob/master/lib/angular2/index.js#L737) method it shouldn't be building an object of `{arg1: arg1, arg2: arg2}`, the body data should simply be the value of `arg1`.

This requires the [`buildPostBody`](https://github.com/mean-expert-official/loopback-sdk-builder/blob/master/lib/angular2/index.js#L737) function in `lib/angular2/index.js` to expect a single argument to be the body. (Maybe throw a warning/error if the user has multiple args that accept the POST body, since it doesn't make sense to have multiple).

Without these changes, I can't keep to RESTful design by creating/updating via custom methods and putting the post body "straight" into the DB, and I need to rewrite my argument like so:

```js
Person.customCreate = (person) => {
  person = person.person;  // need to do this because loopback-sdk-builder makes the body {person: actualPersonObjectIWishWasTheBody}
  return Promise.resolve(person).then(person => {person.id = 1; return person;}); // replace with creation logic
};

Person.remoteMethod('customCreate', {
  "accepts": [
    {
      "arg": "person",
      "type": "object",
      "required": true,
      "description": "The person object to create",
      "http": {
        "source": "body"
      }
    }
  ],
  "returns": [
    {
      "arg": "person",
      "type": "object",
      "root": true,
      "description": "The created person object."
    }
  ],
  "description": "Create a person",
  "http": [
    {
      "path": "/",
      "verb": "post"
    }
  ]
});
```

**Comment by jonathan-casarrubias** [comment]
Hi @hoxxep thanks for reaching me out.

Also, even if you don't believe it there actually are users adding more than 1 body param, actually that was a request and needed to add unit test for it, so I'm pretty sure LoopBack does accept more than 1 body param.

Anyway, I believe is valid to ask if there is only 1 body param not to wrap it into another param, so this way if you select only 1 body param you would get the results you expect.

I may be adding this for the next release, it is just has been a fat release and I need to publish ASAP.

Cheers
Jon

**Comment by hoxxep** [comment]
Hey @jonathan-casarrubias,

That's understandable, sounds odd but I guess there might be use cases for it I can't think of. As for the 1 body param case, I can't seem to find the code you mention? All I see on the GitHub master branch is the [`buildPostBody`](https://github.com/mean-expert-official/loopback-sdk-builder/blob/master/lib/angular2/index.js#L737) function which prints a list of the arguments (with no case for body args length = 1), and then the [`services.ejs`](https://github.com/mean-expert-official/loopback-sdk-builder/blob/master/lib/angular2/shared/services/custom/service.ejs#L49) line which directly prints that result?

Having a test of `postBodyKeys.length === 1` would solve it though. Where is the code you quoted located?

(FYI: loving the SDK by the way, massive, massive time saver!)

Cheers,
Liam

**Comment by jonathan-casarrubias** [comment]
Hi @hoxxep you can actually find the code within the base service

https://github.com/mean-expert-official/loopback-sdk-builder/blob/master/tests/ng2web/src/app/shared/sdk/services/core/base.service.ts#L74

**Comment by hoxxep** [comment]
Hi @jonathan-casarrubias,

Ah, my bad. This was a misunderstanding since I didn't realise that code would manipulate the body inside `request(...)`, apologies!

Cheers,
Liam
