### ISSUE TITLE
Zero results with complex filter (Loopback bug workaround suggestion)

### ISSUE THREAD

**Issue by Destreyf** [mean-expert-official/loopback-sdk-builder#301]
#### What type of issue are you creating?
- [X] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [X] 2.1.0-rc.8 (2.1 Release Candidate 8)
- [ ] Other
#### Please add a description for your issue:
When performing a count, it does a http query type request, but it can actually use the "where" header, i am having trouble with loopback with highly nested count filters, my filters look like this.
```
where[and][0][type][regexp]=/.*/i&
where[and][1][or][0][name][regexp]=/.*docs.*/i&
where[and][1][or][1][author.firstName][regexp]=/.*docs.*/i&
where[and][1][or][2][author.lastName][regexp]=/.*docs.*/i&
where[and][1][or][3][status][regexp]=/.*docs.*/i&
where[and][1][or][4][type][regexp]=/.*docs.*/i
```

This makes loopback return 0 results, this is not a bug in loopback-sdk-builder, but changing it to be where={json-here} works, and so does setting the where header (much like filter is) for counting so my recommendation is to migrate the where over to a header as well to help optimize query and prevent any issues.

**Comment by markv** [comment]
I've made a pull request to fix this bug

**Comment by Destreyf** [comment]
This was fixed by updating loopback, and shouldn't have been patched on the sdk-builder side.

**Comment by jonathan-casarrubias** [comment]
@markv yes it was unfortunate, but the patch introduced more problems than the fixed one.

Anyway fortunately the fix has been done inside the actual framework

Thanks for your contribution
