### ISSUE TITLE
User missing from BaseModels.ts

### ISSUE THREAD

**Issue by Destreyf** [mean-expert-official/loopback-sdk-builder#302]
#### What type of issue are you creating?
- [X] Bug

#### What version of this module are you using?
- [X] 2.1.0-rc.8 (2.1 Release Candidate 8)

#### Please add a description for your issue:
In my generated SDK output i was running into an error because the User wasn't included in the BaseModels.ts file.

**Comment by bitingedgemick** [comment]
@Destreyf changing the AccessToken entry in model-config.json and regenerating the SDK resolved for me.

`"AccessToken": {
    "dataSource": "MSC",
    "public": true  //rather than he default false
  },`

**Comment by jonathan-casarrubias** [comment]
Lol im sorry for that I fixed an issue for users enabling the access token which obviously led a mew issue for users not setting the access token as public. This always has been a headache.

I will send a fix asap.


Cheers Jon

**Comment by Destreyf** [comment]
@jonathan-casarrubias i manually patched it on my client project which is fine as a hold over for now so no rush on getting a fix, i'd rather have a solid solution than a 1 off fix.

**Comment by denzelwamburu** [comment]
Running into the same issue

**Comment by denzelwamburu** [comment]
@bitingedgemick  Work-around solves it, is this the best approach though?

**Comment by bitingedgemick** [comment]
@denzelwamburu Only a quick fix so I could continue with front end dev. I would think Jon will put something in place that doesn't require _public_ AccessTokens.

**Comment by jonathan-casarrubias** [comment]
yup, actually my preference is not to se it public, but some users do enable it. Anyway Ill send the fix asap
