### ISSUE TITLE
LoopBackAuth getToken returns <AccessToken>

### ISSUE THREAD

**Issue by Destreyf** [mean-expert-official/loopback-sdk-builder#303]
#### What type of issue are you creating?
- [X] Bug

#### What version of this module are you using?
- [X] 2.1.0-rc.8 (2.1 Release Candidate 8)

#### Please add a description for your issue:
I'm not sure if this is a bug or not so i marked it as Question with a ? in bug.

The Token in the LoopBackAuth is of type `SDKToken` and when you use getToken it returns an `AccessToken` this caused me a little bit of trouble because i use `getToken` to get the entire token object then i update the user with additional data pulled from the API (loopback include doesn't really give much to include on the login) and then i call `setUser` which takes a value of `SDKToken` to update the user information in the auth system.  Is this intentional?

I also noticed that "setUser" sets the SDKToken, but there could be a `setToken` and `setUser` which were separate.

**Comment by kattsushi** [comment]
1+

**Comment by Destreyf** [comment]
as a side note, calling `this.auth.setUser(<SDKToken>token);` does work as a work-around.

**Comment by brannon-darby** [comment]
https://github.com/mean-expert-official/loopback-sdk-builder/pull/305
