### ISSUE TITLE
Error With Observable in real.time.ts

### ISSUE THREAD

**Issue by denzelwamburu** [mean-expert-official/loopback-sdk-builder#304]
#### What type of issue are you creating?
- [X] Bug

#### What version of this module are you using?
- [X] 2.1.0-rc.n (2.1 Release Candidate n)

Write other if any:

#### Please add a description for your issue:

 Am running into an error when running the app

[10:44:12]  typescript: src/sdk/services/core/real.time.ts, line: 44 
            Type 'Observable<{}>' is not assignable to type 'Observable<null>'. Type '{}' is not assignable to type 
            'null'. 

      L43:  onDisconnect(): Observable<null> {
      L44:    return this.connection.sharedObservables.sharedOnDisconnect;

[10:44:12]  typescript: src/sdk/services/core/real.time.ts, line: 52 
            Type 'Observable<{}>' is not assignable to type 'Observable<null>'. Type '{}' is not assignable to type 
            'null'. 

      L51:  onAuthenticated(): Observable<null> {
      L52:    return this.connection.sharedObservables.sharedOnAuthenticated;
[10:44:12]  typescript: src/sdk/services/core/real.time.ts, line: 60 

            Type 'Observable<{}>' is not assignable to type 'Observable<null>'. Type '{}' is not assignable to type 
            'null'. 

      L59:  onUnAuthorized(): Observable<null> {
      L60:    return this.connection.sharedObservables.sharedOnUnAuthorized;

[10:44:12]  transpile failed

**Comment by denzelwamburu** [comment]
Am `ionic-2.0.0-rc.4`

**Comment by jonathan-casarrubias** [comment]
Good catch, Ill fix it asap

**Comment by denzelwamburu** [comment]
@jonathan-casarrubias  What could be the issue?
