### ISSUE TITLE
nativescript-socket.io is causing issues while building for IOS (NativeScript)

### ISSUE THREAD

**Issue by jonathan-casarrubias** [mean-expert-official/loopback-sdk-builder#31]
**ISSUE 1:** nativescript-socket.io for IOS is WIP

[IOS DEVELOPMENT ROADMAP](https://github.com/naderio/nativescript-socket.io/issues/3)

**Comment by jonathan-casarrubias** [comment]
Looks like this is beyond `nativescript-socket.io`.

When installing some PODs, a workspace is created and that is the one that should be compiled using XCODE. this may be an issue from NativeScript since they are not handling.

As work around, open yourappname.xcworkspace in XCODE and build from there.

**Comment by jonathan-casarrubias** [comment]
NativeScript-socket.io is currently WIP

https://github.com/naderio/nativescript-socket.io/issues/3

**Comment by triniwiz** [comment]
@jonathan-casarrubias you can always check out https://github.com/triniwiz/nativescript-socketio :wink:

**Comment by jonathan-casarrubias** [comment]
Hey @triniwiz, actually I've seen your module before, but not for a while and now I see there is so much recent work.

I think I will be testing your module and if everything goes well I may be changing the dependency to yours.

Cheers
Jon

**Comment by jonathan-casarrubias** [comment]
Ok I verified and does not seems to be reliable neither.. Will keep this open until an integral fix is implemented.

**Comment by naderio** [comment]
Hi @jonathan-casarrubias,
I've just released a new version with almost full support for iOS including edge cases (I had to change the native implementation a bit).
I'm building on macOS Sierra and Xcode 8.0 and seems to work fine. Both for the demo and a near production app.
It requires the project to use Swift 3. Please check the demo to see how to enforce that.
Thanks.

**Comment by jonathan-casarrubias** [comment]
Hey @naderio thanks for reaching me out... Also, that sounds good to me, I will take a look on it.

Thanks for maintaining the support on your module.

Cheers!
Jon

**Comment by jonathan-casarrubias** [comment]
@naderio we have verified and is working pretty neat, we just found this issue https://github.com/naderio/nativescript-socket.io/issues/8,but  it is minor issue compared to the amount of hacks we needed to do before.

Please advice on this issue. 

Also, I'm rolling back to use your module again within the next major release.

Cheers
Jon
