### ISSUE TITLE
Auth service no removing cookies ( Angular 2 )

### ISSUE THREAD

**Issue by Eslem** [mean-expert-official/loopback-sdk-builder#316]
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [x] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

CookieBrowser service in some browsers (tested with ionic in android) the service is not removing all the cookies, so the session continue logued.
The problem is that in some browsers you have to add the path at the end of the expires. From [w3school](http://www.w3schools.com/js/js_cookies.asp):
> You should define the cookie path to ensure that you delete the right cookie.
> Some browsers will not let you delete a cookie if you don't specify the path.

So the line 34 of the file cookie.browser.ts should be:
`js    document.cookie = key + '=; expires=Thu, 01 Jan 1970 00:00:01 GMT;path=/;';
`

**Comment by Destreyf** [comment]
Here's the code i'm using in my logout component (which also calls auth.clear)

```js
window.document.cookie.split(";").forEach(function(c) { 
    document.cookie = c.replace(/^ +/, "").replace(/=.*/, "=;expires=" + new Date().toUTCString() + ";path=/"); 
});
```

Its a little nasty but it removes everything (which is what we need in our project, not just sdk cookies).

**Comment by jonathan-casarrubias** [comment]
Hi @Eslem thanks for reporting, hey so I received a pull request fixing the path issue https://github.com/mean-expert-official/loopback-sdk-builder/pull/326/files 

I'm about to bundle a new version with all the pull request and fixed and publish asap, maybe today maybe tomorrow

Cheers
Jon

**Comment by jonathan-casarrubias** [comment]
Also, there is going to be a new option to select either localStorage or cookies
