### ISSUE TITLE
Question about requesting related models

### ISSUE THREAD

**Issue by PhilippeCorreges** [mean-expert-official/loopback-sdk-builder#318]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [X] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [X] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:
Hello every one
I have a question about related models requests.
I have a Client Model who has a preferedLanguage (1to1 relation) i.e. 
`{
  "name": "Language",
  "plural": "Languages",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "languageName": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {
    "clients": {
      "type": "hasOne",
      "model": "Client",
      "foreignKey": ""
    }
  },
  "acls": [],
  "methods": {}
}`

In the database, of course, Client side, the preferedLanguge Id is stored.
My question is : Is there a way to get directly the LanguageName coming from the Language Table with something like this.clientApi.getCachedCurrent().getPreferedLanguage? Or should I request the  Language database with the ID to get the name and show it (showing it is the objective here). I have gone through the SDK but found nothing.

Thanks for your help.

**Comment by jonathan-casarrubias** [comment]
Hi @PhilippeCorreges thanks for reaching us out.

Hey so, the getCachedCurrent will get only what was persisted during the login process, which is a token instance with user details, but for other different relationships you will need to make a second call for that, though you can later persist that in local storage for future purposes.

**Comment by PhilippeCorreges** [comment]
Hi @jonathan-casarrubias 
Yes of course but my question is much more on querying related models in general.
Should we launch a getCachedcurrent(), get the language id that is in the user details and make a request on the preferedLanguage to get the prefered language of that user or does it exist something like this.clientAPI.getCachedCurrent().getPreferedLanguage() method coming diretly from the sdk?
Thanks

**Comment by jonathan-casarrubias** [comment]
Hi @PhilippeCorreges the only cached featured implementation is for authentication, other than that you need to make HTTP calls, if you want to persist in local storage "cache yourself" you can import and use the SDKStorage service, that is the only way provided by the SDK for you to be able to cache any information you may need.

I hope this information clarify your question.

Cheers
Jon

**Comment by PhilippeCorreges** [comment]
yes.
Thanks
