### ISSUE TITLE
is Loopback 3.0 supported?

### ISSUE THREAD

**Issue by PatrikTes** [mean-expert-official/loopback-sdk-builder#320]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [x] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [x] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

is loopback 3.0 supported with current loopback sdk builder?

**Comment by vinodc** [comment]
@PatrikTes I believe it is but you might have to use 3.1.1 for the current time (see https://github.com/mean-expert-official/loopback-sdk-builder/issues/310)

**Comment by jonathan-casarrubias** [comment]
@PatrikTes there are some methods missing but in general it does work, but for the problem mentioned by @vinodc.

Anyway I'm taking today for fixing most of the issues and publish the next release.

Cheers
Jon

**Comment by PatrikTes** [comment]
Great!
