### ISSUE TITLE
sdk fails to start with next version of loopback-boot

### ISSUE THREAD

**Issue by jmls** [mean-expert-official/loopback-sdk-builder#321]
#### What type of issue are you creating?
- [ x] Bug
#### What version of this module are you using?
- [x ] 2.1.0-rc.n (2.1 Release Candidate n)
#### Please add a description for your issue:

`./node_modules/.bin/lb-sdk tmp/demo4/server/server.js ./sdk -w` fails with `loopback-boot@3.0.0-alpha.1`

it works fine with `loopback-boot@2.23.0`

the error returned is

```
/home/ubuntu/workspace/node_modules/@mean-expert/loopback-sdk-builder/bin/lb-sdk:106
  if (fs.isEmptySync(context.outputFolder)) {
                            ^

TypeError: Cannot read property 'outputFolder' of undefined
    at verifyPath (/home/ubuntu/workspace/node_modules/@mean-expert/loopback-sdk-builder/bin/lb-sdk:106:29)
    at Object.<anonymous> (/home/ubuntu/workspace/node_modules/@mean-expert/loopback-sdk-builder/bin/lb-sdk:88:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

I think the boot phases have been changed, so the `booting` option is not added to app straight away, and is therefore undefined, which means the test 

```
if (app.booting) {
  app.on('booted', verifyPath);
} else {
  verifyPath();
}
```
will _always_ fail (undefined)

**Comment by jmls** [comment]
I have a patch that fixes this, but only because the `verifyPath` function is moved to cover the problem. The underlying cause of the changes in loopback-boot-3.0 is still there. However, it all seems to work. 

Do you want me to PR this "patch" ?

**Comment by jonathan-casarrubias** [comment]
Hey @jmls thanks for reaching out and for the time on digging for this.

Sending a pull request for this issue will be much appreciated, since there are a bunch  pending issues to be fixed, some help will speed up the process.

Cheers
Jon

**Comment by bariscicek** [comment]
Just changing this line;
82   var app = require(appFile);
to this
82   var app = require(appFile).app;

fixed it for me.

**Comment by jonathan-casarrubias** [comment]
Hey @jmls I believe you fixed this one in one of your pull requests right?

**Comment by jmls** [comment]
probably ;) It may have got combined into that pr

**Comment by jonathan-casarrubias** [comment]
ok cool, I will be publishing a new release with all of these changes by tomorrow.
