### ISSUE TITLE
Queries do not work with Cyrillic characters

### ISSUE THREAD

**Issue by astrons** [mean-expert-official/loopback-sdk-builder#328]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [*] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [*] 2.1.0-rc.8 (2.1 Release Candidate 8)
- [ ] Other

Write other if any:

#### Please add a description for your issue:
After the upgrade, loopback-sdk-builder to version Release Candidate. I stop working MongoDb search collection by using the query (collection).find (filter)
Queries do not work with Cyrillic characters. In the console get an error. In the console get an error: "is not a valid HTTP header field value".

_let question =  'На какую величину допускается превышение';
//question = encodeURIComponent(question);
let filterIn = {
  'where': { 'question': question} },
  'fields': { 'id': true }
};
this.ticketApi.find<Ticket>(filterIn).subscribe(
  res => console.log(res),
  err => console.log(err)
)_

**Console log:**
_EXCEPTION: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': '{"where":{"question":"На какую величину допускается превышение"},"fields":{"id":true}}' is not a valid HTTP header field value._

With Latin all searches work without problems. Transfer to URI encoding eliminates this problem, but these requests in the database is not in a single match.
Search query works without problems if you use the REST syntax.

**Comment by jonathan-casarrubias** [comment]
Hi @astrons thanks for reporting, I have recently changed from query string to headers search because of another user request.

Maybe what we should do is to add a parameter to decide if the search goes over query string or header according each developer requirements.

I'll try to add an option for this asap.

Cheers
Jon

**Comment by dehypnosis** [comment]
I am an Korean. i made a product with this.
but now i can't use any api with where, filter paramameter in sdk.

**Comment by dehypnosis** [comment]
+1

**Comment by astrons** [comment]
To solve this problem, it made its remote methods.

**Comment by dehypnosis** [comment]
i have done already but it is not good to make each overrided method for every given metbod which has arguments named filter, or where....

**Comment by jonathan-casarrubias** [comment]
Yes the "where through headers" patch has been a pain in the a**, I will remove that patch ASAP.

There are other issues related to this https://github.com/mean-expert-official/loopback-sdk-builder/issues/356

**Comment by jonathan-casarrubias** [comment]
can you confirm that removing the following lines

/lib/angular2/shared/services/core/base.ejs

````js
// Separate where object from url params and add to search query
if (urlParams.where) {
  headers.append('where', JSON.stringify(urlParams.where));
  delete urlParams.where;
}
````

**Comment by Cyperwu** [comment]
seems not working when I use other characters such as chinese

**Comment by Cyperwu** [comment]
Found a solution:
Actually `urlParams` will always carry `filter` and instead of `where` it was `filter.where` even in the latest release.
So I don't think this issue was fixed
To fix this bug you should try turn this
`     // Separate filter object from url params and add to search query
      if (urlParams.filter) {
        headers.append('filter', JSON.stringify(urlParams.filter));
        delete urlParams.filter;
      }`
into this
`      // Separate filter object from url params and add to search query
      if (urlParams.filter&&!urlParams.filter.where) {
        headers.append('filter', JSON.stringify(urlParams.filter));
        delete urlParams.filter;
      }`

**Comment by Cyperwu** [comment]
any response?

**Comment by guanbo** [comment]
@Cyperwu Chinese is not work for header filter, but you can try follow:
`LoopBackConfig.filterOnUrl();`
To work around.
