### ISSUE TITLE
User.updateAll return {count: 'number'} yet the sdk tries to map models out of it

### ISSUE THREAD

**Issue by rollwhistler** [mean-expert-official/loopback-sdk-builder#329]
#### What type of issue are you creating?
- [X] Bug
- [ ] Enhancement
- [] Question

#### What version of this module are you using?
- [X] 2.0.10 (Stable)
- [ ] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

I'm getting the following error when the sdk parses the response from UpdateALL:

TypeError: datum.map is not a function

The error comes from base.service.ts UpdateAll function:
 .map((datum: T[]) => datum.map((data: T) => this.model.factory(data)));

I guess the issue is that the SDK expected an array of updated objects, but the default behaviour, at least on my Loopback 2 is to return an object with the count number.

**Comment by kattsushi** [comment]
1+

**Comment by jonathan-casarrubias** [comment]
Hey @rollwhistler thanks for reaching us out and for reporting this problem.

I will fix this issue asap.

Cheers
Jon
