### ISSUE TITLE
Invalid request method in replaceOrCreate (PUT)

### ISSUE THREAD

**Issue by astrons** [mean-expert-official/loopback-sdk-builder#330]
#### What type of issue are you creating?
- [*] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [*] 2.1.0-rc.8 (2.1 Release Candidate 8)
- [ ] Other

base.service.ts file. The method used replaceOrCreate PUT method, according to REST syntax must use a POST.

**Comment by jonathan-casarrubias** [comment]
Hey @astrons thanks for reaching us out,

I will verify this issue asap.

Cheers
Jon
