### ISSUE TITLE
Duplicate of options argument when using injectOptionsFromRemoteContext

### ISSUE THREAD

**Issue by tobibrandenberg** [mean-expert-official/loopback-sdk-builder#331]
#### What type of issue are you creating?
- [X] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [X] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

When I use

```javascript
"options": {
    "validateUpsert": true,
    "injectOptionsFromRemoteContext": true
  }
```

in my model json file, the builder generates the relation query functions with duplicate of "options" argument

```javascript
public getOwner(id: any, options: any = {}, refresh: any = {}, options: any = {}): Observable<any> {
    let _method: string = "GET";
    let _url: string = LoopBackConfig.getPath() + "/" + LoopBackConfig.getApiVersion() +
    "/Groups/:id/owner";
    let _routeParams: any = {
      id: id
    };
    let _postBody: any = {};
    let _urlParams: any = {};
    if (refresh) _urlParams.refresh = refresh;
    let result = this.request(_method, _url, _routeParams, _urlParams, _postBody);
    return result;
  }
```

**Comment by jonathan-casarrubias** [comment]
Hi @tobibrandenberg this is a known issue and is already reported in here https://github.com/mean-expert-official/loopback-sdk-builder/issues/310

I will close this issue in favor of 310

Cheers
Jon
