### ISSUE TITLE
Face Dupplicate Identifier

### ISSUE THREAD

**Issue by ahmer-yasin** [mean-expert-official/loopback-sdk-builder#333]
#### What type of issue are you creating?
- [ ] Bug After generating services , see duplicate identifier in custom services
- [ ] Enhancement
- [ ] Question How can i generate code without facing any bug?

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [ ] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

**Comment by jonathan-casarrubias** [comment]
Hi @ahmer-yasin thanks for reaching us out.

Hey so, I believe this is a duplicate, please let me know if the following issue is the problem you are presenting: https://github.com/mean-expert-official/loopback-sdk-builder/issues/310

**Comment by ahmer-yasin** [comment]
hello @jonathan-casarrubias  yes this is same
