### ISSUE TITLE
fieldnames with dashes fail to generate valid code

### ISSUE THREAD

**Issue by jmls** [mean-expert-official/loopback-sdk-builder#337]
#### What type of issue are you creating?
- [x] Bug

#### What version of this module are you using?
- [x] 2.1.0-rc.8 (2.1 Release Candidate 8)

#### Please add a description for your issue:

Given this field definition in a model

```json
"path-server": {
      "type": "string"
    },
```

the generator creates code like this

```json
 path-server?: string;
```

and
```json
 path-server: {
          name: 'path-server',
          type: 'string'
        },
```

which is, as you are probably aware, illegal json / js object property names

**Comment by jonathan-casarrubias** [comment]
NOTE THE FUTURE ME: Will be closed when published
