### ISSUE TITLE
I was using the old Pub/Sub component

### ISSUE THREAD

**Issue by chl03ks** [mean-expert-official/loopback-sdk-builder#342]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [X] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [X] 2.1.0-rc.8.3 (2.1 Release Candidate n)
- [ ] Other^

#### Please add a description for your issue:
I was using the old Pub/Sub component and now i'm usin the new real time component but i don't have the `onCreateModelName` method in the ModelApi class my question here is how i update code to have the same behavior as before.

**Comment by jonathan-casarrubias** [comment]
Hi @owndann thanks for reaching me out,

Hey so, there was a big refactor within the latest versions to drastically reduce the size of the SDK, though that led to somehow skip the pubsub methods. I will restore that methods within the next release, I estimate it will be for  2.1 RC 8.4

Cheers
Jon

**Comment by owndann** [comment]
Thanks for you quick response and i'll try to use the FireLoop API it looks amazing

**Comment by owndann** [comment]
do you need any help on this one ?

**Comment by jonathan-casarrubias** [comment]
Hey Dan, thanks for proposing actually I do need some help on this... I'm in the middle of a product release and I won't be able to attend these issues at least in 1 or 2 weeks.

Basically, what needs to be done is 

1.- Within the BaseApi service, now there are generic methods that previously were repeated across the different model services. That is not happening now, so each of these persisted model methods within the base service, should have a pub sub method as before and passing the parameter "isIo" as true.

2.- For relational methods, maybe getting the old code from previous versions and restore it within the "services/custom.ejs" would be the easiest of the approach.

If you can add a pull request for this would be much appreciated.

Cheers
Jon

**Comment by chl03ks** [comment]
Awesome

**Comment by jonathan-casarrubias** [comment]
@chl03ks I just detected some bugs in the real-time module regarding the PubSub functionality,

I haven't used it in a while so not sure at what level something broke that feature, I'll try to send a patch for the real-time module ASAP, though the new SDK should work with older real-time modules or even the original PubSub.

Cheers
Jon
