### ISSUE TITLE
Duplicate parameter option in relation methods

### ISSUE THREAD

**Issue by hieuit7** [mean-expert-official/loopback-sdk-builder#343]
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [x] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

I have two models A and B with relation hasBelongToMany, when i use sdk to generate client sdk for angular 2:

A hasBelongToMany B

```bash
./node_modules/.bin/lb-sdk server/server client/path -l angular2 -d  ng2native  -i disabled 
```

after generate run, i check some method in A, duplicate parameter "option = {}"!!! 

Thank you!

**Comment by jonathan-casarrubias** [comment]
hi @hieuit7 are you using RC 8.3 or prior?¨
