### ISSUE TITLE
upsertWithWhere bad request

### ISSUE THREAD

**Issue by davidpestana** [mean-expert-official/loopback-sdk-builder#347]
#### What type of issue are you creating?
- [X] Bug
#### What version of this module are you using?
- [X] 2.1.0-rc.n (2.1 Release Candidate n)

when i use  swagger exproler this is te CURL  chain generated to apply at upserWithWhere 

> curl 'http://0.0.0.0:3001/api/Prices/upsertWithWhere?where=%7B%22kmRangeId%22%3A%225881789715ef053d73ce1478%22%2C%22serviceId%22%3A%2258817dedb43698003253d89b%22%2C%22rateId%22%3A%225882439cc128bb0034ef8a74%22%7D' -H 'Pragma: no-cache' -H 'Origin: http://0.0.0.0:3001' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: es-ES,es;q=0.8,en;q=0.6' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Cache-Control: no-cache' -H 'Referer: http://0.0.0.0:3001/explorer/' -H 'Connection: keep-alive' --data-binary $'{\n"kmRangeId":"5881789715ef053d73ce1478",\n"serviceId":"58817dedb43698003253d89b",\n"rateId":"5882439cc128bb0034ef8a74",\n"price":1222\n}' --compressed

hoewever when i use SDK to call  the CURL chain generated is different.  

> curl 'http://0.0.0.0:3001/api/Prices/upsertWithWhere' -H 'Pragma: no-cache' -H 'Origin: http://localhost:3000' -H 'where: {"serviceId":"58817dedb43698003253d89b","kmRangeId":"5881789c15ef053d73ce1479","rateId":"5882439cc128bb0034ef8a74"}' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: es-ES,es;q=0.8,en;q=0.6' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36' -H 'Content-Type: application/json' -H 'Accept: application/json, text/plain, */*' -H 'Cache-Control: no-cache' -H 'Referer: http://localhost:3000/' -H 'Connection: keep-alive' --data-binary '{"price":55,"serviceId":"58817dedb43698003253d89b","kmRangeId":"5881789c15ef053d73ce1479","rateId":"5882439cc128bb0034ef8a74"}' --compressed

i call the SDK in Angular2 Component with this code
```typescript
      this.priceApi.upsertWithWhere(
         {
              serviceId:this.service.id, 
              kmRangeId:this.kmRange.id,
              rateId: this.rate.id
          },
          {
              price:this.price.price,
              serviceId:this.service.id, 
              kmRangeId:this.kmRange.id,
              rateId: this.rate.id
          }      
      ).subscribe(result => console.log(result));
```
and Loopback returns a server side error...

> Error no gestionado para la solicitud POST /api/Prices/upsertWithWhere: AssertionError: The where argument must be an object at Function.DataAccessObject.patchOrCreateWithWhere.DataAccessObject.upsertWithWhere (/home/david/Projects/traqui/api-v2/price-api-v2/node_modules/loopback-datasource-juggler/lib/dao.js:663:3)

maybe i must be a call with another method?

thanks for all

**Comment by davidpestana** [comment]
i solved the last issue fixing  base.service.ts  at  line  91

```typescript
    // Separate where object from url params and add to search query
    if (urlParams.where) {
      headers.append('where', JSON.stringify(urlParams.where));
     // delete urlParams.where;
    
    }

```

**Comment by jonathan-casarrubias** [comment]
hi @davidcheung thanks for reporting,

This patch was recently added, I'm asking @markv the spirit behind the patch to see if he added that because he was having other problems or because is nicer.

At the end all the problems should be addressed broadly, so if there was no other problem solved maybe we just rollback the patch.

@markv thoughts?

**Comment by markv** [comment]
The problem arose from the loopback count endpoint. The query object only requires the where portion of the filter. The sdk ```BaseLoopBackApi.request``` method on the where query for the count endpoint is parsing the query to bracket notation this was causing problems when using the ```inq``` filter. If the count where query instead used the seemingly more reliable stringified json format it solved the issue. Is there any particular reason that the count filter is parsed to bracket notation?

**Comment by jonathan-casarrubias** [comment]
@markv I'm not totally sure about your issue, would you mind to provide examples?

From what I understand, I can say that originally filter queries where translated to query string, but the problem was nested 'include' queries with more than 3 sub-levels did not work.

Then filter queries were translated to filter=JSON.stringify({ A JSON }), similar to swagger and did work well, but it was difficult to debug, then I received a request to move from query string to header because it was easier to debug.

Anyway, again I'm not totally sure how the where filter ended, so I will need to verify, but definitely the fix should address both issues now.

**Comment by redaikidoka** [comment]
I'm also getting a problem with upsertWithWhere. 

In my strongloop app, I'm using the latest sdk builder:
`    "@mean-expert/loopback-sdk-builder": "2.1.0-rc.8.3",`

I'm calling: 
```
this.userApi.upsertWithWhere(
      {"idUser": _idUser},
      {"goalText": _textGoal, "sUpdateUser": _idUpdater}
      );
```
in my angular app, I get the error:
`POST http://127.0.0.1:3000/api/AdsUsers/upsertWithWhere 500 (Internal Server Error)`

In my strongloop app, I see this error:
```
Unhandled error for request POST /AdsUsers/upsertWithWhere: AssertionError: The where argument must be an object
    at Function.DataAccessObject.patchOrCreateWithWhere.DataAccessObject.upsertWithWhere (/Users/pol/Dev/coach/pgAccess-rambutan/node_modul
es/loopback-datasource-juggler/lib/dao.js:663:3)
    at SharedMethod.invoke (/Users/pol/Dev/coach/pgAccess-rambutan/node_modules/strong-remoting/lib/shared-method.js:262:25)
    at HttpContext.invoke (/Users/pol/Dev/coach/pgAccess-rambutan/node_modules/strong-remoting/lib/http-context.js:295:12)
    at phaseInvoke (/Users/pol/Dev/coach/pgAccess-rambutan/node_modules/strong-remoting/lib/remote-objects.js:647:9)
    at runHandler (/Users/pol/Dev/coach/pgAccess-rambutan/node_modules/loopback-phase/lib/phase.js:135:5)
    at iterate (/Users/pol/Dev/coach/pgAccess-rambutan/node_modules/async/lib/async.js:146:13)
    at Object.async.eachSeries (/Users/pol/Dev/coach/pgAccess-rambutan/node_modules/async/lib/async.js:162:9)
    at runHandlers (/Users/pol/Dev/coach/pgAccess-rambutan/node_modules/loopback-phase/lib/phase.js:144:13)
    at iterate (/Users/pol/Dev/coach/pgAccess-rambutan/node_modules/async/lib/async.js:146:13)
    at /Users/pol/Dev/coach/pgAccess-rambutan/node_modules/async/lib/async.js:157:25
    at /Users/pol/Dev/coach/pgAccess-rambutan/node_modules/async/lib/async.js:154:25
    at execStack (/Users/pol/Dev/coach/pgAccess-rambutan/node_modules/strong-remoting/lib/remote-objects.js:492:7)
    at RemoteObjects.execHooks (/Users/pol/Dev/coach/pgAccess-rambutan/node_modules/strong-remoting/lib/remote-objects.js:496:10)
    at phaseBeforeInvoke (/Users/pol/Dev/coach/pgAccess-rambutan/node_modules/strong-remoting/lib/remote-objects.js:643:10)
    at runHandler (/Users/pol/Dev/coach/pgAccess-rambutan/node_modules/loopback-phase/lib/phase.js:135:5)
    at iterate (/Users/pol/Dev/coach/pgAccess-rambutan/node_modules/async/lib/async.js:146:13)

```

**Comment by KingsDevelopment** [comment]
+1 on last comment, we get this too..

**Comment by josephlaw** [comment]
I use below method to update record successfully
```
           var params = {
               name: "myname"
           };
           User.upsertWithWhere({
              where : {
                 id : "testing"
               }
          }, params, function(result) {
              console.log('record', result);
            });

```

**Comment by dmastag** [comment]
Right now I am using

LoopBackConfig.whereOnUrl();

So that I can use it
