### ISSUE TITLE
Unable to send 0 or false to number/boolean arguments in custom method

### ISSUE THREAD

**Issue by mahendranvm** [mean-expert-official/loopback-sdk-builder#349]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [x] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [x] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

I have a custom method that takes a required boolean and number type arguments. The generated sdk creates urlParams like this "if(argX)  _urlParams.argX = argX". So when I pass 0s (or FALSEs) to argX, they are not getting added to urlParams resulting in 400 Errors. Should the check be rather for undefined or null rather than like this: if (typeof argX !== 'undefined' && argX !== null) _urlParams.argX = argX

**Comment by jonathan-casarrubias** [comment]
thanks for reporting I will need to add a unit test for this an verify the issue

**Comment by mahendranvm** [comment]
Hi, thanks for the updates. This is marked closed, but rc.9 still produces urlParams like below:
if (${param.arg}) _urlParams.${param.arg} = ${param.arg};

So, it the value passed is a 0 or false, the parameter is still not attached.

**Comment by jonathan-casarrubias** [comment]
yeah not sure what happened, I did fix this but I'm seeing the result and the changes are not there in the release...

I'll open it again and send the fix in the next version
