### ISSUE TITLE
setUsername and setToken Bad Documentation!

### ISSUE THREAD

**Issue by rodplata** [mean-expert-official/loopback-sdk-builder#351]
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [x] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:
In the new version you split the setUsername() and setToken() but the documentation (for social login integration, for example) you still just using setUsername()

**Comment by jonathan-casarrubias** [comment]
Yes I can do that now
