### ISSUE TITLE
Loopback API + ionic2 - separate

### ISSUE THREAD

**Issue by demiro** [mean-expert-official/loopback-sdk-builder#352]
So, here is my story

I created first a sails API
And ionic2 app

both separate folders and would like it too keep that way
then I dismissed sails and opted for loopback instead

now, for what I found and read, mostly of the SDK and projects would require loopback project and ionic/angular project to be under the same folder..

I would like to completely separate the concerns but still use at least the basic http auth/connection services 

How do I do that? Can I use loopback sdk builder in my ionic2 project?
Can I just get the auth service?

I find no examples of how to use loopback and provided sdk services when projects are separate

**Comment by denzelwamburu** [comment]
Hey @demiro.
Yes you can.
The build sdk can be imported to your project folder and be able to manipulate the services.

**Comment by jonathan-casarrubias** [comment]
@demiro not sure where you read that the Client Project requires to be inside the LoopBack project. But that is 100% incorrect.

You can if you want have Client and Server together, mainly on web projects... But you can definitely  have separated concerns, actually when you generate the SDK it ask you where you want to place the SDK, in this case your Ionic APP that can be located in any other place of the filesystem.

Of course the SDK should be inside your angular 2 application, but not as you are describing.

I hope this helps you clarify your questions.

**Comment by jonathan-casarrubias** [comment]
Closing due inactivity, also I need to clean the repo to open space for LB4 related issues.
