### ISSUE TITLE
Filters = {} in remotemethod can't accept empty object as arg?

### ISSUE THREAD

**Issue by barocsi** [mean-expert-official/loopback-sdk-builder#357]
#### What type of issue are you creating?
- [ x ] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [x ] 2.0.10 (Stable)
- [ ] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Remote method
```

    bdata.remoteMethod(
        'query',
        {
            accepts: [
                {arg: 'filters', type: 'object', required: true},
                {arg: "options", type: "object", http: "optionsFromRequest", required: false}
            ],
            returns: {arg: 'item', type: 'object'},
            http: {path: '/query', verb: 'get'},
            notes: "Queries arbitrary aggregate objects from the database"
        }
    );

```

can't receive a {} filter object? why?
```
 this.bdataAPI.query({})
            .subscribe(result => {
 
            }, error => {
              // throws 400 error of filter argument missing. its not. its just empty
            })
```

**Comment by barocsi** [comment]
It's probably because filters object is being manipulated for whatever fancy reason in base.service.ts:
```
 // Separate filter object from url params and add to search query
    if (urlParams.filter) {
      headers.append('filter', JSON.stringify(urlParams.filter));
      delete urlParams.filter;
    }
```
is this neccessary? this way if you add a {} to the headers it seems to be missing by the api.

**Comment by rodplata** [comment]
Same problem here with the issue #356 
@jonathan-casarrubias  any update of this?

**Comment by jonathan-casarrubias** [comment]
Well is not really the same issue, the other is related to the where and this to the filter object.

Filter is being sent through headers because a patch I received because it was easier to debug than query string parameters, but also... It does fix a bug when passing deep nested include filters, in query string won't include more than 2 levels.

So, basically is trying to fix a Framework limitation, on client side. Also, when I accepted this patch I verified that passing the filter through headers is valid for LoopBack, so if it is not accepting an empty value, maybe and just maybe is a framework issue, not sdk.

**Comment by jmls** [comment]
I may have just hit this problem: passing in a filter defined as 

`await this._taskService.findById(id,{ include: 'comments'}).toPromise()`

works just fine, but 

`await this._taskService.findById(id,{ include: ['comments','worklogs']}).toPromise()`

does not (no comments or worklogs applied) 

how can I include more than one child on a request ?

**Comment by Destreyf** [comment]
@jmls This should work as you are using it, i have a couple models that have 10-12 relationship includes, i would verify that the filter works when calling the rest endpoint, and if that doesn't work, then its likely that the model taskService or the relationship item, have an invalid relationship or its missing.

**Comment by jmls** [comment]
heh - yah, it's my bad. For some reason I have a `remoteMethod` defined in the task model with `filter` set as a string parameter. I fixed that (removed it) , regenerated the sdk and the problem went away ..

**Comment by Destreyf** [comment]
@jmls No worries, its easy to miss things like that, especially with how flexible loopback can be, i've found the best thing to do when running into issues is to check if the rest endpoint works, and if that does, then inspect a request made from the explorer and a request made from the sdk in the browsers network tab in dev tools.

**Comment by jonathan-casarrubias** [comment]
This has been fixed in an earlier version,

If you want to send an empty object, you will need to pass the filter through query string and not through headers.

In order to achieve that just configure the SDK as follows:

````js
LoopBackConfig.filterOnUrl();
````
