### ISSUE TITLE
Cookie Browser not found if using AOT build

### ISSUE THREAD

**Issue by dmastag** [mean-expert-official/loopback-sdk-builder#359]
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [X] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:
I am using it on a Ionic2 / Angular 2 Project

#### Please add a description for your issue:
For some reason if I use the SDK and build the app for production it says that the cooke.browser cannot be found. Have tried it on 2 separate projects with the same result.

As far as I know the production build in Ionic2 is using AOT/Tree Shaking

**Comment by dmastag** [comment]
This is the exact message I receive:

> main.js:32 Uncaught Error: Cannot find module "../../storage/cookie.browser"

**Comment by albertorcf** [comment]
The same issue for me.

**Comment by jonathan-casarrubias** [comment]
Thats odd, will need to verify

**Comment by imron02** [comment]
This is fix by use ionic v2.2.0 and ionic-storage 2.0.0
