### ISSUE TITLE
Add filters to getcurrent

### ISSUE THREAD

**Issue by barocsi** [mean-expert-official/loopback-sdk-builder#361]
#### What type of issue are you creating?
- [ ] Bug
- [ x ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [x ] 2.0.10 (Stable)
- [ ] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:
I need to get the current user with {include:[]} enabled. Why is this omitted?

**Comment by jonathan-casarrubias** [comment]
Not sure will need to verify
