### ISSUE TITLE
Question: What are the latest supported version?

### ISSUE THREAD

**Issue by PhilippeCorreges** [mean-expert-official/loopback-sdk-builder#362]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [X ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [X] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:
Hello,
Which are the latest supported version of loopback with both 2.0.10 and 2.1.0.X?

Thanks and Regards

**Comment by jonathan-casarrubias** [comment]
Right now it does support loopback 3, but there are issues to be solved.

Cheers

**Comment by PhilippeCorreges** [comment]
Thanks @jonathan-casarrubias
