### ISSUE TITLE
Could you please give me some detail info about Real-Time App Example

### ISSUE THREAD

**Issue by fanttm** [mean-expert-official/loopback-sdk-builder#364]
#### What version of this module are you using? - [ ] 2.0.10 (Stable)
Write other if any:  #### Please add a description for your issue:

On "5. Usage Examples", I tried to write my test code of Real-Time App Example, but I always get error info "Property 'onCreate' does not exist on type 'AccountApi'." I consider that some necessary steps must be missed. How can I do about it?

**Comment by aCasasItexico** [comment]
Documentation in point 5 seems to be little odd, logic changed in order to use references instead of using ModelApi events, please refer to [Fireloop Documentation](http://docs.fireloop.io/en/api/)

```
constructor(private realTime: RealTime) {
     this.realTime
        .onReady()
        .subscribe(() =>
            this.RoomReference = this.realTime.FireLoop.ref<Room>(Room)
            this.RoomReference.on('change',{
              limit: 10,
              order: 'id DESC',
              include: 'members'
            }).subscribe((rooms: Room[]) => console.log(rooms));
        );

**Comment by jonathan-casarrubias** [comment]
Right, the SDK builder provides serveral Real-Time approaches, the one on page number 5 is using the PubSub pattern that got broken in a SDK Builder update

Related issue: https://github.com/mean-expert-official/loopback-sdk-builder/issues/342

Another Real-Time implementation is the FireLoop one, and you can find more complete documentation in http://docs.fireloop.io

**Comment by fanttm** [comment]
Thanks, it real helpful!
