### ISSUE TITLE
Error when generating SDK

### ISSUE THREAD

**Issue by PhilippeCorreges** [mean-expert-official/loopback-sdk-builder#366]
#### What type of issue are you creating?
- [X] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [X] 2.1.0-rc.8.3
- [ ] Other

Write other if any:

#### Please add a description for your issue:
I have updated  loopback-sdk builder and trying to generate the SDK from the project root folder with:
**./node_modules/.bin/lb-sdk ./server/server.js ./angular2client/src/app/shared/sdk**

I am getting:

TypeError: Cannot read property 'outputFolder' of undefined
    at verifyPath (/Users/IOSoftwareSAS/WebstormProjects/distinguo/node_modules/@mean-expert/loopback-sdk-builder/bin/lb-sdk:106:29)
    at Object.<anonymous> (/Users/IOSoftwareSAS/WebstormProjects/distinguo/node_modules/@mean-expert/loopback-sdk-builder/bin/lb-sdk:88:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by anodynos** [comment]
I got the have the same problem (with slight diff line numbers), when executing 
```
╰─$  npm install --save @mean-expert/{loopback-component-realtime,loopback-sdk-builder}                                                       
loopback-example-app@0.0.1 /mnt/projects/trials/loopback-example-app
├── @mean-expert/loopback-component-realtime@1.0.0-rc.4 
└── @mean-expert/loopback-sdk-builder@2.1.0-rc.8.3 

╰─$ ./node_modules/.bin/lb-sdk server/server.js ./angular2App -l angular2 -d ng2web -i enabled
```
where `./angular2App` is an existing directory in my current path. 

```
/mnt/projects/trials/loopback-example-app/node_modules/@mean-expert/loopback-sdk-builder/bin/lb-sdk:106
  if (fs.isEmptySync(context.outputFolder)) {
                            ^

TypeError: Cannot read property 'outputFolder' of undefined
    at verifyPath (/mnt/projects/trials/loopback-example-app/node_modules/@mean-expert/loopback-sdk-builder/bin/lb-sdk:106:29)
    at Object.<anonymous> (/mnt/projects/trials/loopback-example-app/node_modules/@mean-expert/loopback-sdk-builder/bin/lb-sdk:88:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3
```

**Comment by kattsushi** [comment]
@PhilippeCorreges  @anodynos  try with out ./ it is not a relative path

``` bash
./node_modules/.bin/lb-sdk server/server.js angular2App -l angular2 -d ng2web -i enabled
```
here doc :) [https://github.com/mean-expert-official/loopback-sdk-builder/wiki/1.-Install-Builder-&-Build-SDK#generate-angular-2-sdk-for-web-and-progressive-apps](url)

**Comment by PhilippeCorreges** [comment]
Hi @kattsushi 
./node_modules/.bin/lb-sdk server/server.js angular2client/src/app/shared/sdk gives exactly the same result.

**Comment by anodynos** [comment]
Ah, it worked like a charm - thanks! 

PS: I 've just check out the generator, it looks very promising. 

But why `AccessTokenInterface` and not `IAccessToken` and then `StatFilter` instead of `IStatFilter`. I think as `I` in front of an interface of a class makes absolute sense (reminds of java I know, but why not?.

Also `declare var Object: any;`, why? It complains anyway `TS2451: Cannot redeclare block-scoped variable 'Object'.`

**Comment by PhilippeCorreges** [comment]
I am at the root folder of my project and even if I launch: ./node_modules/.bin/lb-sdk server/server.js . I am getting this error: 
`/node_modules/@mean-expert/loopback-sdk-builder/bin/lb-sdk:106
  if (fs.isEmptySync(context.outputFolder)) {
                            ^

TypeError: Cannot read property 'outputFolder' of undefined`

**Comment by PhilippeCorreges** [comment]
Hi @anodynos @kattsushi @jonathan-casarrubias 

I can confirm this issue is coming from loopback-boot. I updated mine to: "loopback-boot": "2.23.0" and everything has come back to normal.

Is it possible to flag this as a bug?

Cheers

**Comment by jonathan-casarrubias** [comment]
@PhilippeCorreges that is strange since the outputFolder is a parameter from the sdk builder, should not be affected by the loopback boot, but maybe there is another mechanism that is affecting that flag.. 

I will add the will verify label

Cheers
Jon

**Comment by PhilippeCorreges** [comment]
@jonathan-casarrubias 

Thanks

**Comment by jonathan-casarrubias** [comment]
@PhilippeCorreges would you  mind to confirm this has been fixed?

**Comment by PhilippeCorreges** [comment]
@jonathan-casarrubias In a new release?
