### ISSUE TITLE
Default to type "any" instead of crashing for method parameters.

### ISSUE THREAD

**Issue by fifafu** [mean-expert-official/loopback-sdk-builder#370]
#### What type of issue are you creating?
- [ X] Bug
- [ ] Question
- [ ] Enhancement

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [X ] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:
If a remote method in Loopback doesn't have a type specified for a remote method parameter, the builder should default to type any. In Loopback the type is not mandatory and currently the builder will crash in the buildMethodParams function because param.type may be undefined.

**Comment by jonathan-casarrubias** [comment]
Ok cool, I received a pull request for adding the types so I believe we all missed the fact that some people may not add the types.

I Will try to add a patch for it asap, also pull requests are always welcome

Cheers
Jon
