### ISSUE TITLE
[TS2.2.x] Operator '!==' cannot be applied to types

### ISSUE THREAD

**Issue by beeman** [mean-expert-official/loopback-sdk-builder#371]
#### What type of issue are you creating?
- [x] Bug

#### What version of this module are you using?
- [x] 2.1.0-rc.8.3

#### Please add a description for your issue:

When running the generated SDK in a project with TypeScript 2.2.1 it results in an error:

```
ERROR in /Users/beeman/workspace/scratch/loopback-scratch/client/src/app/shared/sdk/services/core/search.params.ts (34,42): Operator '!==' cannot be applied to types '"string" | "number" | "boolean" | "symbol" | "undefined" | "object" | "function"' and '"array"'.)
/Users/beeman/workspace/scratch/loopback-scratch/client/src/app/shared/sdk/services/core/search.params.ts (37,50): Operator '===' cannot be applied to types '"string" | "number" | "boolean" | "symbol" | "undefined" | "object" | "function"' and '"array"'.)
```

There is an example project [here](https://github.com/beeman/loopback-scratch).

#### Workaround

Downgrade the Angular app to TypeScript 2.1.6.

**Comment by jmls** [comment]
I think that there's some logic problem in that code anyway ...

```
    private _parseParam(key: string, value: any, parent: string) {
        if (typeof value !== 'object' && typeof value !== 'array') {
            return parent ? parent + '[' + key + ']=' + value
                          : key + '=' + value;
        } else if (typeof value === 'object' ||  typeof value === 'array') {
            return parent ? this._JSON2URL(value, parent + '[' + key + ']')
                          : this._JSON2URL(value, key);
        } else {
            throw new Error('Unexpected Type');
        }
    }
```
so, if the value is *not* an object and *not* an array, hit the first test
if it doesn't pass the first test, then it *must* be an array or object, so the second test is irrelevant - and this makes the last else completely redundant. 

In fact, if there _is_ an unexpected type, it's actually caught by the first test

**Comment by jmls** [comment]
if you replace the `_parseParam` function with this code, the typescript error goes away

```
private _parseParam(key: string, value: any, parent: string) {
        let typeofValue:string = typeof value;

        if (typeofValue !== 'object' && typeofValue !== 'array') {
            return parent ? parent + '[' + key + ']=' + value
                          : key + '=' + value;
        } else {
            return parent ? this._JSON2URL(value, parent + '[' + key + ']')
                          : this._JSON2URL(value, key);
        }
    }
```

**Comment by ferares** [comment]
That works, can you make a pull request, or should I?

**Comment by jonathan-casarrubias** [comment]
I will be integrating this fix as soon as the pull request points to development.

Thanks for reporting and also for fixing the issue.

**Comment by Wavfact** [comment]
This is still an issue in Typescript 2.3.4

Found this bug while researching the error message i was getting after upgrading.
![6-27-2017 2-48-29 pm](https://user-images.githubusercontent.com/587090/27604648-e89b21e2-5b47-11e7-8459-947b6e277302.png)

**Comment by beeman** [comment]
@Wavfact your error seems to come from one of these files, which are not part of the SDK:

`src/app/pipes/MyCurrencyPipe.ts` or `src/app/commercial/directives/numbers-only.directive.ts`

**Comment by Wavfact** [comment]
I downgraded to 2.1.6 as suggested above and the issue was resolved..

In those files, there was a typescript error using typeof <var> !== "String"   Thats why I posted that the issue has not been resolved yet.

**Comment by beeman** [comment]
If the issue is indeed in 
`src/app/pipes/MyCurrencyPipe.ts` and `src/app/commercial/directives/numbers-only.directive.ts` you should just fix those files. No need to downgrade the TypeScript 2.1.6
