### ISSUE TITLE
Getting ZoneAwareError on very simple setup

### ISSUE THREAD

**Issue by anselanza** [mean-expert-official/loopback-sdk-builder#372]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [x] Question

#### What version of this module are you using?
- [x] 2.0.10 (Stable)
- [ ] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

I am just starting out on an app that is making use of the Loopback SDK Builder, for now in a very simple way. I have a Component that imports the following:

```
import { LoopBackConfig } from '../sdk/index';
import { Party } from '../sdk/models/index';
import { PartyApi } from '../sdk/services/index';
```
There is only one model here, Party.

The rest of the Component looks like this:
```
@Component({
  selector: 'home',  // <home></home>
  providers: [],
  templateUrl: './player.component.html'
})
export class PlayerComponent implements OnInit {
  private party: Party = new Party();
  constructor(
    public appState: AppState,
    private partyApi: PartyApi 
  ) {
    LoopBackConfig.setBaseURL('http://localhost:3001/api');
    LoopBackConfig.setApiVersion('api');
    this.getParty(1);
  }

  public ngOnInit() {
    console.log('PlayerComponent');
  }

  getParty(id: any): void {
    this.partyApi.findById(
      id,
      {
        include: ['tracks']
      }
    ).subscribe((party: Party) => {
      console.log('Got Party by ID:', party);
      this.party = party;
    })
  }

}
```
I am using a Webpack setup.

There are no TypeScript errors picked up, and no errors when Webpack does its bundling either. But in the browser, there are quite a few when running the above, all similar to the following:

```
Error
Error: DI Error
    at NoProviderError.ZoneAwareError (http://localhost:3000/polyfills.dll.js:4731:33)
    at NoProviderError.BaseError [as constructor] 
```
... and so on on.

I should add that
- I've checked the paths for the modules and they seem correct, relative to this component
- The error does not show up if the Component only imports (and does nothing else with the Model Class or Service) but immediately shows up when `private partyApi: PartyApi` is included

Any ideas what I might be doing wrong?

**Comment by anselanza** [comment]
Oh, another clue, buried 556 lines into the error messages:

`zone.js:420 Unhandled Promise rejection: No provider for PartyApi! ; Zone: angular ; Task: Promise.then ; Value: NoProviderError {__zone_symbol__error: Error: DI Error`

No provider? But why?

**Comment by jonathan-casarrubias** [comment]
Hi @anselanza, thanks for reaching out..

Hey so, have you installed the SDKModule within the AppModule?

**Comment by anselanza** [comment]
Ah, the magic is working now.

Wow, not sure how I missed that in the Wiki. Thanks for the help!
