### ISSUE TITLE
lb-sdk "app.booting" broken

### ISSUE THREAD

**Issue by speed1speed1** [mean-expert-official/loopback-sdk-builder#375]
If "app.booting" is false.
The "lb-sdk" will call the "verifyPath" function, so "context" variables is undefined.
Maybe you need change the "context" variables position.
Please fix that.
Thanks.

**Comment by jmls** [comment]
I think this is a dupe of #321

**Comment by speed1speed1** [comment]
OK, fine.
I closed this issue.
