### ISSUE TITLE
Loopback-storage-component Error while Geneate Angular2 sdk

### ISSUE THREAD

**Issue by fadyhashmi** [mean-expert-official/loopback-sdk-builder#376]
#### What type of issue are you creating?
- [1 ] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [ 1] 2.1.0-rc.n (2.1 Release Candidate n8.3
![error](
Error: Cannot create data source "storage": Cannot initialize connector "loopback-component-storage": FileSystemProvider: Path does not exist: data
)
)
- [ ] Other

Write other if any:
I am having that issue while generating angular2 sdk id loopback. It shows error on loobabck storage component   

#### Please add a description for your issue:

**Comment by hugoserrana** [comment]
@fadyhashmi Mine is working. I think that error is not Loopback SDK Builder related.
In your datasources.json, the root field of your storage datasource dont exist yet.

Example:
`"storage": {
    "name": "storage",
    "connector": "loopback-component-storage",
    "provider": "filesystem",
    "root": "./image"
  }
`

Create the folder that you set on "root" field in your loopback project and try generate again.
Hope it helps you.

**Comment by fadyhashmi** [comment]
@hugoserrana still not working same error, tried both jsonss 
"storage": {
    "name": "storage",
    "connector": "loopback-component-storage",
    "allowedContentTypes": ["image/jpg", "image/jpeg", "image/png"],
    "provider": "filesystem",
    "root": "./image"
  }
and also tried 
"storage": {
    "name": "storage",
    "connector": "loopback-component-storage",
    "allowedContentTypes": ["image/jpg", "image/jpeg", "image/png"],
    "provider": "filesystem",
    "root": "image"
  }

**Comment by fadyhashmi** [comment]
I solved this issue by using absolute path in
"storage": {
"name": "storage",
"connector": "loopback-component-storage",
"allowedContentTypes": ["image/jpg", "image/jpeg", "image/png"],
"provider": "filesystem",
"root": "absolute path"
}

**Comment by hugoserrana** [comment]
@fadyhashmi Glad to see that it worked. 
Could you close this issue?

**Comment by jonathan-casarrubias** [comment]
Hey @fadyhashmi I'm glad you was able to fix your issue.

@hugoserrana I really appreciate you addressing this issue, I hope to keep seeing you around. So If you would like to be part of the team and help on answering some questions or even contributing in any level you are welcome.

Cheers
Jon
