### ISSUE TITLE
RememberMe not remembered after quitting Ionic 2 app

### ISSUE THREAD

**Issue by BostjanPisler** [mean-expert-official/loopback-sdk-builder#378]
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [x] 2.1.0-rc.8.3 (2.1 Release Candidate 8.3)
- [ ] Other

Write other if any:

#### Please add a description for your issue:
Setting rememberMe to true when logging in doesn't work with Ionic 2 app when running on iOS or Android device. When quitting and opening the app again the user has to re-login.

**Comment by jonathan-casarrubias** [comment]
Have you tried in other environments? anyway I will add the will verify label

Cheers
Jon

**Comment by BostjanPisler** [comment]
I've checked again:

- browser works, 

- Android works, 

- **iOS doesn't work**.

**Comment by jonathan-casarrubias** [comment]
Closing this in favor of #390
