### ISSUE TITLE
Using multiple Loopback Instances in one Angular App

### ISSUE THREAD

**Issue by dmastag** [mean-expert-official/loopback-sdk-builder#379]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [ X ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [ X ] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

I am in need to use multiple Loopback servers. I can't unite them since they both have different purposes and are developed by different teams. Would it be possible to use something like explained [here](http://stackoverflow.com/questions/39610294/import-two-exported-classes-with-the-same-name)

So in my module I would do:

```
import { SDKBrowserModule } from './shared/sdk1/index';
import { SDKBrowserModule as SDK2 } from './shared/sdk2/index';
```

Do you see any problems in doing this?

**Comment by jonathan-casarrubias** [comment]
@dmastag I honestly haven't tried that, if you find out that works it would be great

But, I'm not totally sure it will work in those cases that you have the same model name or service in both SDKs.

This will be a good experimentation project, but the SDK was not tested under this conditions before

**Comment by jonathan-casarrubias** [comment]
I will close this one since it is out of the scope, need to clean up the repo for the next version

**Comment by dmastag** [comment]
No problem, already tried it out and its working as intended.
