### ISSUE TITLE
Proposal: Add to manual

### ISSUE THREAD

**Issue by sirgalleto** [mean-expert-official/loopback-sdk-builder#38]
Actually in my project I have a warning `(node) warning: possible EventEmitter memory leak detected. 11 authentication listeners added. Use emitter.setMaxListeners() to increase limit.`

I thing is good idea add in the manual anything help or instruction for that.

**Comment by jonathan-casarrubias** [comment]
@sirgalleto that is a situation with the datasource juggler from strongloop, it is out of the SDK Builder scope.

I may add a reference for that in the reference for the next version, though.

**Comment by sirgalleto** [comment]
Ok, sounds good. 

Actually do you work with any fix of data juggler?

**Comment by jonathan-casarrubias** [comment]
@sirgalleto not really, but the strongloop team has been working to fix that issue, if you have an old version of the framework you may need to update it at least to version 2.2.0.

Search in google for the exact same error message and you will find lots of info about that issue.

cheers!!
Jon

**Comment by sirgalleto** [comment]
Oh thanks.

**Comment by sirgalleto** [comment]
So, im in 2.22.0. I will look how to fix it

**Comment by jonathan-casarrubias** [comment]
what type of datasoure are you using?

**Comment by sirgalleto** [comment]
MySQL

**Comment by jonathan-casarrubias** [comment]
Yes that was my assumption, I had that issue using sql dbs also when using the auto-migration, for some reason that issue does not appear to be in non-sql dbs

**Comment by sirgalleto** [comment]
My project isnt in production, I can migrate DB without problems.

**Comment by jonathan-casarrubias** [comment]
I would -almost- always recommend to use MongoDB instead of MySQL is much more modern, also MySQL does not have PubSub functionality so, if you would like to turn loopback into a real time API  and your SDK support for real-time applications, I really recommend you to migrate to MongoDB.

Cheers!!
Jon

**Comment by sirgalleto** [comment]
Thanks for the recommendations 👍

**Comment by sirgalleto** [comment]
I love it, congrats!

**Comment by jonathan-casarrubias** [comment]
@sirgalleto you are welcome!!!

Stay around, there is plenty to come..

Cheers!!
Jon

**Comment by sirgalleto** [comment]
Sure
