### ISSUE TITLE
Nativescript socket.io / socketio build fail.

### ISSUE THREAD

**Issue by jaalsh** [mean-expert-official/loopback-sdk-builder#391]
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [x] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [x] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

Firstly, I should point out that there is two very similarly named packages: [nativescript-socket.io](https://www.npmjs.com/package/nativescript-socket.io) and [nativescript-socketio](https://www.npmjs.com/package/nativescript-socketio)

The [documentation](https://github.com/mean-expert-official/loopback-sdk-builder/wiki/2.-Setup-SDK) states that we install the socketio dependency via ```npm install --save nativescript-socketio```. However, I believe this is incorrect and the correct dependency is ```nativescript-socket.io``` according to the ```socket.native.ts``` file generated, which expects to import this.

But if the correct package is ```nativescript-socketio``` then the sdk build isn't working. Changing the import statement in ```socket.native.ts```  to reflect ``nativescript-socketio``` causes errors.

Which package is correct? Both cause issues. If the documentation contains a typo and it's supposed to be `````npm install --save nativescript-socket.io```then other than a quick update to the documentation this issue can safely be ignored.

Many thanks.

**Comment by jonathan-casarrubias** [comment]
@jaalsh thanks for reporting,

Hey so there was a moment when the actual module was without "." but didn't offer the right support for iOS... so I changed that to the one including "."

I'll update the docs, to reflect the right module.

Cheers
Jon
