### ISSUE TITLE
sdk-builder not generating most of the custom services' functions

### ISSUE THREAD

**Issue by Jonibigoud** [mean-expert-official/loopback-sdk-builder#392]
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [x] 2.1.0-rc.9 
- [ ] Other

Write other if any:

#### Please add a description for your issue:

Hi,
I'm facing a problem since the first pre-release of version 2.1.0:

Only a few of the functions in most of my custom services are generated:

- patchOrCreate()

- patchAttributes()

- getModelName()

Here are my dependencies:

  "dependencies": {
    "compression": "^1.0.3",
    "cors": "^2.5.2",
    "helmet": "^1.3.0",
    "loopback": "^3.6.0",
    "loopback-boot": "^2.23.0",
    "loopback-component-explorer": "^4.2.0",
    "loopback-connector-mongodb": "^3.0.1",
    "serve-favicon": "^2.0.1",
    "strong-error-handler": "^1.0.1"
  },
  "devDependencies": {
    "@mean-expert/loopback-sdk-builder": "^2.1.0-rc.9",
    "eslint": "^2.13.1",
    "eslint-config-loopback": "^4.0.0",
    "nsp": "^2.1.0"
  }

Do you think it is a bug?

**Comment by Jonibigoud** [comment]
Only models based on "PersistedModel" are impacted.
my model based on "User" and my model based on "Role" seem ok.

Any idea?

**Comment by jonathan-casarrubias** [comment]
@Jonibigoud it sounds to  me that you are using the fireloop-only flag as enabled, that one won't create the ServicesApi files but the ones related to authentication.

I remember this option is by default disabled, so just make sure it is also for you.

**Comment by Jonibigoud** [comment]
Hi @jonathan-casarrubias,
thanks for your reply and for your precious time spent on this sdk.
I'm using this script to generate the code:

`    "build:sdk": "./node_modules/.bin/lb-sdk ./server/server.js ./client/WebPdpg/src/app/Shared/sdk -i disabled"
`
i tried this with fireloop flag set to disabled: 
`"build:sdk": "./node_modules/.bin/lb-sdk ./server/server.js ./client/WebPdpg/src/app/Shared/sdk -l angular2 -d ng2web -i disabled -f disabled"`

But still same error.

This solution with the 2.1.0-rc.9 version:
`    "build:sdk": "./node_modules/.bin/lb-sdk ./server/server.js ./client/WebPdpg/src/app/Shared/sdk"
`
outputs this error:

`npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:sdk"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! test@1.0.0 build:sdk: `lb-sdk ./server/server.js ./client/WebPdpg/src/app/Shared/sdk`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@1.0.0 build:sdk script 'lb-sdk ./server/server.js ./client/WebPdpg/src/app/Shared/sdk'.`

The thing is that if i keep the 2.0.10 version i always need to modify the generated code because of some errors like deduplication of "options" param in some functions...that s why i would be interested in moving to a version that fixes thoses bugs.
If you have any idea...

**Comment by Jonibigoud** [comment]
Still struggling with that problem...tried with many versions, still same problem.
I'm stuck, if anybody has a clue i would be very thankful...

**Comment by Destreyf** [comment]
@Jonibigoud Its extremely difficult to troubleshoot something like this, is there a sample repo that i could look at that has this issue?  Have you made sure that your models are public?  I am running the SDK Builder with over 100 models and have had no trouble generating the Rest side of the services.

**Comment by Jonibigoud** [comment]
hi i'm back with a sample repo generated with node 6.9 lts:

https://github.com/Jonibigoud/apitest

You will see that i created two models, "Gestionnaire", a persisted model with no properties, and "Utilisateur", a model based on "User" root model.
The sdk is in ./client/Shared folder.

I hope you will be able to help me because i've tried many things without success.

**Comment by Jonibigoud** [comment]
Hi, @Destreyf and @jonathan-casarrubias , i'm still struggling with that.
If you have a few minutes to look at my sample repo i would be very thankful as i'm still struggling with that problem.
I tried on a linux distro, on a windows 7, from node v6.9 to 7.9, with npm v3.10.10...no clue.

**Comment by jonathan-casarrubias** [comment]
@Jonibigoud I have reviewed your repo, and I see everything is being generated as expected, I think you are confused about how things works.

The gestionnaire model does not have any custom remote method, nor any relationship... That is why you get generated only a couple of methods inside, the rest of the CRUD methods are extended from the BaseAPI Class, which will provide a lot of other methods.

the Utilisateur is also correclty generated since it does extend from user, it provides the user specific methods, but the rest of the CRUDS are extended from the BaseAPI.

if you want to know the entire list of methods provided by the BaseAPI you can either explore that file or by using intellisense.

I'm closing this issue since is not a real bug.

Regards

**Comment by Jonibigoud** [comment]
Ok, but  all methods are generated with sdk builder v2.0.10 (finf, finOne, findById,...)

**Comment by Jonibigoud** [comment]
Maybe you can tell me what I'm missing here.:
Here is same sample repository but with sdk builder v2.0.10,  all basic methods are automatically generated  (find, findOne, findById, replaceById...)

Regards

**Comment by Destreyf** [comment]
@Jonibigoud i think the misunderstanding you're having here, is in older versions of the SDK builder, each model had every method generated on every file, now they all extend `BaseLoopBackApi` which contains the general CRUD (find, findOne, findById, ect) methods, these are no longer generated per model, so you need to make sure that you have the whole SDK Output (see `services/core/base.service.ts` for the methods) you can still call the methods on the service files (`services/custom/XYZ.ts`) as they directly extend the `BaseLoopBackApi` class which contains all the logic for the default methods.

**Comment by Destreyf** [comment]
The other thing to note, is that when you run the sdk builder, if you don't provide the -w flag, it expects you to manually clear the previous output, i am unsure if this was a changed behavior or not as i started using it with the 2.1.0 release.

**Comment by jonathan-casarrubias** [comment]
@Jonibigoud as @Destreyf is stating, all of these methods you believe are missing, are now actually part of the BaseLoopBackApi service and your custom services extend from that other class, which provides you with the functionality you think is missing.

I hope all of this helps you clarify the issue

Regards
jon

**Comment by Jonibigoud** [comment]
Wow Thank you for the explanation. Sorry for the time you spent helping me!

Best regards!
