### ISSUE TITLE
parameter not generated

### ISSUE THREAD

**Issue by jmls** [mean-expert-official/loopback-sdk-builder#399]
#### What type of issue are you creating?
- [X] Bug

#### What version of this module are you using?
- [x] 2.1.0-rc.9 (2.1 Release Candidate 9)

#### Please add a description for your issue:
some parameters are not generated. This json definition
```json
RtbSession.remoteMethod('login', {
        description: 'log in',
        accepts: [
            { arg: 'userId', type: 'string' },
            { arg: 'password', type: 'string' },
            { arg: 'source', type: 'string' }
        ],
        returns: { arg: 'data', type: 'object', root: true },
        http: { path: '/login', verb: 'post' }
    });
    RtbSession.remoteMethod('logout', {
        description: 'logout',
        accepts: [
            { arg: 'userId', type: 'string' }
        ],
        returns: { arg: 'data', type: 'object', root: true },
        http: { path: '/logout', verb: 'post' }
    });
```

generates this code
```typescript
/**
   * log in
   *
   * @param {object} data Request data.
   *
   *  - `userId` – `{string}` - 
   *
   *  - `password` – `{string}` - 
   *
   *  - `source` – `{string}` - 
   *
   * @returns {object} An empty reference that will be
   *   populated with the actual data once the response is returned
   *   from the server.
   *
   * <em>
   * (The remote method definition does not provide any description.
   * This usually means the response is a `RtbSession` object.)
   * </em>
   */
  public login(userId: any = {}, password: any = {}, source: any = {}, rememberMe: boolean = true): Observable<any> {
    let _method: string = "POST";
    let _url: string = LoopBackConfig.getPath() + "/" + LoopBackConfig.getApiVersion() +
    "/RtbSession/login";
    let _routeParams: any = {};
    let _postBody: any = {};
    let _urlParams: any = {};
    if (userId) _urlParams.userId = userId;
    if (password) _urlParams.password = password;
    if (source) _urlParams.source = source;
    let result = this.request(_method, _url, _routeParams, _urlParams, _postBody);
    return result;
  }

  /**
   * logout
   *
   * @param {object} data Request data.
   *
   *  - `userId` – `{string}` - 
   *
   * @returns {object} An empty reference that will be
   *   populated with the actual data once the response is returned
   *   from the server.
   *
   * <em>
   * (The remote method definition does not provide any description.
   * This usually means the response is a `RtbSession` object.)
   * </em>
   */
  public logout(): Observable<any> {
    let _method: string = "POST";
    let _url: string = LoopBackConfig.getPath() + "/" + LoopBackConfig.getApiVersion() +
    "/RtbSession/logout";
    let _routeParams: any = {};
    let _postBody: any = {};
    let _urlParams: any = {};
    if (userId) _urlParams.userId = userId;
    let result = this.request(_method, _url, _routeParams, _urlParams, _postBody);
    return result;
  }
```
Notice that both login and logout have 
```
* @param {object} data Request data.
   *
   *  - `userId` – `{string}` - 
```
defined, login has 

`public login(userId: any = {}, password: any = {}, source: any = {}, rememberMe: boolean = true): `

but logout has

` public logout():`

**Comment by jonathan-casarrubias** [comment]
@jmls neither the login or logout are auto-generated, this is because the SDK require custom logic that won't be provided by LoopBack, therefore whatever you define in your custom login / logout, won't be the final.

I honestly don't think that having a custom login -mainly- and logout will work with the SDK right away, the results would be unexpected and there is no way to tell the SDK how to behave on your custom access methods.

Therefore, I don't consider this as a bug but as a new feature request, to accept custom login/logout methods not provided by LoopBack of course.

**Comment by jmls** [comment]
I disagree. the login / logout methods are on a non-user model, and the loopback explorer api works just fine with them

also, the preceeding comments on the `logout` methods specify
```
   * @param {object} data Request data.
   *  - `userId` – `{string}` - 
```
so they are being picked up somewhere

I *think* what you are saying is that these remote methods conflict with the *sdk*'s expectation of what login / logout are - That's the sdk's problem, not mine ;)

As far as I am concerned, `login` and `logout` on a pure `Model` are simply remote methods.

**Comment by jmls** [comment]
Actually, what you mentioned also doesn't explain why the sdk generated the `login` parameters correctly
```
public login(userId: any = {}, password: any = {}, source: any = {}, rememberMe: boolean = true): Observable<any> {
 ```

notice that there not only is userId and password, but also the `source` parameter. That is a very custom parameter , so the sdk picked that up just fine

**Comment by jonathan-casarrubias** [comment]
Well that is different, I was assuming you were replacing login/logout from a User based model, in that case we would not do anything about it...

As custom remote method in non-user based model, it should work... 

For instance, at least within the service template the validations always are:

````js
if (model.isUser && methodName === 'login')
````

Then now I can consider this as a bug, since it seems there is a part of the generator not considering the isUser property from the model.

I'll verify the JS file  that generates and seek for validations missing the model.isUser property.

**Comment by jmls** [comment]
```
{
  "name": "RtbSession",
  "plural": "RtbSession",
  "base": "Model",
  "properties": {},
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```
