### ISSUE TITLE
accessToken is not set in XxxApi services

### ISSUE THREAD

**Issue by emsedano** [mean-expert-official/loopback-sdk-builder#400]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [x] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [ ] 2.1.0-rc.n (2.1 Release Candidate n)
- [x] Other

Write other if any: 2.1.0-rc.9

#### Please add a description for your issue:
I'm ussing passport login approach, I did what you mention in your github page
**server side** => 
redirect to /passport/:id/:userId
``` javascript
function(request, response) {
      const provider = request.params.provider;
      const redirectUrl = `/#/passport/${request.accessToken.id}/${request.accessToken.userId}`;
      if (this.hasValidUser(request)) {
        response.cookie('accessToken', request.signedCookies.access_token, {
          signed: true,
          maxAge: COOKIE_MAX_AGE
        });
        response.redirect(redirectUrl);
      } else {
        request.session.destroy(function() {
          response.redirect(config[`openidconnect-${provider}`].failureRedirect);
        });
      }
```
**angular2 side =>**
I added a routing to handle this redirection and save the token id and the user id, and finally redirecto to the actual homepage which redirects to a page with a list of a model called Request
the routing module contains:
```javascript
const routes: Routes = [
  ...
  {
    path: 'passport/:id/:userId',
    component: PassportComponent,
    pathMatch: 'full'
  },
...
```
the PassportComponent
```typescript
import { Component } from '@angular/core';

import {ActivatedRoute, Router} from "@angular/router";
import {LoopBackAuth} from "../services/api/services/core/auth.service";
import {SDKToken} from "../services/api/models/BaseModels";

@Component({
  selector: 'sp-passport',
  templateUrl: './passport.component.html',
  styleUrls: ['./passport.component.scss']
})
export class PassportComponent {

  constructor(
      private auth: LoopBackAuth,
      private route: ActivatedRoute,
      private router: Router
  ) {
    this.route.params.subscribe((token: SDKToken) => {
      console.log(`token => ${token}`);
      if (token.id && token.userId) {
        this.auth.setToken(token);
        this.auth.setRememberMe(true);
        this.auth.save();
        this.router.navigate(['/']);
      }
    });
  }

}
```
the service using sdk builder
``` typescript
import { Injectable } from '@angular/core';
import { Observable, Subject } from 'rxjs/Rx';
import { Request } from '../models/request';
import {RequestApi} from "../../common/services/api/services/custom/Request";
import {LoopBackAuth} from "../../common/services/api/services/core/auth.service";

@Injectable()
export class InboxService {
  constructor(private auth: LoopBackAuth, private _requestApi: RequestApi) {
  }
  public getRequests(): Observable<Request[]> {
    return this._requestApi.find();
  }
}

```

and after calling this the IncomeMessage value in server side comes with accessToken empty, and ACL cannot resolve the the user
this is what is inside AccessToken object when the execution arrives to RoleResolver
```
{"id":"$anonymous","ttl":1209600,"created":"2017-04-07T13:29:07.277Z"}
```
but the current user id and userid values present and instead arrives as $anonymous

any thougths ?

**Comment by jonathan-casarrubias** [comment]
@emsedano thanks for reporting,

Hey so... Would you mind to confirm that the token is locally persisted either in cache or cookies depending on your configurations.

For that you need to go to the developer tools from a browser you use, then verify if there are credentials stored in cookies or local storage.

I also see you have a console log for the token, is that being correctly logged into the console?

**Comment by emsedano** [comment]
I can see inside LoopBackAuth (`xxxApi.auth.storage.cookies`) of the xxxApi service the values for token id and userid are present, BUT the` xxApi.auth.token` is empty... I put a breakpoint to the constructor of LoopBackAuth and the values there seems to be assigned correctly...

**Comment by emsedano** [comment]
also if I do this
```javascript
  _requestApi['auth'].getToken().id = _requestApi['auth']['storage'].get(`${auth['prefix']}id`);
  _requestApi['auth'].getToken().userId =  _requestApi['auth']['storage'].get(`${auth['prefix']}userId`);
```
I used ['key'] because `auth` is protected in TS, and by doing this I can see accessToken present in loopback server side correctly attached to the request and RoleResolver works fine... the problem is that I guess this is not correct way to do

**Comment by jonathan-casarrubias** [comment]
yes basically you are loading the data from the internal storage.... That would be equivalent to

````js
 constructor(private _requestApi: RequestApi) {
  _requestApi['auth'].getToken().id = _requestApi['auth'].load('id');
  _requestApi['auth'].getToken().userId = _requestApi['auth'].load('userId');
}
````

The problem though, is that is being already done within the constructor of auth service

````js
  constructor(@Inject(InternalStorage) protected storage: InternalStorage) {
    this.token.id         = this.load('id');
    this.token.user       = this.load('user');
    this.token.userId     = this.load('userId');
    this.token.issuedAt   = this.load('issuedAt');
    this.token.created    = this.load('created');
    this.token.ttl        = this.load('ttl');
    this.token.rememberMe = this.load('rememberMe');
  }
````

So you shouldn't need to manually do that, I'm trying to figure out why is not being loaded while constructing the service

**Comment by emsedano** [comment]
btw I'm using 
angular 4.0.1 
loopback 3
chrome as browser

**Comment by jonathan-casarrubias** [comment]
@emsedano I have been unable to replicate this issue, also I don't see any other developer reporting the same problem.

Since I'm cleaning the repo, I need to close this issue for being un-replicable and inactive.

Regards

**Comment by mraquino007** [comment]
@emsedano have you tried it in firefox? I have this problem in Chrome and Safari
