### ISSUE TITLE
Type based on user in loopback (Cannot find name 'id')

### ISSUE THREAD

**Issue by hanseilers** [mean-expert-official/loopback-sdk-builder#401]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [ x] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [x ] 2.1.0-rc.9 (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

Hi, I get this error on a member type I based on User. I didn't add anything special to the  member object: 

> {
  "name": "member",
  "plural": "members",
  "base": "User",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {},
  "validations": [],
  "relations": {
    "projects": {
      "type": "hasMany",
      "model": "project",
      "foreignKey": "ownerId"
    },
    "fundedProjects": {
      "type": "hasMany",
      "model": "project",
      "foreignKey": "projectId",
      "through": "projectFunding"
    },
    "supportedProjects": {
      "type": "hasMany",
      "model": "project",
      "foreignKey": "projectId",
      "through": "projectSupporter"
    }
  },
  "acls": [],
  "methods": {}
}

The error I get on ng serve is: 

ERROR in /home/ubuntu/workspace/client/src/app/shared/sdk/services/custom/Member.ts (1059,11): Cannot find name 'id'.

[Member.ts.txt](https://github.com/mean-expert-official/loopback-sdk-builder/files/905843/Member.ts.txt)

**Comment by request-eduardo** [comment]
I am getting the exact same error. I can only manage to run it by changing "noEmitOnError": true to false in my compilerOptions in the tsconfig.json file. But even so, I can't do any request to the api using the services... all of them are returning "Server error". I am working on a Nativescript SDK and have already reported the "Server error" issue as #398

**Comment by jonathan-casarrubias** [comment]
@hanseilers thanks for reporting,

Hey so... I'm verifying and I'm unable to see a changePassword method created in the test environment.

What version of LoopBack are you using? the test environment is running the versions below

````json
{
    "loopback": "^3.2.1",
    "loopback-boot": "^2.6.5",
    "loopback-datasource-juggler": "^2.39.0"
}
````

In order to fix this issue first I  need to have access to the same method, otherwise I would not be able to verify why is not correctly generated.

Regards.

**Comment by hanseilers** [comment]
Hi Jonathan, 

Using: 

> "dependencies": {
    "@mean-expert/loopback-component-realtime": "^1.0.0-rc.4",
    "@mean-expert/loopback-sdk-builder": "^2.1.0-rc.9",
    "compression": "^1.0.3",
    "cors": "^2.5.2",
    "helmet": "^1.3.0",
    "loopback": "^3.2.1",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^4.0.0",
    "serve-favicon": "^2.0.1",
    "strong-error-handler": "^2.0.0"
  },

I can send entire project it that helps...

Cheers, 
Hans

**Comment by Sturgelose** [comment]
Having exactly the same issue, with the User model:

```
public changePassword(oldPassword: any, newPassword: any): Observable<any> {
    let _method: string = "POST";
    let _url: string = LoopBackConfig.getPath() + "/" + LoopBackConfig.getApiVersion() +
    "/Users/change-password";
    let _routeParams: any = {
      id: id
    };
    let _postBody: any = {};
    let _urlParams: any = {};
    if (oldPassword) _urlParams.oldPassword = oldPassword;
    if (newPassword) _urlParams.newPassword = newPassword;
    let result = this.request(_method, _url, _routeParams, _urlParams, _postBody);
    return result;
  }
```
I'm using the default User model configuration, though.

Id in line 6, throws the same error as indicated before. I updated to the latest version of Loopback and all the other modules:

```
"cors": "^2.5.2",
    "eslint": "^3.19.0",
    "helmet": "^3.5.0",
    "lodash": "^4.17.4",
    "loopback": "^3.0.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^4.0.0",
    "loopback-connector-es": "1.3.5",
    "loopback-connector-mongodb": "^3.0.0",
    "loopback-nodejs-client": "^1.0.1",
```

**Comment by thijsvanbuuren** [comment]
Hi,

I have the same situation, the changePassword was never generated in my project before but now it does. 

A workaround for me if your not using that method yet in your YourModel.js:

    YourModel.disableRemoteMethodByName('changePassword');

**Comment by fabianscheidt** [comment]
I found a solution for this issue: The changePassword-method finds the user-id with a custom http-mapping function. The SDK still includes the attribute just because the arg-name is 'id', which it should not. I made a pull-request with a fix.

**Comment by hanseilers** [comment]
Great that it's solved. 
I'm kinda newish to this. In npm I can only use the previous version and not this latest version *.10. 
Is there something different I should to other than updating my package.json and npm install?

**Comment by fabianscheidt** [comment]
You could check out the development-branch using npm by putting "https://github.com/mean-expert-official/loopback-sdk-builder.git#development" in the dependencies instead of the version number until Jonathan releases 2.1.0-rc.10. I haven't tested it but this should work.

**Comment by jonathan-casarrubias** [comment]
hey guys I published the new release a couple of hours ago, now you should be able to get it from the NPM repository..

Cheers
Jon

**Comment by hanseilers** [comment]
Yes, got it. Thanks!
