### ISSUE TITLE
"include=user" ignored during Login once upgraded to Angular 4

### ISSUE THREAD

**Issue by pierfreeman** [mean-expert-official/loopback-sdk-builder#404]
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [x] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

When upgrading to Angular 4, when creating a new HTTP request with base.service.ts, searchParams are not attached to the url despite being set. 

Specifically, during login with customerApi (which is the service of a sub-model of User) the 'include=user' search param is ignored (while it is set by default), resulting in the absence of the user object in the token response object.

**Comment by Eslem** [comment]
The temporary fix i made is to add "?include=user" at the end of the url in the login method of your model service. I couldn't find the error of the include..
`let _url: string = LoopBackConfig.getPath() + "/" + LoopBackConfig.getApiVersion() +
      "/Mode/login?include=user";
`

**Comment by Destreyf** [comment]
@pierfreeman @Eslem Which RC of the SDK Builder (and Version) are you using, there was a fix implemented in 2.1.0-RC.9 specifically to fix the change to search params made in angular 4, and i have been using it with no trouble.

**Comment by Eslem** [comment]
I updated and now works, thanks.

**Comment by jonathan-casarrubias** [comment]
Cool!! I'm glad the update worked for you... I'm closing this now
