### ISSUE TITLE
Authenticated Requests with multiple instances of SDK

### ISSUE THREAD

**Issue by RicardoVaranda** [mean-expert-official/loopback-sdk-builder#408]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [X] Question

#### What version of this module are you using?
- [X] 2.0.10 (Stable)
- [ ] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

Hey guys, first of all thank you a lot for all of the work put in this project, I only recently started adapting it but the benefits are already outweighing the initial downside of having to refactor everything. 

In our current set up we have multiple instances of the sdk generated on a single angular application, they all share the same authentication (token based). 

What is the correct way to make authenticated requests on multiple instances of the sdk with the same access token?

 😇

**Comment by jonathan-casarrubias** [comment]
@RicardoVaranda thanks for reaching out,

Hey so I have not experience using different instances of the SDK, actually it was not designed for that... Though I have heard from others devs doing it, so I know is possible....

I'll keep your issue open for a while to see if someone else have experience on this use case...

Cheers
Jon
