### ISSUE TITLE
Possible issue in loopback-sdk-builder/lib/angular2/index.js

### ISSUE THREAD

**Issue by mnapoli76** [mean-expert-official/loopback-sdk-builder#411]
#### What type of issue are you creating?
- [X] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [X] 2.1.0-rc.10 (2.1 Release Candidate 10)
- [ ] Other

Write other if any:

#### Please add a description for your issue:
Maybe I'm wrong, but following this line of code:

https://github.com/mean-expert-official/loopback-sdk-builder/blob/master/lib/angular2/index.js#L855

the parameter to the isArray() function should be 'property.type' and not just 'type'.

Regards,
Mauro

**Comment by jonathan-casarrubias** [comment]
Hi @mnapoli76 thanks for reporting but there is already an issue for this problem, I'll close this one in favor of https://github.com/mean-expert-official/loopback-sdk-builder/issues/410
