### ISSUE TITLE
Type 'SDKToken' is not assignable to type 'AccessToken'

### ISSUE THREAD

**Issue by Paulillo16** [mean-expert-official/loopback-sdk-builder#414]
#### What type of issue are you creating?
- [ X] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [ X] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:
   loopback@3.7.0

#### Please add a description for your issue:
This is error:
ERROR in C:/cygwin64/www/my_app/src/app/shared/sdk/services/custom/Usuario.ts (1745,5): Type 'SDKToken' is not assignable to type 'AccessToken'.
  Property '"scopes"' is missing in type 'SDKToken'.

Usuario.ts
```
1738.  /**
1739.   * Get data of the currently logged access tokern that was returned by the last
1740.   * call to {@link sdk.Usuario#login}
1741.   *
1742.   * @returns object An AccessToken instance.
1743.   */
1744.  public getCurrentToken(): AccessToken {
1745.    return this.auth.getToken();
1746.  }
```

../shared/sdk/services/core/auth.service.ts:
```
  /**
   * @method getToken
   * @return {void}
   * @description
   * This method will set a flag in order to remember the current credentials.
   **/
  public getToken(): SDKToken {
    return <SDKToken> this.token;
  }
```

../shared/sdk/models/BaseModels.ts:
```
  export class SDKToken implements AccessTokenInterface {
    id: any = null;
    ttl: number = null;
    scopes: Array<any> = null; // #######==>>>>> I added this line to solve the problem
    issuedAt: any = null;
    created: any = null;
    userId: any = null;
    user: any = null;
    rememberMe: boolean = null;
    constructor(data?: AccessTokenInterface) {
        Object.assign(this, data);
    }
  }
```

../shared/sdk/models/AccessToken.ts:
```
   export interface AccessTokenInterface {
    "id"?: string;
    "ttl"?: number;
    "scopes"?: Array<any>;
    "created"?: Date;
    "userId"?: any;
     user?: any;
   }

```

**Comment by jonathan-casarrubias** [comment]
@Paulillo16 thanks for reporting,

Is this scopes property part of the built in AccessToken functionality? is a new implementation? or that is something custom you added to the model....

I have never seen the scopes property within the AccessToken model, so if it is a new loopback implementation we might want to add that

**Comment by Paulillo16** [comment]
I think it should be a new Loopback functionality built into AccesToken.
I'm sure it isn't a functionality developed by me.

**Comment by jonathan-casarrubias** [comment]
@Paulillo16  That is fair enough, if you are sure is not yours then I can assume is a new LB functionality, I'll address that scopes property as part of the following release.

Cheers
Jon

**Comment by Destreyf** [comment]
@jonathan-casarrubias @Paulillo16 I can confirm that scopes is a property from loopback's own AccessToken, you can see the code here: https://github.com/strongloop/loopback/blob/master/common/models/access-token.json

These scopes appear to be used when dealing with oAuth to indicate which scopes were obtained.

**Comment by toniopelo** [comment]
Same problem here! +1

**Comment by csotomon** [comment]
In this moment, does exist a solution for this?
