### ISSUE TITLE
Socket Error 400 when accessing Remote Server

### ISSUE THREAD

**Issue by denzelwamburu** [mean-expert-official/loopback-sdk-builder#415]
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [x] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

I've Hosted the server on a nginx but when i try to connect to it from my app, it returns a 400 error.  Is there any extra config i should add or any ideas on the work around?

**Comment by jonathan-casarrubias** [comment]
Are you serving to multiple server instances? in other words do you have more than 1 instance of the API running?

**Comment by denzelwamburu** [comment]
No. I haven't clustered anything. It's just on a remote host with Nginx. Is
there any extra configs?

**Comment by jonathan-casarrubias** [comment]
ok then it might be that you got the latests real-time component version but you haven't update the SDK...

Try updating both the loopback-component-realtime and the loopback-sdk-builder, generate a new SDK and I believe your issue should be gone.

**Comment by jonathan-casarrubias** [comment]
Any update on this?

**Comment by denzelwamburu** [comment]
Nothing.
Still brings the erro. This only brings the error running in production.
![screen shot 2017-05-05 at 5 30 51 pm](https://cloud.githubusercontent.com/assets/6532631/25749900/ba0398c2-31b8-11e7-9eb2-036abb779322.png)

**Comment by jonathan-casarrubias** [comment]
I don't think you have the latests versions, I can tell because your app is still trying to connect using long polling as transport.

Update the `loopback-component-realtime`, `loopback-sdk-builder` and create a new SDK with the latests changes, and your problem will be gone.

Cheers
Jon

**Comment by denzelwamburu** [comment]
Give me two hours to get home and install it.

**Comment by denzelwamburu** [comment]
Hey @jonathan-casarrubias,
Updated it and run into an error.

**Comment by bitingedgemick** [comment]
Hi @denzelwamburu 

You need to add the driver option to the component-config.json file.

`  "@mean-expert/loopback-component-realtime": {
    "auth": true,
    "debug": false,
    "driver": {
      "name": "socket.io"
    }
  }`

**Comment by denzelwamburu** [comment]
My bad, didn't see it in the docs.
Let me add it.
Thanks.

**Comment by denzelwamburu** [comment]
It worked. 💪🏿 
Should have closed this earlier.
