### ISSUE TITLE
Wipe to only clear relevant generated SDKs files instead of nuking

### ISSUE THREAD

**Issue by Sturgelose** [mean-expert-official/loopback-sdk-builder#421]
#### What type of issue are you creating?
- [ ] Bug
- [X] Enhancement
- [ ] Question

#### What version of this module are you using?
- [X] 2.0.10 (Stable)
- [ ] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

We are trying to create via CI a new client after each tagged/released version of our LoopbackJS API. Your client generator is amazing, but, the way it behaves it makes it hard to user this client as a library.

We are trying to push it to its own git repository and call it either via NPM or even using git submodules (either way is easier). However, the way your CLI wipes the folder, it deletes ALL files and folders, not even leaving there the .git folder, which really harms any custom files or settings you have added around there (and there is no way to do a diff, because you just nuked the folder with git included...).

Could there be a way that you deleted just the relevant folders? For example, just deleting the models, services, storage and sockets folders + index.ts and lb.config.ts (maybe this last one as optional). This would allow to keep a repository with the client library and allow our customers to be able to update their implementations from our repo.

I know we could do this by hand, but well, we are trying to implement CI, and well, as we are all IT people and love to automatize/be lazy, this would help a lot :)

Thanks a lot!

**Comment by jonathan-casarrubias** [comment]
Closing this in favor of https://github.com/mean-expert-official/loopback-sdk-builder/issues/472
