### ISSUE TITLE
* [bug] the filter can not work if string is utf-8 chars for v2.1.0-rc.6 above.

### ISSUE THREAD

**Issue by snowyu** [mean-expert-official/loopback-sdk-builder#423]
#### What type of issue are you creating?
- [X] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [X] 2.1.0-rc.6 and above
- [ ] Other

#### Please add a description for your issue:

Set 'filter' parameter to HTTP headers"  #151 , but the HTTP headers can not support non-ascii chars!!

eg, 

```json
{"where":{"id":"你"}}
```

**Comment by snowyu** [comment]
The #418  in the same issue.

**Comment by jonathan-casarrubias** [comment]
Closing in favor of #418
