### ISSUE TITLE
Unexpected token: name (SDKToken)

### ISSUE THREAD

**Issue by gsyjdcg** [mean-expert-official/loopback-sdk-builder#424]
#### What type of issue are you creating?
- [x ] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [x] 2.1.0-rc.10.2 (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

When executing "ng build --prod" to obtain an angular project for production the following error appears in the terminal:

**ERROR in main.e07b3961a5e0052c142b.bundle.js from UglifyJs
Unexpected token: name (SDKToken) [main.e07b3961a5e0052c142b.bundle.js:11,6]**

When it reaches 92% and it is doing "chunk asset optimization" it stops and the error appears.

At this time it is not possible to pass a project using the @ mean-expert/loopback-sdk-builder

Any solution ?. Thank you.

**Comment by jonathan-casarrubias** [comment]
Hi @gsyjdcg I have just verified with the latest version and did ng build --prod without any issues, would you mind to try with the last version?

**Comment by gsyjdcg** [comment]
Thanks @ jonathan-casarrubias,

The above error is no longer reproduced. Although I now get a new error message when I run the ng build --prod command:

ERROR in main.e4b1eb3e8ffd75b7fec5.bundle.js from UglifyJs
Unexpected token: keyword (const) [main.e4b1eb3e8ffd75b7fec5.bundle.js:53,9]

**Comment by gsyjdcg** [comment]
I have already solved,
I have modified the tsconfig.json file and everything works correctly. Thanks again.

{
  "compilerOptions": {
    "baseUrl": "",
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [**"es5", "es2015"**, "dom"],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": **"es5"**,
    "typeRoots": [
        "node_modules/@types"
      ],
    "types": [
         "node"
      ]
  },
  "exclude": [ "test.ts" ],
  "angularCompilerOptions": { "genDir": "i18n" }
}

**Comment by jonathan-casarrubias** [comment]
Wonderful, I'm glad you made it work, I'm closing this and changing the issue title for future reference
