### ISSUE TITLE
Question: How to handle "authenticated = true"?

### ISSUE THREAD

**Issue by PhilippeCorreges** [mean-expert-official/loopback-sdk-builder#425]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [x] Question

#### What version of this module are you using?
- [x] 2.0.10 (Stable)
- [ ] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:
Hello,
I am wondering if someone has a sample on how to handle the fact the a user is authenticated or not. Everything works fine, login, logout ... But I just would like to hide some menus if the user is not authenticated.

Many thanks and Kind Regards

**Comment by jonathan-casarrubias** [comment]
@PhilippeCorreges thanks for reaching out,

Hey so... every model that extends from user provides you with a `Model.isAuthenticated()` method. You can use it to know if a user is authenticated or not

https://github.com/mean-expert-official/loopback-sdk-builder/blob/master/tests/ng2web/src/app/shared/sdk/services/custom/Account.ts#L1249

**Comment by PhilippeCorreges** [comment]
Thanks

**Comment by fiftoine** [comment]
Hello,
Thanks for the info but how would you observe the authentication to bind the visibility of an element in a template?

Sort of : 
`<div *ngIf="...isAuthenticated">...</div>`

Thanks

**Comment by MROALI** [comment]
how to verify is the session is expired. Other saying the isAuthenticated returns always true even if the accesstoken is expired ??

**Comment by PhilippeCorreges** [comment]
Hi @MROALI 
No idea. I am still looking at it. Any info from your side ?

**Comment by PhilippeCorreges** [comment]
just tried : 
`<button mat-button (click)="logout()" *ngIf="isAuthenticated() | async">{{ 'LOGOUT' | translate }}</button>`

In Vain

**Comment by PhilippeCorreges** [comment]
Hello.
Has anyone an update? I am really stuck here.

Thanks and Regard
