### ISSUE TITLE
non-default path in default method craps out

### ISSUE THREAD

**Issue by jmls** [mean-expert-official/loopback-sdk-builder#427]
#### What type of issue are you creating?
- [X] Bug

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [X] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

if a standard method like `find()` has a path other than `/` then the generated class does not make the correct rest call. 

For example, I have a model called `Person` with a remote method oncalled `find` which has a path of `/users` 

when I try to call `Person.find()` I get the error `GET https://myapp/api/People 404 (Not Found)`

when trying the same call from explorer, the api works just fine

I am guessing that if you find a method called `find` then you simply default to the method defined in `base.service.ts` - however, that will not work for paths other that `/`

**Comment by jonathan-casarrubias** [comment]
@jmls the PersistedModel Methods are not generated from configurations, it was originally doing that but the SDK size was too big there was many complains about the amount of duplicated code.

For that reason we decided to keep all the persisted model methods in the base class and then extend all the other services from there, which drastically reduced the SDK size / duplicated code.

Being honest I don't see this going back to generate all the persisted model methods, if it is important for you, then you might want to go back to version 1.

**Comment by jmls** [comment]
You don't need to duplicate code - if there is a custom path for the persistent model method, add it as a property. Then, in the base , If that property exists,  use that path instead of the default for the method. The *only* code that would be added is a custom property if that model has custom paths ...

**Comment by jonathan-casarrubias** [comment]
@jmls that is a viable solution, would you send a pull request for that enhancement? If so I can open this issue again for PR reference.
