### ISSUE TITLE
Duplicate Identifier For relationships in model

### ISSUE THREAD

**Issue by Bhushan001** [mean-expert-official/loopback-sdk-builder#430]
#### What type of issue are you creating?
- [ ] Bug

#### What version of this module are you using?
- [ ] 2.1.0-rc.10.2

I created services for my angular app using sdk builder.
But when I try to run my angular project I get below errors:

> Duplicate identifier 'dept'

I have created attribute dept in my model.json  as 

    `"properties": {
        "dept": {
          "type": "object"
        }
    }`
and mentioned it in my relations as : 

    `"relations": {
        "dept": {
          "type": "belongsTo",
          "model": "Dept",
          "foreignKey": ""
        }
    }`
 I also get the below error:

> Subsequent variable declarations must have the same type.  Variable 'dept' must be of type 'any', but here has type 'Dept'.

Is there anything wrong with my model?

I tried using `sdk-builder` in loopback project where `model.json ` had only `properties` and no `relations`, It worked correctly.
please help.
Thanks

**Comment by Legited** [comment]
You can remove "dept" property, since its a related model

**Comment by jonathan-casarrubias** [comment]
@Legited thanks for helping with the answer, in deed @Bhushan001 you should not define the property and use the FK instead (Actually loopback will automatically do that for you)
