### ISSUE TITLE
Bad Request: ?filter=undefined

### ISSUE THREAD

**Issue by bitingedgemick** [mean-expert-official/loopback-sdk-builder#438]
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [x] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:
In rc.10.5 the ?filter queryString is added to the api request when there are no urlParams resulting in a bad request error from the api. 

Changing lines 67-71 of /lib/angular2/shared/services/core/base.ejs to the code below fixes the issue.

if (urlParams.filter) {
   if (LoopBackConfig.isHeadersFilteringSet()) {
      headers.append('filter', JSON.stringify(urlParams.filter));
   } else {
      filter = `?filter=${encodeURI(JSON.stringify(urlParams.filter))}`;
   }
}

**Comment by jonathan-casarrubias** [comment]
@bitingedgemick cool thanks, I'm adding the patch for the next version
