### ISSUE TITLE
ngc fails for SDKBrowserModule

### ISSUE THREAD

**Issue by enko** [mean-expert-official/loopback-sdk-builder#439]
#### What type of issue are you creating?
- [X] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [X] 2.1.0-rc.5 (2.1 Release Candidate 5)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

If I try to build my ionic app with a generated API I get this error:

```
Error: Error encountered resolving symbol values statically. Calling function 'SDKBrowserModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbo AppModule in /home/tim/flyacts/api-generator-bug/fe/src/app/app.module.ts, resolving symbol AppModule in /home/tim/flyacts/api-generator-bug/fe/src/app/app.module.ts
```

I have created a repository to recreate this error:

https://github.com/enko/api-generator-bug

Just clone it and follow the instructions inside the README.md.

**Comment by jonathan-casarrubias** [comment]
@enko I have just compiled the test environment without any problem, I also know from other projects running AoT, would you mind to update your SDK to see if the issue persists?

**Comment by enko** [comment]
@jonathan-casarrubias had you any time looking into this? The Repository I provided contains every ounce of code that is needed to reproduce this problem. Can I support you in any way?

**Comment by enko** [comment]
@jonathan-casarrubias I figured it out! I publish the sdk as a package and I compiled it, but with tsc and not with ngc. After I started it to compile it with ngc I did not get any errors any more. I figured it out, because the angular compile had internaly no metadata available on the annotation.

**Comment by jonathan-casarrubias** [comment]
@enko I reviewed your repo and I was unsure about the structure, but I was unable to figure out your issue, I'm glad you were able to fix it, I'll use it as future reference.

Cheers
Jon
