### ISSUE TITLE
Implement Custom Headers

### ISSUE THREAD

**Issue by jonathan-casarrubias** [mean-expert-official/loopback-sdk-builder#441]
#### What type of issue are you creating?
- [ ] Bug
- [X] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [X] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

We need to have the ability to send custom headers on each request, not always the loopback token will be sent as authorization token

**Comment by gauravb12** [comment]
Got this issue.
How to pass header queries (as function) to the loopback-sdk-builder generated APIs

Generated API
`public getData(customHeaders?: Function): Observable<any> { }`

I am calling the above API as 
`this.someApi.getData()`
How do I pass the header in the above call. I need to pass query parameters like `?param=1001`

Any help would be appreciated!
