### ISSUE TITLE
Fix missing property in base service

### ISSUE THREAD

**Issue by jonathan-casarrubias** [mean-expert-official/loopback-sdk-builder#442]
#### What type of issue are you creating?
- [X] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [X] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:
When io is disabled there is a missing connection property that might cause compilation issues

**Comment by enko** [comment]
This does not work. 

In base.ejs on Line 53 it reads `<% if ( isIo !== 'enabled' ){` I think this should be `<% if ( isIo === 'enabled' ){`.

**Comment by jonathan-casarrubias** [comment]
@enko thanks for detecting this, I just published version 2.1.0-rc.12.1 that actually fixes that..

Cheers
Jon
