### ISSUE TITLE
Generated Angular SDK services import all rxjs operators

### ISSUE THREAD

**Issue by Legited** [mean-expert-official/loopback-sdk-builder#448]
#### What type of issue are you creating?
- [ ] Enhancement

#### What version of this module are you using?
FireLoop Version: 1.0.0-beta.2.5
loopback-sdk-builder: "2.1.0-rc.12.1"

#### Please add a description for your issue:
Generated Angular SDK services have `import { Observable } from 'rxjs/Rx'` which imports all operators that increase the build size. At the moment I have to manually change them to `import { Observable } from 'rxjs/Observable'` after every `fireloop sdk`

**Comment by jonathan-casarrubias** [comment]
@Legited not sure if you tried to run the TEST environment, but if you do you will see your changes breaks the project in many cases.

It is possible that this patch works for you in your local project, but this will definitely break others projects.

Please verify that your PR does not successfully pass the continuos integration process.

https://travis-ci.org/mean-expert-official/loopback-sdk-builder/builds/247373006?utm_source=github_status&utm_medium=notification

**Comment by Legited** [comment]
@jonathan-casarrubias yes I know it doesn't pass. I'd like to fix it, but I've had a problem with testing. Cloned development branch and getting an error when running `npm test` :

```
> fireloop@1.0.0 build:sdk:ng2web /Volumes/Mac_Drive/Jack_Daniels/Web_Projects/misc/loopback-sdk-builder/tests/fireloop
> lb-sdk server/server.js ../ng2web/src/app/shared/sdk -d ng2web -i enabled -w enabled -v disabled -f disabled

module.js:487
    throw err;
    ^

Error: Cannot find module 'underscore.string'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Volumes/Mac_Drive/Jack_Daniels/Web_Projects/misc/loopback-sdk-builder/node_modules/underscore.inflections/lib/underscore.inflections.js:266:13)
    at Object.<anonymous> (/Volumes/Mac_Drive/Jack_Daniels/Web_Projects/misc/loopback-sdk-builder/node_modules/underscore.inflections/lib/underscore.inflections.js:279:4)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
npm ERR! code ELIFECYCLE
```

**Comment by jonathan-casarrubias** [comment]
@Legited that is weird, I'm verifying in my local to see if I can replicate the test issue, but again is odd because it correctly runs on the CI

**Comment by jonathan-casarrubias** [comment]
@Legited I have just verified and it does correctly run in my local...

I see the underscore.string is a sub-dependency being installed by underscore.inflections

![image](https://user-images.githubusercontent.com/1533239/27702809-e7384fbc-5cca-11e7-9396-dbf850911570.png)

My best guest is that there was a network issue while your NPM was installing the packages, try by manually running NPM install again

**Comment by Legited** [comment]
@jonathan-casarrubias Same issue still, which npm version are you running?

**Comment by jonathan-casarrubias** [comment]
@Legited my npm version is 6.5.0

**Comment by Legited** [comment]
That must be your Node version, latest npm is 5.0.4. Could you try `npm -v`?

**Comment by jonathan-casarrubias** [comment]
@Legited lol you are right, I verified both versions and copy pasted the node one... the NPM is 3.10.9... I'll try to update both node and npm and see if I can replicate, but I can not do that right now since I can mess with my environment at this moment, but I'll try as soon as I can

**Comment by Legited** [comment]
@jonathan-casarrubias no worries, plz ping me when you lock packages (new npm will do it automatically after running `npm install`) and I'll try to do a proper PR 👍
