### ISSUE TITLE
Password property missing on User models

### ISSUE THREAD

**Issue by Legited** [mean-expert-official/loopback-sdk-builder#449]
#### What type of issue are you creating?
- Bug

#### What version of this module are you using?
 2.1.0-rc.12.1

#### Please add a description for your issue:

Models inheriting from base model "User" should retain property "password". Right now I get TS compilation error saying that there is no such property on my "CustomUser" class, but LoopBack throwing error when creating a user, because "password" is required

**Comment by jonathan-casarrubias** [comment]
@Legited thanks for reaching out...

So, I'm not sure why the password property is not being generated for you, my best guess is that you are setting the property as hidden. If you do that, the SDK will not generate.

Unless you modify that, in a vanilla project the password property is always generated.

**Comment by Legited** [comment]
Here's the model definition:

```
{
    "name": "NUser",
    "base": "User",
    "idInjection": true,
    "options": {
        "validateUpsert": true
    },
    "mixins": {
        "TimeStamp": {
            "required": false
        },
        "Stats": [
            {
                "method": "stats",
                "endpoint": "/stats",
                "description": "Statistical information for NUser registers.",
                "type": "model",
                "count": {
                    "on": "createdAt",
                    "by": "index"
                }
            }
        ],
        "ClearBaseAcls": true
    },
    "properties": {
        "firstName": {
            "type": "string",
            "required": true
        },
        "lastName": {
            "type": "string"
        },
        "companyId": {
            "type": "string"
        },
        "avatarUrl": {
            "type":"string"
        }
    },
    "validations": [],
    "relations": {
        "company": {
            "type": "belongsTo",
            "model": "Company",
            "foreignKey": "companyId"
        },
        "messages": {
            "type": "hasMany",
            "model": "Message"
        },
        "conversations": {
            "type": "hasMany",
            "through": "ChatConnection",
            "foreignKey": "userId",
            "model": "ChatRoom"
        }
    },
    "acls": [],
    "methods": {}
}
```

Using 2.1.0rc10.2 for now

**Comment by thiagovito** [comment]
Im having same issue. I generated SDK using the latest build 2.1.0-rc.12.1 and it removed passwords.

![image](https://user-images.githubusercontent.com/904073/27829795-bc0fc3ec-6099-11e7-8311-dc55814ba738.png)

**Comment by Paulillo16** [comment]
I also have the same error.
I think the error is caused by a change of the loopback native user model.

$workspace_my_proyect/node_modules/loopback/common/models/user.json:
{
  "name": "User",
  "properties": {
    "realm": {
      "type": "string"
    },
    "username": {
      "type": "string"
    },
    "password": {
      "type": "string",
      "required": true
    },
    "email": {
      "type": "string",
      "required": true
    },
    "emailVerified": "boolean",
    "verificationToken": "string"
  },
  "options": {
    "caseSensitiveEmail": true
  },
  **"hidden": ["password", "verificationToken"],**
  "acls": [
    {
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    },
    {
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW",
      "property": "create"
    },
    {
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "ALLOW",
      "property": "deleteById"
    },
    {
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW",
      "property": "login"
    },
    {
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW",
      "property": "logout"
    },
    {
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "ALLOW",
      "property": "findById"
    },
    {
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "ALLOW",
      "property": "patchAttributes"
    },
    {
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "ALLOW",
      "property": "replaceById"
    },
    {
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW",
      "property": "verify",
      "accessType": "EXECUTE"
    },
    {
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW",
      "property": "confirm"
    },
    {
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW",
      "property": "resetPassword",
      "accessType": "EXECUTE"
    },
    {
      "principalType": "ROLE",
      "principalId": "$authenticated",
      "permission": "ALLOW",
      "property": "changePassword",
      "accessType": "EXECUTE"
    },
    {
      "principalType": "ROLE",
      "principalId": "$authenticated",
      "permission": "ALLOW",
      "property": "setPassword",
      "accessType": "EXECUTE"
    }
  ],
  "relations": {
    "accessTokens": {
      "type": "hasMany",
      "model": "AccessToken",
      "foreignKey": "userId",
      "options": {
        "disableInclude": true
      }
    }
  }
}

**Comment by thiagovito** [comment]
Thanks @Paulillo16 
This is very odd. I did not have the user.json file in my project. In fact after I added it when I generate the SDK files it removed few important methods on my extended models such as Login, Logout, and others :(

Any idea?

**Comment by thiagovito** [comment]
@Paulillo16 Sorry Ignore what I just said. I was looking in the wrong folder. Its the one in the node_modules. $workspace_my_proyect/node_modules/loopback/common/models/user.json:

**Comment by Paulillo16** [comment]
In my case, I have two projects:

1. Client: Contains the view of the application implemented with Angular 2. This is where I use the SDK generated.
2. Server: Contains application logic, models, etc.

User.json is located in the my server project.

And for the moment I solved the problem back to the previous version of user.ts file (located into SDK generated - project 1. Clientr).

**Comment by thiagovito** [comment]
@Paulillo16 
I have same structure as yours. This is exactly what I did. I fixed it on my user.ts file.

**Comment by jonathan-casarrubias** [comment]
Hey @Paulillo16 thanks for finding the change in the loopback side, that provides the problem... so the possible solution would be to overwrite the hidden: property in your user based model, so you expose that again.

Unfortunately if that is a hidden property there is nothing I can do to fix that in the SDK side, so just try adding the following in your user based model:

````json
{
  "hidden": ["verificationToken"],
}
````

Regards,
Jon

**Comment by Legited** [comment]
@jonathan-casarrubias Wasn't "password" always hidden on User model? Also if you unhide it, it will be included in api requests

**Comment by Paulillo16** [comment]
@jonathan-casarrubias are right. The "password" always hidden on user model.

The difference is that in the previous version of loopback-sdk-builder, it was generated
the user.json model SDK with "password" and "verificationToken". And in the current version, it is not generating user.json model SDK with "password" and "verificationToken".

Then, I do not know the reason for the error.

**Comment by jonathan-casarrubias** [comment]
@Legited you are totally right it was never exposed, you could not see that on the loopback explorer...

I'm not sure then if before was internally exposed and now it is not, I'm really not sure what is going on now, the latests published versions didn't modify anything related to users nor anything related to models, so I will need to go and debug the entire flow and see what the problem might be.

**Comment by jonathan-casarrubias** [comment]
ok I was able to reproduce the issue, I don't think is a SDK issue... This is what I did to replicate,

I have a project with SDK RC 12 and for me it was generating the properties, but for a team member of the same project it wasn't creating the properties.

So, I moved my node_modules to node_modulesBK and then did `$npm install` again and after that I'm able to reproduce the error, so there is a change in a loopback module that introduced this issue, is not the SDK but now the problem is that bug needs to be located

**Comment by jonathan-casarrubias** [comment]
I verified and in fact the SDK have no more access to the password property, I'm adding work around to include it for those user based models.

**Comment by jonathan-casarrubias** [comment]
Guys I have published a work around for this issue, unfortunately for some weird and unrelated reason the continuos integration is failing, though I won't merge into master for now until I fix that, I did publish to NPM because the patch is really small and should not affect any other functionality.

Try installing,  2.1.0-rc.12.2 from NPM and the password property now will be generating regardless is hidden or not, or whatever the LB problem is
