### ISSUE TITLE
Add empty instance factory

### ISSUE THREAD

**Issue by bonaventoora** [mean-expert-official/loopback-sdk-builder#451]
#### What type of issue are you creating?
- [ ] Bug
- [x] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [x] 2.1.0-rc.12.1 (2.1 Release Candidate 12.1)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

I needed a way to ease creation of reactive forms in angular, especially I didn't want to manually type model properties into FormBuilder methods. So I added a static method that returns an instance of model with properties seeded with default values (properties only, relations are not included).

Example:

```json
// model.json
{
  "name": "ContactPerson",
  "base": "PersistedModel",
  "idInjection": true,
  "properties": {
    "active": {
      "type": "boolean"
    },
    "first_name": {
      "type": "string"
    },
    "last_name": {
      "type": "string"
    },
    "position": {
      "type": "string"
    },
    "responsibility_area": {
      "type": "string"
    },
    "pesel": {
      "type": "string"
    },
    "phones": {
      "type": ["ContactPersonPhone"]
    },
    "emails": {
      "type": ["ContactPersonEmail"]
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```
would produce:

```typescript
// ContactPerson.ts
public static emptyInstanceFactory() {
    let instance = {   active: false,
       first_name: '',
       last_name: '',
       sex: '',
       position: '',
       responsibility_area: '',
       pesel: '',
       phones: <any>[],
       emails: <any>[],
       id: 0,
     };
    return ContactPerson.factory(instance);
  }
```

So when a reactive form is needed, it can be created this way:
```typescript
// in component:
this.form = this._formBuilder.group(ContactPerson.emptyInstanceFactory());
```

Pull request will follow shortly.

**Comment by jonathan-casarrubias** [comment]
@bonaventoora not sure if you are aware, but there is a SDK flag that already allows you to set default values on your model instances.

If the defaults flag is enabled, then when you use the Model.factory() method it will return an object with the properties already initialized.

Would you mind to explain why implementing this new feature instead of using the  flag `-v enabled` and then simply use the factory method?

````js
this.form = this._formBuilder.group(ContactPerson.factory());
````

**Comment by jonathan-casarrubias** [comment]
@bonaventoora any update on this?

**Comment by bonaventoora** [comment]
Sorry for the delay. I missed that `-v` option, looks like this PR can be discarded.

**Comment by jonathan-casarrubias** [comment]
@bonaventoora no worries I do appreciate you taking the time to work on this and send your PR.

Cheers
Jon
