### ISSUE TITLE
"Cannot find name <MODEL>"

### ISSUE THREAD

**Issue by DerekTBrown** [mean-expert-official/loopback-sdk-builder#455]
#### What type of issue are you creating?
- [X] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [X] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

#### Please add a description for your issue:

After compilation of the SDK, I get Typescript errors telling me that it couldn't find the Typescript classes of my models:

```
ERROR in /Users/derekbrown/Projects/pocketflint/src/web/sdk/services/custom/Device.ts (285,59): Cannot find name 'device'.

ERROR in /Users/derekbrown/Projects/pocketflint/src/web/sdk/services/custom/Host.ts (46,66): Cannot find name 'host'.
```

**Comment by DerekTBrown** [comment]
The problem seems to have to do with capitalization in the typings.  Some of my models are capitalized.  When it generates the type specification, it generates them in lowercase:

```Javascript
  public findModels(customHeaders?: Function): Observable<device[]> {
```

But should be this:

```Javascript
  public findModels(customHeaders?: Function): Observable<Device[]> {
```

**Comment by DerekTBrown** [comment]
Confirming that capitalization was the issue. By renaming my models from `device` => `Device`, etc, it worked.  While this might be the standard naming convention, would probably be good in the long run to standardize capitalization.

**Comment by jonathan-casarrubias** [comment]
@DerekTBrown thanks for reaching out...

Hey so, not following the camel cased naming convention for all of your models would not only generate this issue but many others more. Having lowercased model names is not supported, so I will give you the advice for you to name your models using the camel case convention, this way you will avoid other issues ahead

Regards,
Jon

**Comment by DerekTBrown** [comment]
@jonathan-casarrubias having assumptions about case in input variables is terrible style.  This needs to be refactored.

**Comment by jonathan-casarrubias** [comment]
@DerekTBrown is just that the assumption is based on standard conventions, anyway... If you feel this needs to be refactored to allow unconventional model names, then PRs are welcome :)
