### ISSUE TITLE
httpVerb is strictly checked even on capital

### ISSUE THREAD

**Issue by KingsDevelopment** [mean-expert-official/loopback-sdk-builder#465]
#### What type of issue are you creating?
- [X] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [X] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:
in `lib/angular2/shared/services/custom/service.ejs` you are making use of `httpVerb`, but whenever a check is done on `httpVerb`, it's always uppercase. But in the loopback documentations state, that the verb can also be lowercase. Just like in the examples: https://loopback.io/doc/en/lb2/Remote-methods.html

The problem is, that now that we use lowecase, the template checks on uppercase. So post verbs are not having a postbody, but the parameters are set in the url.

**Comment by jonathan-casarrubias** [comment]
@KingsDevelopment thanks for reaching out..

Hey so, would you mind to verify if the following patch works for your case?

lib/angular2/shared/services/custom/service.ejs
````js
25:  var httpVerb = (action.getEndpoints ? action.getEndpoints()[0].verb : action.getHttpMethod()).toUpperCase();
````
