### ISSUE TITLE
Data type check issue

### ISSUE THREAD

**Issue by dreamdevil00** [mean-expert-official/loopback-sdk-builder#475]
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [x] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

Sorry for my poor English, firstly.

It is something about  data type check in ```function buildObservableType(model, method)```
which in file  ```lib/angular2/index.js```

The code:
```
function buildObservableType(model, method) {
    let type = 'any';
    if (
      method.name.match(/(^createMany$|^find)/g) ||
      (
        typeof method.returns === 'object' &&
        (method.returns.type === 'array' || Array.isArray(method.returns.type))
      )
    ) type = `${model.name}[]`;
    if (method.name.match(/(^create$|upsert|^findBy|^findOne$)/g)) type = model.name;
    return type;
  }
```

I found official document [Loopback Types ](http://loopback.io/doc/en/lb3/LoopBack-types.html) describes  ``` The type name is case-insensitive;```
so the code ``` method.returns.type === 'array ``` may make mistakes if user specifies the data type 'Array'

Please check

**Comment by barocsi** [comment]
It also messes up like this>
```
    Actor.remoteMethod(
        'findByName',
        {
```
results
```
 public findByName(name: any, filters: any = {}, customHeaders?: Function): Observable<actor> {
```
where actor should be Actor
