### ISSUE TITLE
How to use relations in models

### ISSUE THREAD

**Issue by WhatzzUp** [mean-expert-official/loopback-sdk-builder#479]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [x] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [x] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

Hello guys,

i try to create some standard records if someone create a new record from my "customer" model.
Our "users" have one or more "dashboards" with one or more "widgets", so its necessary if a new user is created a related dashboard with related widgets must be created.

customer ->(one or many) userDashboard -> (has one or many)-> widgets

Following describes my current state:

i defined the relationship in my 'customer.js'

```
"relations": {
    "userDashboard": {
      "type": "hasMany",
      "model": "userDashboard",
      "foreignKey": "fkey_user_id"
    }
  },
```

init a afterSave hook in my "customer.ts"
```
hooks: {
    beforeSave: {name: 'before save', type: 'operation'},
    afterSave: {name: 'after save', type: 'operation'}
  },
```
the "afterSave" method
```
 afterSave(ctx: any, next: Function): void {
    console.log('customer: After Save');
   //get userDashboard model
    this.userDashboard = this.model.app.models.userDashboard; 
    this.createUserDashboard(ctx.instance);
    next();
  }
```

My current method to create the records:
```
 createUserDashboard(instance: any) {
    let userID = instance.id;
    dashboardSeed['fkey_user_id'] = userID;
    this.userDashboard.findOrCreate(dashboardSeed, (err: any, instance: any, created: any) => {
      //get userWidget  model
      this.userWidget = this.model.app.models.userWidget;
      widgetSeed["fkey_dashboard_id"] = instance.id;
      widgetSeed["fkey_user_id"] = userID;
      this.userWidget.findOrCreate(widgetSeed, (err: any, instance: any, created: any) => {
        console.log(err);
        console.log(instance);
        console.log(created)
      })
    })
  }
```

[Loopback Doku "HasMany relations"](https://loopback.io/doc/en/lb3/HasMany-relations.html)
> Once you define a “hasMany” relation, LoopBack adds a method with the relation name to the declaring model class’s prototype automatically. For example: Customer.prototype.orders(...)

According to loopback documentation i should do sth like this:
```
customer.userDashboard([filter],(data:any)=> {
  ...
});
```
but this didnt work (userDashboard is undefined). I have no idea what i´m doing wrong.
Can someone explain, how to implement "related" records in hooks or how i general can use relation in the model/remote etc.? Or is a hook the correct place for this? 
Important: We´r using **fireloop** with the current version 1.0.0-beta.2.6

The whole 'custom.ts' file

```
import {Model} from '@mean-expert/model';

const dashboardSeed: any =
  {
    designation: 'admin@limes.rocks',
    description: 'admin',
    icon: 'admin'
  };


const widgetSeed =
  {
    cols: 1,
    rows: 1,
    y: 0,
    x: 0,
    type: 'project-standard',
    maxItemRows: 4,
    dragEnabled: true,
    resizeEnabled: false,
    backgroundColor: 'green',
    icon: 'apps.svg',
    iconColor: 'blue',
    fkey_user_id: 'SuperAdmin',
    fkey_dashboard_id: 'SuperAdmin',
  }
;

/**
 * @module customer
 * @description
 * Write a useful customer Model description.
 * Register hooks and remote methods within the
 * Model Decorator
 **/
@Model({
  hooks: {
    beforeSave: {name: 'before save', type: 'operation'},
    afterSave: {name: 'after save', type: 'operation'}
  },
  remotes: {
    myRemote: {
      returns: {arg: 'result', type: 'array'},
      http: {path: '/my-remote', verb: 'get'}
    }
  }
})

class customer {
  // LoopBack model instance is injected in constructor
  private userDashboard: any;
  private userWidget: any;

  constructor(public model: any) {
  }


  // Example Operation Hook
  beforeSave(ctx: any, next: Function): void {
    console.log('customer: Before Save');
    next();
  }

  // Example Operation Hook
  afterSave(ctx: any, next: Function): void {
    console.log('customer: After Save');
    this.userDashboard = this.model.app.models.userDashboard;
    this.createUserDashboard(ctx.instance);
    next();
  }

  /**
   * @method createUserDashboard
   * @description
   * Create a dashboard width widgets for new users
   **/
  createUserDashboard(instance: any) {
    let userID = instance.id;
    dashboardSeed['fkey_user_id'] = userID;
    this.userDashboard.findOrCreate(dashboardSeed, (err: any, instance: any, created: any) => {
      this.userWidget = this.model.app.models.userWidget;
      widgetSeed["fkey_dashboard_id"] = instance.id;
      widgetSeed["fkey_user_id"] = userID;
      this.userWidget.findOrCreate(widgetSeed, (err: any, instance: any, created: any) => {
        console.log(err);
        console.log(instance);
        console.log(created)
      })
    })
  }

  // Example Remote Method
  myRemote(next: Function): void {
    this.model.find(next);
  }
}

module.exports = customer;

```

Cheers

Chris

**Comment by jonathan-casarrubias** [comment]
Hi @WhatzzUp thanks for reaching out,

Hey so.... Im assuming the issue with the  `customer.userDashboard()` method is in the backend, I'm a little confused because this is the sdk repo so I could also assume this is a front end issue.

Anyway, since you shared the backend model, I will answer in the backend terms.

Question:
How do I execute related methods like `customer.userDashboard()`? (Scoped methods)

Answer:

A scope method is only available from instances and not from models, I'm unable to see `customer.userDashboard()` in your entire custom.ts file,  so I will add an example of how you should use a scoped method.

````js
class customer { 

  constructor(public model:) {
    // Correct use of scoped methods
    this.model.findOne((err: Error, instance) => {
      instance.userDashboard();
    });

     // Incorrect use of scoped methods
     this.model.userDashboard()
  };
}
````

I hope this helps you clarify your question

Cheers
Jon

**Comment by WhatzzUp** [comment]
Hey @jonathan-casarrubias ,

thx for the answer!

I understand now how relations work! Big thx! 

Cheers
Chris

**Comment by jonathan-casarrubias** [comment]
@WhatzzUp I'm glad it helped you, it might be confusing and we all had that specific problem at some point, lol.

See you around.

cheers
Jon
