### ISSUE TITLE
Not able to create SDK, when I have a model inherited from User.

### ISSUE THREAD

**Issue by aaqilniz** [mean-expert-official/loopback-sdk-builder#505]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [x] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [x] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:
I created a model and inherited from PersistentModel, SDK worked fine with that. Then I created a model which inherited from User base class and tried to create SDK, but it failed and resulted in the following error:

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:sdk
"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! delete@1.0.0 build:sdk: `lb-sdk server/server.js ../easy-stats-app-1/src/app/shared/sdk`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the delete@1.0.0 build:sdk script 'lb-sdk server/server.js ../easy-stats-app-1/src/app/shared/sdk'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the delete package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     lb-sdk server/server.js ../easy-stats-app-1/src/app/shared/sdk
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs delete
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls delete
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Muhammad Aaqil\Desktop\delete\npm-debug.log

**Comment by aaqilcs102** [comment]
The above problem shows up if I use api-server, I tried with empty-server it's working totally fine. 
Can't I create SDK for an app with api-server or any other option?

**Comment by jonathan-casarrubias** [comment]
Hi @aaqilcs102 thanks for reaching out,

Hey so... It should work fine with api-server, actually I personally never tested with the empty-server configuration..

Anyway, there is an open issue related to user based models, where if you hide the username it crashes... There is a fix for that in development, it will be published during the next version, though I'm not sure is your exact issue.

Cheers
Jon
