### ISSUE TITLE
Enable withCredentials Option

### ISSUE THREAD

**Issue by jonathan-casarrubias** [mean-expert-official/loopback-sdk-builder#511]
#### What type of issue are you creating?
- [ ] Bug
- [X] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [ ] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:
Community contribution to enable withCredentials option https://github.com/mean-expert-official/loopback-sdk-builder/pull/507

**Comment by robbievandam** [comment]
Hi @jonathan-casarrubias,

Is there going to be an official release/tag for [997856c](https://github.com/mean-expert-official/loopback-sdk-builder/commit/997856c3ac33aa2e70ee9e6df9363f955560bef2) ?
