### ISSUE TITLE
Implements socket "connect_error","connect_failed"

### ISSUE THREAD

**Issue by eduardoarn** [mean-expert-official/loopback-sdk-builder#518]
#### What type of issue are you creating?
- [ ] Bug
- [ x] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [x ] 2.1.0-rc.13.5 (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

I'm implementing using as functions generated by the SDK, but I did not find it to find a correct way to get socket connection problems.

in the implementation of socket.connections.ts, if I am not mistaken, does not contemplate receiving errors, I had to implement at least to test the following code snippet

`public connect(token: AccessToken = null): void {
....
      this.on('connect_error',  (error) => {
        console.log('connect_error:',error);        
      });
      this.on('connect_failed',  (error) => {
        console.log('connect_failed:',error);        
      });
...
`

But as I said, I do not know if I'm doing it the right way, I can thank you for that, if I may.

**Comment by jonathan-casarrubias** [comment]
@eduardoarn look for the loopback-component-realtime on this org to see the instructions to setup the real-time, it seems the backend is not configured... might be?
