### ISSUE TITLE
Generated sdk for angular is not working in angular 5

### ISSUE THREAD

**Issue by dmastag** [mean-expert-official/loopback-sdk-builder#529]
#### What type of issue are you creating?
- [X] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [X] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:
I tried to upgrade my existing angular-cli project to Angular 5 and got a bunch of errors on production builds. I think this has to do with the way rxjs is imported but I am not sure.

**Comment by jonathan-casarrubias** [comment]
Have you tried to update the SDK? yesterday I got a PR related to NG5 and is published now. Try that and see if works!

**Comment by dmastag** [comment]
Yes, I did. Also saw that the Observables are still imported from 'rxjs/Rx'
Though even after updating them all manually, it was still preventing me from production builds.

**Comment by dmastag** [comment]
I tried on a brand new angular5 generated with angular-cli and import the sdk which was failing.
Then I tried to do some manual changes, which are:

replace all
`import { Observable } from 'rxjs/Rx';`
with
`import { Observable } from 'rxjs/Observable';`

And add into `sdk/models/FireLoopRef.ts` the following
`import 'rxjs/add/operator/merge';`

And into `sdk/sockets/socket.connections.ts` and `/sdk/services/core/real.time.ts` the following
`import 'rxjs/add/operator/share';`

It was working on the angular-cli project afterwards to do production builds
`ng build --prod`

**Comment by mrnetforge** [comment]
When can we except new release with fix?

**Comment by jonathan-casarrubias** [comment]
@dmastag thanks for sending the patch, I just landed this in version 2.1.1, please check if everything goes well, also...

The test environment is already using Angular 5, so everything should go fine..

Cheers
Jon

**Comment by dmastag** [comment]
@jonathan-casarrubias thanks for the merge.
Just tested 2.1.1 and its working as intended, am going to close this now.
