### ISSUE TITLE
"JSON Parse error: Unterminated string" only on iOS - broken string in $LoopBackSDK$user

### ISSUE THREAD

**Issue by thiagovito** [mean-expert-official/loopback-sdk-builder#556]
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [ ] 2.1.0-rc.n (2.1 Release Candidate n)
- [x] Other

Write other if any: 2.1.2

#### Please add a description for your issue:
Guys,

We experienced a bug that happens only on iOS (Safari and Chrome). It happens when trying to store cookie with special characters  such as (àáâãèéê, etc). 

The error we get is "JSON Parse error: Unterminated string". We get this problem because if there is any of these characters the JSON string brakes in: **$LoopBackSDK$user**

So to solve that we have changed the following file:
`sdk/storage/stcookie.browser.ts`

we have added: 
`encodeURI(value)` in the **set** method

and
`decodeURI(value)` in **parse** method.

So that cookies are saved with special characters

**Comment by PhilFlash** [comment]
Same problem on IOS

**Comment by jonathan-casarrubias** [comment]
@thiagovito thanks for reaching out, hey so would you mind to send a PR to development with the patches you did to make it work.

I can publish that with the next version 2.2.0 which is about to be published.

Cheers
Jon
