### ISSUE TITLE
StaticInjectionError

### ISSUE THREAD

**Issue by sadhac** [mean-expert-official/loopback-sdk-builder#642]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [X] Question

#### What version of this module are you using?
- [X] 2.0.10 (Stable)
- [ ] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:
Hi
[angsdkerror.log](https://github.com/mean-expert-official/loopback-sdk-builder/files/3015374/angsdkerror.log)

Getting an uncaught exception error when using the model api service in my component. 
Please see log attached and let me know how to resolve it.

**Comment by gezquinndesign** [comment]
I suspect that this is not an issue with the sdk but rather an issue with the Angular module set up. 

For starters, have you included ModelApi in the providers section of the ModelCreateComponent module?

Would need to see your code to be of any more help.

**Comment by sadhac** [comment]
You are correct, its not the sdk. I had to use the AppUserApi service. Thanks! 
Is there a guide/example that has extended user model authentation and authorization with Angular 6+?
