### ISSUE TITLE
Method for to-many relations not accepting array

### ISSUE THREAD

**Issue by mevinDhun** [mean-expert-official/loopback-sdk-builder#88]
I have a model _MeetingRole_ which has many _Permissions_.
To create permissions and add it to a meeting role, i can perform a POST on 
_/MeetingRoles/{id}/permissions_

Now this method can either accept a single _Permission_ object or an array of permissions but the generated code in the sdk treats only single permission:
```javascript
public createPermissions(id: any, data: Permission = undefined) {
    let method: string = "POST";
    let url: string = LoopBackConfig.getPath() + "/" + LoopBackConfig.getApiVersion() +
    "/MeetingRoles/:id/permissions";
    let routeParams: any = {
      id: id
    };
    let postBody: any = {
      data: data
    };
    let urlParams: any = {};
    let result = this.request(method, url, routeParams, urlParams, postBody);
    return result;
  }
```

I suggest renaming the above to _createPermission_ and create another method _createPermissions_ which can take an array of _Permission_. Or update the existing method to make it always accept an array.

**Comment by jonathan-casarrubias** [comment]
@mevinDhun there is already a method to create many is name createMany, so in your case should be something like createManyPermissions.

**Comment by mevinDhun** [comment]
@jonathan-casarrubias  thanks for the quick reply. There is a _createMany_ method in the MeetingRole service which is used to create many meeting roles. There is no method available to create a batch of permissions for a specific meeting role. I checked and _createManyPermissions_ is not present.

**Comment by jonathan-casarrubias** [comment]
@mevinDhun I have verified that there is a missing createMany method when a hasMany relation is implemented, for some reason this problem is not present in hasAndBelongsToMany relation.

I will send a fix for this ASAP.. 

Cheers
Jon

**Comment by jonathan-casarrubias** [comment]
This issue is fixed and will be released in version 2.0.0-rc.9

**Comment by mevinDhun** [comment]
Hi, I just tried v2.0.8 and it has generated the method _createManyPermissions_ but the argument is of type _Permission_ instead of _Permission[]_ or _any_. Can you please have a look?

**Comment by jonathan-casarrubias** [comment]
Hi @mevinDhun thanks for reporting haven't been in that part of the code for a while so I may moved something that unintentionally affected this feature.

I will verify and publish a fix asap.

Cheers!
Jon
