### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by camerlab** [mean-expert-official/loopback-sdk-builder#98]
Hi,
I am running some test on a machine with Ubuntu 16.04, Angular2 rc5, and webpack.
I have generated an sdk following the instructions and everything went smooth. However after inserting the SDKModule into a vanilla Angular2 app from angular-cli@webpack, I get the following error in browser console (after running ng serve).

Uncaught TypeError: Cannot read property 'prototype' of undefined

__extends	@	Category.ts:17
(anonymous function)	@	Category.ts:53
(anonymous function)	@	Category.ts:718
__webpack_require__	@	bootstrap 9219e6a…:52
(anonymous function)	@	index.ts:1
__webpack_require__	@	bootstrap 9219e6a…:52
(anonymous function)	@	base.service.ts:8
__webpack_require__	@	bootstrap 9219e6a…:52
(anonymous function)	@	Meeting.ts:1505
__webpack_require__	@	bootstrap 9219e6a…:52
(anonymous function)	@	sdk.module.ts:36
__webpack_require__	@	bootstrap 9219e6a…:52
(anonymous function)	@	app.module.ts:5
__webpack_require__	@	bootstrap 9219e6a…:52
(anonymous function)	@	index.ts:3
__webpack_require__	@	bootstrap 9219e6a…:52
(anonymous function)	@	main.ts:9
__webpack_require__	@	bootstrap 9219e6a…:52
(anonymous function)	@	ws (ignored):1
__webpack_require__	@	bootstrap 9219e6a…:52
webpackJsonpCallback	@	bootstrap 9219e6a…:23
(anonymous function)	@	main.bundle.js:1

Category.ts and Meeting.ts are model generated by the sdk.
Could you please me help me to debug it? Do you have an example of an app using an sdk generated by the tool?

**Comment by camerlab** [comment]
I found that it works well in a fresh angular2-cli@webpack installation if I disable pubsub in the loopback server

**Comment by jonathan-casarrubias** [comment]
@camerlab I'm presenting the same issue, I rolled back to the stable version before the webpack patch from yesterday and it does work ok regardless the io functionality.

I'm verifying the issue and send a fix ASAP.

Thanks for reporting,
Jon

**Comment by camerlab** [comment]
Ok. Thank you Jonathan.

**Comment by jonathan-casarrubias** [comment]
@camerlab I have just published a hot fix for this issue, basically I reverted the patch and now it should work as documented

**Comment by jonathan-casarrubias** [comment]
For future reference:

WebPack is not so Barrels friendly, therefore we won't be able to load everything from './shared'; as we were doing before RC5.

For anyone having issues please, read the WIKI documentation and import files from

For Models: shared/sdk/models 
For Services: shared/sdk/services

IMPORTANT: Do not try to load everything from ./shared when using webpack.
